### ISSUE TITLE
vcd_vapp_vm: tenant user unable to use catalog belonging to an admin organization

### ISSUE THREAD

**Issue by anttiah** [vmware/terraform-provider-vcd#1022]
Hello

I'm trying to upgrade my modules from vcd v3.6.0 to v3.8.2 but I can't get `vcd_vapp_vm` resource working with this new `vapp_template_id` argument. The catalog and vapp template I need to use are located in an admin organization while my resources must be created in an end user (tenant) organization.

The problem is that `vcd_catalog` and `vcd_catalog_vapp_template` data sources require use of a provider but it can't be the same provider which is used in my resources because `org` is mandatory argument of a provider and the catalog & template are not found in the tenant organization.

If I try to define another provider with correct organizaion just for `vcd_catalog` and `vcd_catalog_vapp_template` data sources, it doesn't work either because `user` and `password` are also mandatory arguments of a provider but the organization in question is admin org and my tenant user is not allowed to log on.

If I don't define new provider and just add `org` argument to `vcd_catalog` and `vcd_catalog_vapp_template` data sources, `terraform plan` prompts missing provider arguments interactively and eventually fails due to missing login infromation.

This issue did not exist in vcd v3.6.0  because `catalog_name` and `template_name` arguments of the `vcd_vapp_vm` resource worked across organization boundaries.

### Terraform Version
```
Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.8.2
```

### Affected Resource(s)
Combination of
- `vcd_catalog`
- `vcd_catalog_vapp_template`
- `vcd_vapp_vm`

### Terraform Configuration Files
Simplified and anonymized example which should be relatively easy to complete. Note two different `vcd` providers with different organizations and  how `vcd_catalog` & `vcd_catalog_vapp_template` must use different provider than the rest of the resources. This does not work because of the reasons explained above.
 
```hcl {.line-numbers}
terraform {
  backend "redacted" {}
  required_providers {
    vcd = {
      source  = "vmware/vcd"
      version = "3.8.2"
    }
  }
}

variable "api_url" {
  type = string
  default = "https://vcloud/api"
}

variable "tenant_user" {
  type = string
}

variable "tenant_password" {
  type      = string
  sensitive = true
}

provider "vcd" {
  alias     = "tenant_provider"
  url       = var.api_url
# Login works with these
  user      = var.tenant_user
  password  = var.tenant_password
  auth_type = "integrated"
# Catalog is not here
  org       = "tenant_org"
  vdc       = "tenant_vdc"
}

provider "vcd" {
  alias     = "admin_provider"
  url       = var.api_url
# Login to admin_org fails with these
  user      = var.tenant_user
  password  = var.tenant_password
  auth_type = "integrated"
# Catalog is here
  org       = "admin_org"
  # vdc is unknown
}

resource "vcd_vapp" "test_app" {
  provider = vcd.tenant_provider
  name     = "test_app"
}

resource "vcd_vapp_org_network" "test_network" {
  provider         = vcd.tenant_provider
  vapp_name        = vcd_vapp.test_app.name
  org_network_name = "tenant_network"
}

data "vcd_catalog" "test_catalog" {
  provider = vcd.admin_provider
  name     = "Some Catalog"
}

data "vcd_catalog_vapp_template" "test_template" {
  provider   = vcd.admin_provider
  catalog_id = data.vcd_catalog.test_catalog.id
  name       = "Some Template"
}

# This does not work
resource "vcd_vapp_vm" "test_vm" {
  provider               = vcd.tenant_provider
  vapp_template_id       = data.vcd_catalog_vapp_template.test_template.id
  vapp_name              = vcd_vapp.test_app.name
  name                   = "test_vm"
  computer_name          = "test_vm"
  # ...
}

# But the deprecated syntax still works
resource "vcd_vapp_vm" "test_vm" {
  provider               = vcd.tenant_provider
  catalog_name           = "Some Catalog"
  template_name          = "Some Template"
  vapp_name              = vcd_vapp.test_app.name
  name                   = "test_vm"
  computer_name          = "test_vm"
  # ...
}

```

### Expected Behavior
Plan is created.

### Actual Behavior
Depending on organization names, plan fails either because catalog is not found or credentials are not accepted.

### Steps to Reproduce
`terraform plan`

### User Access rights 
Organization admin of a vCloud tenant organization. No system administrator access.

**Comment by dataclouder** [comment]
This works in my environment, using aliases (the catalog was already shared)

```
variable "org1" {}
variable "org2" {}
variable "user1" {}
variable "user2" {}
variable "password1" {}
variable "password2" {}
variable "catalog" {}
variable "template" {}
variable "url" {}

provider "vcd" {
  alias                = "org1"
  user                 = var.user1
  password             = var.password1
  auth_type            = "integrated"
  saml_adfs_rpt_id     = ""
  url                  = "${var.url}/api"
  sysorg               = var.org1
  org                  = var.org1
  allow_unverified_ssl = "true"
  max_retry_timeout    = 600
  logging              = true
  logging_file         = "go-vcloud-director-1.log"
}

provider "vcd" {
  alias                = "org2"
  user                 = var.user2
  password             = var.password2
  auth_type            = "integrated"
  saml_adfs_rpt_id     = ""
  url                  = "${var.url}/api"
  sysorg               = var.org2
  org                  = var.org2
  allow_unverified_ssl = "true"
  max_retry_timeout    = 600
  logging              = true
  logging_file         = "go-vcloud-director-2.log"
}

data "vcd_catalog" "cat1" {
  provider = vcd.org1
  name     = var.catalog
}

data "vcd_catalog" "cat2" {
  provider = vcd.org2
  org      = var.org1
  name     = var.catalog
}

data "vcd_catalog_vapp_template" "template" {
  provider   = vcd.org2
  catalog_id = data.vcd_catalog.cat2.id
  name       = var.template
}

output "cat1" {
  value = data.vcd_catalog.cat1.is_shared
}

output "template" {
  value = data.vcd_catalog_vapp_template.template
}
```

**Comment by anttiah** [comment]
Thank you for your effort! Looks like the winning combnation is to use both `provider` and `org` with `vcd_catalog` only, and just `provider` with the rest. Or at least it seems like it because now I can't repro my issue anymore.

Have to make couple of tests in the actual production environment but so far it's looking good 🤞

**Comment by dataclouder** [comment]
"org" is needed with catalog because you can't use the default tenant Org, as the catalog belongs to another one.
Please close this issue if your whole workflow runs correctly.
