### ISSUE TITLE
Error: [ENF] entity not found when manually deleting resource

### ISSUE THREAD

**Issue by Jasperswaagman** [vmware/terraform-provider-vcd#1028]
Hello,

I'm wondering if something is wrong with the following usecase:

I apply the resources defined below which works perfectly fine. After **manually** removing the vApp in which most of the resources are placed I receive the following error:

```hcl
Error: error finding vApp. [ENF] entity not found
```

which makes sense because we just manually deleted the vApp. TF does recognise the vApp has been changed/deleted:
```hcl
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # vcd_vapp.main has been deleted
  - resource "vcd_vapp" "main" { 
```
Since the vApp is missing I expect TF to (re)create the vApp. Am I making a wrong assumption and is this working as intended?

### Terraform Version
```
Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/vmware/vcd v3.8.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_nat_rules
- and more

### Terraform Configuration Files

```hcl
provider "vcd" {...}
resource "vcd_vapp" "main" {...}
data "vcd_catalog" "main" {...}
data "vcd_catalog_vapp_template" "main" {...}
resource "vcd_vapp_vm" "main" {...}
resource "vcd_vapp_network" "main" {...}
resource "vcd_network_isolated_v2" "main" {...}
resource "vcd_vapp_org_network" "main" {...}
resource "vcd_vapp_nat_rules" "main" {...}
```

### Expected Behavior
I expect TF to create the vApp resource because it is missing.

### Actual Behavior
TF says it can't find the entity on plan/apply and stops processing.

### Important Factoids
- VMware Cloud Director version 10.4
- Tested it locally and also with TFEnterprise.

**Comment by dataclouder** [comment]
BTW, if you wish to delete a resource cleanly, you can do that with Terraform, which has the additional benefit of removing also the depending resources:

```
terraform destroy -target vcd_vapp.vappName
```
