### ISSUE TITLE
vcd_security_tag data source

### ISSUE THREAD

**Issue by danielhanaj** [vmware/terraform-provider-vcd#1044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Is it possible to add data source for "vcd_security_tag"? 
At the moment we cannot re-use existing security tags that are used for creating NSX-T dynamic groups

### New or Affected Resource(s)

* vcd_security_tag

### Terraform Configuration (if it applies)

```hcl
data "vcd_security_tag" "my_tag" {
  name   = "test-tag"
}
```

**Comment by danielhanaj** [comment]
I would like to use existing security tags and assign those to existing and newly created VMs for proper firewall grouping. Security tags already exist and has been manually created in the UI. Using "vcd_security_tag" resource and specifying exactly same security tag name that has been manually created in UI, removes manually created one and replaces it with the one created by Terraform. I believe that is expected behaviour. In theory we still have security tag with same value but: 
- All VMs that had manually created security tag assigned does not have that anymore since exisitng one has been removed
- Security Groups that group VMs based on security tags does not recognize new tag created by Terraform.

**Comment by Didainius** [comment]
@danielhanaj ,
Would the recent implementation of https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#security_tags help? (https://github.com/vmware/terraform-provider-vcd/pull/1006)

**Comment by danielhanaj** [comment]
> @danielhanaj , Would the recent implementation of https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#security_tags help? (#1006)

@Didainius That did the trick. Thanks a lot.
