### ISSUE TITLE
Not possible to handle more than 128 stroage profiles

### ISSUE THREAD

**Issue by Kernal87** [vmware/terraform-provider-vcd#1066]
Howdy 

We have the problem that we now have more than 128 storage profiles. We now get the following error message when creating a VDC 
`
│ Error: [getVcdVdcInput] error retrieving storage profile from provider VDC : [QueryWithNotEncodedParams] FATAL - more than 128 storage profiles found. Refactory needed`

Is it possible to increase the value? 

Best Regards 

Claudio

**Comment by dataclouder** [comment]
Thanks for submitting this issue.
We know what the problem is, and we'll fix it.

**Comment by dataclouder** [comment]
Fixed in version [v3.10.0](https://github.com/vmware/terraform-provider-vcd/releases/tag/v3.10.0)
