### ISSUE TITLE
vcd_nsxt_app_port_profile return more than a single entry when used in a VDC Group

### ISSUE THREAD

**Issue by smolinari-obs** [vmware/terraform-provider-vcd#1090]
Hello,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved
for bug reports and feature requests. For general usage questions, please see:
https://www.terraform.io/community.html.

### Terraform Version
$ terraform -v
Terraform v1.5.1
on linux_amd64

### Affected Datasource
- vcd_nsxt_app_port_profile

### Terraform Configuration Files

```hcl
data "vcd_nsxt_app_port_profile" "test" {

  org        = local.vdc_org
  context_id = local.vdc_group_id
  name       = "HTTP"
  scope      = "SYSTEM"
}

output "debug" {
  value = data.vcd_nsxt_app_port_profile.test
}
```

### Debug Output
ft.log => https://gist.github.com/smolinari-obs/91be47935a0caf9a63e596875baa047d

### Expected Behavior
We should have only one result per application profile like in the UI.

### Actual Behavior
The provider return this error :  │ Error: Expected exactly one NSX-T Application Port Profile. Got '2'

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

**Comment by Didainius** [comment]
I am closing this in favor of #1058.
