### ISSUE TITLE
vcd_vapp_vm with dualstack ip adress pool ipv4 and ipv6

### ISSUE THREAD

**Issue by riconem** [vmware/terraform-provider-vcd#1100]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Creation of a `vcd_vapp_vm` with dualstack ip adress pools in the network section. Currently there are no options for that. You can create a vm with an ip adress pool but you can't choose if it's ipv4 or ipv6 like in the GUI. It's some kind of random behaviour.

```hcl
resource "vcd_vapp_vm" "web2" {
  vapp_name        = vcd_vapp.web.name
  name             = "web2"
  vapp_template_id = data.vcd_catalog_vapp_template.linux.id
  memory           = 2048
  cpus             = 1

  network {
    type               = "org"
    name               = "net"
    ip_allocation_mode = "POOL"
    adapter_type       = "VMXNET3"
  }
}
```

When the code is applied and you have a dualstack network with ipv4 and ipv6. It happens that there are a ipv6 ip adress on an ip4 adress pool. It also doesn't add the other ipv4 adress to the pool.

![image](https://github.com/vmware/terraform-provider-vcd/assets/27899109/3551252f-c4de-455e-b41b-fe4565a646c2)

Inside the GUI you can choose a pool for ipv4 and ipv6. So it should look like the following.

![image](https://github.com/vmware/terraform-provider-vcd/assets/27899109/19f7b7df-3d23-4530-a05a-1416ab6c6718)

### New or Affected Resource(s)

* vcd_vapp_vm
* vcd_vm
* vcd_vapp

**Comment by riconem** [comment]
I also tried to implement it, but I am struggeling with it and documented in this [issue](https://github.com/vmware/go-vcloud-director/issues/604). Does someone know how to fix the xml error? I am assume that I am using the wrong schemas.

[terraform-provider-vcd](https://github.com/riconem/terraform-provider-vcd/tree/add-network-connection-elements)
[go-vcloud-director](https://github.com/riconem/go-vcloud-director/tree/v2.21.0-add-network-connection-elements)

**Comment by nxcc** [comment]
hi @riconem, just found out how to fix the xml. Looks like order of elements in NetworkConnection is important. You have to move `SecondaryIpAddress` just below `IPAddress`, and `SecondaryIpAddressAllocationMode` below `IPAddressAllocationMode` in the struct. This also changes the order in the XML. Just tied it out and it works for me.

**Comment by riconem** [comment]
Thank you @nxcc. I will try.

**Comment by danielmasur** [comment]
> Thank you @nxcc. I will try.

@riconem Have you had a chance to test this? My couple first tests looked promising.

**Comment by Didainius** [comment]
Hello,
Just to let you know - we see this is a demanded feature and we're working on it. I am progressing on testing it and looking for possible side effects now as VM operations are quite tricky and based on XML which often gives surprises.

**Comment by Didainius** [comment]
Hello,
I have gone through testing and would like to ask if any of the interested parties could test. Field names are such (they match the approach that we have in Org VDC networks (e.g. https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/network_routed_v2#secondary_gateway)

<img width="681" alt="image" src="https://github.com/vmware/terraform-provider-vcd/assets/15804230/061f3dae-0f5b-44b2-8207-a9ccc9ac8314">

**Comment by riconem** [comment]
Thank you. I will test it. Could you also provide your [go-vcloud-director](https://github.com/Didainius/go-vcloud-director) version? I couldn't find it.

**Comment by Didainius** [comment]
> Thank you. I will test it. Could you also provide your [go-vcloud-director](https://github.com/Didainius/go-vcloud-director) version? I couldn't find it.

Thanks. It is here - https://github.com/vmware/go-vcloud-director/pull/694 (this PR for Terraform also uses it)
