### ISSUE TITLE
vcd_network_routed_v2 does not have an attribute for Route Advertisement

### ISSUE THREAD

**Issue by selmalatawey** [vmware/terraform-provider-vcd#1105]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

CD 10.4+ allows the tenant to create a routed network with Route Advertisement enabled to allow the T1 gateway to advertise it to the north T0 gateway/provider gateway.
vcd_network_routed_v2 resource does not has have an argument for that. 

Add an argument (Boolean) in vcd_network_routed_v2 resource which allows the tenant to automate enabling/disabling Route Advertisement for that specific routed network.

vcd_network_routed_v2
New argument: 
route_advertised - Optional (VCD 10.4+) / Boolean if set to true, the network will be marked for advertisement by Org Edge to the north Provider GW and to the physical network. Default is false.

### References

![image](https://github.com/vmware/terraform-provider-vcd/assets/141845667/8b0901dd-4523-4592-901f-9f17ffb98697)

**Comment by nnikodimov** [comment]
@Didainius, do you happen to have an update on when this is planned to be available?  Enabling route advertisement for Public IP Space routed networks is quite a common use-case for VCD customers.

**Comment by lvirbalas** [comment]
@nnikodimov it's too early to answer that (yet).

**Comment by koznov** [comment]
That's a needed feature to enable option to advertise networks.

**Comment by Didainius** [comment]
Hello,
This functionality is implemented in #1203. Would anyone want to give it a try?

**Comment by selmalatawey** [comment]
@Didainius how can I pull that beta version including the fix?

**Comment by oliverwiegers** [comment]
@Didainius I tested it. It works :) Amazing work. Thank you

**Comment by Didainius** [comment]
> @Didainius The "Route Advertisement" settings have changed in the new version of VCD (v10.5.1). Now "Advertisement Strict", "Advertisement Flexible" and "All Networks Advertised" are offered. I would require these new settings to be set via terraform for our use-case.

@bogi0704 , just in time :) I will make a separate adjustment to add these, as this one is finalised now and is easier for team reviews.

**Comment by oliverwiegers** [comment]
Thanks for the patch :) 

Is there an ETA for the next release that will contain this patch?
