### ISSUE TITLE
Add import block support.

### ISSUE THREAD

**Issue by Dragnell87** [vmware/terraform-provider-vcd#1106]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can we add support for import block from terraform 1.5. Thanks

### New or Affected Resource(s)

* vcd_vapp_vm
* vcd_vapp_firewall_rules
* vcd_vapp_nat_rules
* vcd_vapp_static_routing
* vcd_vapp_org_network
* vcd_vapp_network
* vcd_vapp_access_control

**Comment by dataclouder** [comment]
Hi
Please note that the you can already use import blocks with terraform-provider-vcd 3.10.0.

For example, to import a `vcd_vapp_vm` named "TestVm", inside a vApp `TestVapp`, belonging to a VDC "myVdc", within organization "myOrg", you do the following:

```hcl
import {
  to = vcd_vapp_vm.myVm
  id = "myOrg.myVdc.TestVapp.TestVm"
}
```
Then you run
```shell
terraform plan `-generate-config-out=generated_vm.tf`
```
and finally, after inspecting the new file `generated_vm.tf`, you run `terraform plan`, and `terraform apply`. You will notice that the output for both `plan` and `apply` now includes an `import` action.

That said, we are improving our handling of import to help users generate the imported resources code more easily.
See PR #1104

**Comment by Dragnell87** [comment]
Hello, thank you for this. I could not find the documentation for this.

**Comment by dataclouder** [comment]
Some temporary documentation:

* https://github.com/dataclouder/terraform-provider-vcd/blob/import-compound-resources/website/docs/guides/importing_resources.html.markdown
* https://developer.hashicorp.com/terraform/language/import
