### ISSUE TITLE
Deleting resources  

### ISSUE THREAD

**Issue by timlukastlt** [vmware/terraform-provider-vcd#1125]
# Deleting resources Bug

Hello, i think that their is a bug in the provider. 
It appears when i want to delete an resource while i delete a rule which contains the resource.

## When will the bug occur
Just after the deletion of an existing ipset, which is also used in the distributed firewall. 
You need to remove the ipset and the rule in the distributed firewall at the same time, then the process will fail.

During execution of terraform apply the deletion of the ipset will fail because the rule is in the distributed firewall but this one should also be deleted. 

I think the order of execution in the provider is wrong. Normally it should first execute the deletion job in the distributed firewall so that the dependencies are resolved. The problem also occurs when the terraform name of these object is changed. 

## Terraform Version
```
Terraform v1.5.1
on linux_amd64
```

## Affected Resource(s)
- vcd_nsxt_distributed_firewall
- vcd_nsxt_ip_set
- vcd_nsxt_app_port_profile (probably but not tested)

## Terraform Configuration Files
```hcl
data "vcd_nsxt_app_port_profile" "HTTPS" {
  scope = "SYSTEM"
  name  = "HTTPS"
} 

resource "vcd_nsxt_ip_set" "source" {
    edge_gateway_id = var.edgeGateway_id

    name         = "tf_source_example"
    description  = "TF SOURCE EXAMPLE" 
    ip_addresses = ["10.0.0.0"]
}

resource "vcd_nsxt_ip_set" "destination" {
    edge_gateway_id = var.edgeGateway_id

    name         = "tf_destination_example"
    description  = "TF DESTINATION EXAMPLE" 
    ip_addresses = ["12.0.0.0"]
}

resource "vcd_nsxt_distributed_firewall" "t1" {
    vdc_group_id = var.vcd_vdc_group
    
    rule {
        name        = "tf_rule source > destination"
        description = "None"
        action      = "ALLOW"
        ip_protocol = "IPV4"
        logging      = "false"
        enabled     = "true"
        direction   = "IN_OUT"
        source_ids  = [vcd_nsxt_ip_set.source.id]
        destination_ids = [vcd_nsxt_ip_set.destination.id]
        app_port_profile_ids = [data.vcd_nsxt_app_port_profile.HTTPS.id]
        comment = "Rule is generated with Terraform"
    }
}
```

## Output
```
Error: [nsxt ip set resource delete] error deleting NSX-T IP Set: error deleting NSX-T Firewall Group: error waiting completion of task (...): task did not complete successfully:  [400:INTERNAL_SERVER_ERROR] - [ ... ] Bad Request: Error occurred in the backing network provider: The object path=[...] cannot be deleted as either it has children or it is being referenced by other objects path=[...], error code 500030
```

## Expected Behavior
IPSET should have been deleted and the rules updated

## Actual Behavior
The Job will fail:
```
Bad Request: Error occurred in the backing network provider: The object path=[...] cannot be deleted as either it has children or it is being referenced by other objects
```

## Steps to Reproduce
1. Delete the rule from the nsxt_distributed_firewall
2. Delete the ipsets (source, destination)
3. Run terraform (init, plan, apply)

**Comment by Didainius** [comment]
Hello @timlukastlt,
Thanks for the issue, but the problem is - we cannot control it as Terraform provider developers. At the moment I could just tell to do it in 2 steps - remove relevant entity from firewall configuration - perform `apply` and then remove the entity itself and again perform `apply agin.

**Comment by Didainius** [comment]
BTW - could you possibly try adding `depends_on` case to formalize the dependency tree. Although reference by `id` shouldn't require it, but it is interesting if it can help you.

**Comment by timlukastlt** [comment]
Hi,
thank you for your fast reply.
I added the depends_on for the "vcd_nsxt_distributed_firewall" containing the ipsets but even this don`t affect the deletion order and failed.

**Comment by timlukastlt** [comment]
Hey,
i found the solution. Just add this to every ressource.
```tf
lifecycle {
    create_before_destroy = true
} 
```
Then the order will be correct. The resources will first be created then the firewall will be updated and in the end it will delete the ressources.
