### ISSUE TITLE
How should I use the `ldap_mode = "SYSTEM"` and is it even possible?

### ISSUE THREAD

**Issue by cgrard** [vmware/terraform-provider-vcd#1134]
Hi there,

I'm not sure this is a bug or missing/unclear documentation yet but I'm facing an issue with the LDAP settings and the vcd_org_ldap resource creation: https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/org_ldap#ldap_mode

I have a VMware Virtual Cloud that has a system identity provider defined (which is an Active Directory server) , so in my terraform code, according to the documentation, I should be able to use the `SYSTEM` value for the `ldap_mode` argument but then how do I set the `base_distinguished_name` value in that case?

I tried with `ldap_mode = CUSTOM` and the corresponding `ldap_settings` and it works well but it defeat the purpose of being offered to use `SYSTEM`.

So I tried setting a minimal `custom_settings` with only the base DN but of course it does not work. I don't want to provide a complete `custom_settings` argument here since I want to reuse the system's identity provider and not define a new full blown custom LDAP config each time I create an organization. I just want to say "_please use ldap_mode = SYSTEM and use ou=Foo,dc=domain,dc=local base DN_"

So all in all, how am I supposed to use the `SYSTEM` `ldap_mode`? Any idea what I'm missing here?

**Comment by cgrard** [comment]
Any news?

**Comment by dataclouder** [comment]
Using `SYSTEM` means that the organization will use the LDAP service that was set at system level by the provider (system administrator). If no LDAP service was set by the provider, the organization won't be able to use any.

**Comment by cgrard** [comment]
That's not the problem, as I said there's a LDAP service set but I can't access the setting that would allow me to set the OU to use through the provider (which should be the `CustomUsersOu` parameter according to source code).
This setting exists but it is ignored in the source code : https://github.com/cgrard/terraform-provider-vcd/commit/a333f4db5dc391e26c6a9474290850403036dab7

**Comment by cgrard** [comment]
Thanks for the fix, I can compile, of course, but testing is much more difficult for me as of now because terraform is currently run in a container through a CI in a sealed environment that I don't have direct access to, but I'll try.

**Comment by lvirbalas** [comment]
We can't announce dates. However, at this point, we are striving for our traditional holiday release at the end or beginning of the new year.
