### ISSUE TITLE
Connect more external networks to nsxt edge gateway

### ISSUE THREAD

**Issue by carmine73** [vmware/terraform-provider-vcd#1138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

External networks that are NSX-T Segment backed (VLAN or overlay) can now be connected directly to Org VDC Edge Gateway and not routed through Tier-0 or VRF the Org VDC GW is connected to. This connection is done via the service interface (aka Centralize Service Port – CSP) on the service node of the Tier-1 GW that is backing the Org VDC Edge GW. The Org VDC Edge GW still needs a parent Tier-0/VRF (now called Provider Gateway) although it can be disconnected from it.

I see `external_network_id` can be a single id in resource `vcd_nsxt_edgegateway`, I guess there's no way to connect one more external netork to the edge gateway using this plugin.

### New or Affected Resource(s)

* vcd_nsxt_edgegateway

**Comment by carmine73** [comment]
I'll try, where I can find an example?

**Comment by Didainius** [comment]
You could look it up there (in that PR code) - https://github.com/Didainius/terraform-provider-vcd/blob/22764ee22fd70c7c9dd7160f7c79918a2282610b/website/docs/r/nsxt_edgegateway.html.markdown

The way to render it in Terraform registry mode would be to copy whole text and paste it into registry.terraform.io/tools/doc-preview

**Comment by carmine73** [comment]
Hi @Didainius,
thank you, test done, it works!
```
## edge gateway 1
resource "vcd_nsxt_edgegateway" "edge1" {
  org      = "orgname-test-1"
  owner_id = "urn:vcloud:vdc:xxxxxxxxx"

  name        = "orgname-test-edge-1"
  description = "created with terraform + provider registry.terraform.io/vmware/vcd v3.11.0"

  external_network_id = "urn:vcloud:network:yyyyyyyyy"

  # T0 subnet
  subnet {
    gateway       = "10.10.10.1"
    prefix_length = "24"
    primary_ip    = "10.10.10.191"
    allocated_ips {
      start_address = "10.10.10.191"
      end_address   = "10.10.10.191"
    }
  }

  # NSX-T Segment backed uplink with Primary IP
  external_network {
    external_network_id = "urn:vcloud:network:zzzzzzzzzz"
    gateway             = "10.97.97.1"
    prefix_length       = "24"
    allocated_ip_count  = 1
    primary_ip          = "10.97.97.101"
  }
}
```
