### ISSUE TITLE
vcd_network_routed_v2  doesn't have an interface_type NON_DISTRIBUTED (for NSX-T)

### ISSUE THREAD

**Issue by odraghi** [vmware/terraform-provider-vcd#1143]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow to create routed vdc network __non distributed__ 

That would imply two change:
1. Add a new value on network_routed_v2, Argument  interface_type = __non_distributed__ 
2. Add a new boolean argument on vcd_nsxt_edgegateway : __nonDistributedRoutingEnabled __  = false (Default) 

### New or Affected Resource(s)

- vcd_nsxt_edgegateway
- vcd_network_routed_v2

### References
na

**Comment by Didainius** [comment]
@odraghi ,
As for `vcd_network_routed_v2`, we already have a field `interface_type` that can accept `distributed` - is this what you are aiming to achieve?

**Comment by odraghi** [comment]
Yes but NSX-T supports only interface_type=internal
And that a shame because with "internal" in nsx-t,  that create distributed network.

**Comment by Didainius** [comment]
Ah, indeed. I will see if we can make it better.

**Comment by odraghi** [comment]
The goal is really to add a way to create non distributed network with nsx-t.

**Comment by jmunnik** [comment]
@odraghi do you know if is there any update on this open ticket ?

**Comment by GinoBadouri** [comment]
Yeah, we also have the requirement to disable distributed routing for some networks created by ```vcd_network_routed_v2```. How can we achieve this?

**Comment by Didainius** [comment]
Short note. Work in progress.

**Comment by Didainius** [comment]
@odraghi , @GinoBadouri , @jmunnik 
The PR is ready - https://github.com/vmware/terraform-provider-vcd/pull/1297
Would you be able to test and confirm it satisfies your needs?

**Comment by GinoBadouri** [comment]
Hi @Didainius 
Is there some artifact I can download?
I'm trying to compile from the PR branch but it seems to fail for me:
```
mastag@razerblade15:~/src/terraform-provider-vcd$ make build
==> Checking that code complies with gofmt requirements...
./vcd/datasource_vcd_org_saml_metadata.go:63:55: missing ',' in argument list
./vcd/datasource_vcd_rights_container_test.go:183:34: expected ']', found ','
./vcd/resource_vcd_provider_vdc.go:400:39: expected ']', found ','
./vcd/resource_vcd_provider_vdc.go:408:36: expected ']', found ','
./vcd/resource_vcd_provider_vdc.go:414:38: expected ']', found ','
./vcd/resource_vcd_provider_vdc.go:422:39: expected ']', found ','
./vcd/resource_vcd_provider_vdc.go:592:59: expected ']', found ','
./vcd/resource_vcd_provider_vdc.go:650:55: expected ']', found ','
./vcd/structure.go:112:12: expected '(', found '['
./vcd/structure.go:351:15: expected '(', found '['
go install -ldflags="-X 'github.com/vmware/terraform-provider-vcd/v3/vcd.BuildVersion=v3.13.0-11-ge3f863aa'"
build github.com/vmware/terraform-provider-vcd/v3: cannot load cmp: cannot find module providing package cmp
make: *** [GNUmakefile:12: build] Fout 1
```

**Comment by Didainius** [comment]
> Hi @Didainius Is there some artifact I can download? I'm trying to compile from the PR branch but it seems to fail for me:
> 
> ```
> mastag@razerblade15:~/src/terraform-provider-vcd$ make build
> ==> Checking that code complies with gofmt requirements...
> ./vcd/datasource_vcd_org_saml_metadata.go:63:55: missing ',' in argument list
> ./vcd/datasource_vcd_rights_container_test.go:183:34: expected ']', found ','
> ./vcd/resource_vcd_provider_vdc.go:400:39: expected ']', found ','
> ./vcd/resource_vcd_provider_vdc.go:408:36: expected ']', found ','
> ./vcd/resource_vcd_provider_vdc.go:414:38: expected ']', found ','
> ./vcd/resource_vcd_provider_vdc.go:422:39: expected ']', found ','
> ./vcd/resource_vcd_provider_vdc.go:592:59: expected ']', found ','
> ./vcd/resource_vcd_provider_vdc.go:650:55: expected ']', found ','
> ./vcd/structure.go:112:12: expected '(', found '['
> ./vcd/structure.go:351:15: expected '(', found '['
> go install -ldflags="-X 'github.com/vmware/terraform-provider-vcd/v3/vcd.BuildVersion=v3.13.0-11-ge3f863aa'"
> build github.com/vmware/terraform-provider-vcd/v3: cannot load cmp: cannot find module providing package cmp
> make: *** [GNUmakefile:12: build] Fout 1
> ```

Very odd. It shouldn't be this way. Which `Go version` (`go version` command) do you have?

**Comment by GinoBadouri** [comment]
go version go1.12.1 linux/amd64

**Comment by Didainius** [comment]
> go version go1.12.1 linux/amd64

Oh, so the problem is go version. This code needs at least `1.22.3` as per `go.mod` file

**Comment by GinoBadouri** [comment]
I've upgraded go and it works !
```
Terraform will perform the following actions:

  # module.one.vcd_network_routed_v2.backend[0] will be updated in-place
  ~ resource "vcd_network_routed_v2" "backend" {
        id                          = "urn:vcloud:network:904053e1-4a1f-4c3c-8eb2-bf0bd8687d79"
      ~ interface_type              = "INTERNAL" -> "non_distributed"
        name                        = "cibg1-backend"
        # (12 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

How long will it take for this to go live in a new release?

**Comment by Didainius** [comment]
> I've upgraded go and it works !
> 
> ```
> Terraform will perform the following actions:
> 
>   # module.one.vcd_network_routed_v2.backend[0] will be updated in-place
>   ~ resource "vcd_network_routed_v2" "backend" {
>         id                          = "urn:vcloud:network:904053e1-4a1f-4c3c-8eb2-bf0bd8687d79"
>       ~ interface_type              = "INTERNAL" -> "non_distributed"
>         name                        = "cibg1-backend"
>         # (12 unchanged attributes hidden)
> 
>         # (1 unchanged block hidden)
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> ```
> 
> How long will it take for this to go live in a new release?

Happy to hear that! We don't have a date for the new release yet to be fair.

**Comment by oliverwiegers** [comment]
@Didainius even though you don't have a release date planned yet how are the chances for a release in the next few weeks?

**Comment by Didainius** [comment]
> @Didainius even though you don't have a release date planned yet how are the chances for a release in the next few weeks?

I am afraid I have to tell there are pretty much 0 chances 

> 
> Works for us as well btw. Thank you :)

Great to hear (read) it!
