### ISSUE TITLE
new resource_type vcd_nsxt_alb_edgegateway_service_engine_group and vcd_nsxt_alb_service_engine_group in data source vcd_resource_list

### ISSUE THREAD

**Issue by carmine73** [vmware/terraform-provider-vcd#1145]
### Description

it would be nice to have `vcd_nsxt_alb_edgegateway_service_engine_group` and `vcd_nsxt_alb_service_engine_group` in data source  `vcd_resource_list` as `resource_type`
https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/resource_list#resource_type

### New or Affected Resource(s)

* data source `vcd_resource_list`

I had a look in the 3.11.0 code but I did't find them in `datasource_vcd_resource_list.go`

**Comment by Didainius** [comment]
Thanks @carmine73 for the issue,
You're right - they aren't yet because they must new OpenAPI filtering mode so this got on the side, but a good issue to track it

**Comment by carmine73** [comment]
hi @Didainius, still not on track?

**Comment by adambarreiro** [comment]
Hi @carmine73, thanks for your patience. This is being implemented in #1296, if you want to check it out and try it

**Comment by carmine73** [comment]
thanks, I cannot test it right now, I'll try in September.
for sure I'll use it when released

**Comment by carmine73** [comment]
do I miss something?
```
# service_engine_group list (supported since 3.14.0)
data "vcd_resource_list" "serv_eng_groups_list" {
  name          = "serv_eng_groups_list"
  resource_type = "vcd_nsxt_alb_edgegateway_service_engine_group"
  parent        = local.my-edge.name
  list_mode     = "name"
}
```
the edge owner is a vdc group
```
│ Error: could not retrieve Org '' and VDC '': empty VDC name provided
│
│   with data.vcd_resource_list.serv_eng_groups_list,
│   on fcp-datasrc-myorg.tf line 375, in data "vcd_resource_list" "serv_eng_groups_list":
│  375: data "vcd_resource_list" "serv_eng_groups_list" {
│
╵
```

**Comment by adambarreiro** [comment]
Hi @carmine73, I checked and unfortunately it doesn't work with VDC Groups. Will create a separate new issue for that.

**Comment by carmine73** [comment]
Sorry I wasn't able to test it before 3.14.0 been released :-(
