### ISSUE TITLE
Is there a way of accessing the Default Application Port Profiles in Terraform

### ISSUE THREAD

**Issue by pauljemmett** [vmware/terraform-provider-vcd#1151]
Hello,

### Terraform Version
Terraform v1.6.2
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.10.0

### Affected Resource(s)
data "vcd_nsxt_app_port_profile" "ssh" {
  name  = "SSH"
  org   = "System"
  scope = "PROVIDER"
}

I wanted to use this System created default app port profile to create a firewall rule rather than creating a new custom app port profile however I get this message

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: [ENF] entity not found NSX-T Application Port Profile not found
│
│   with data.vcd_nsxt_app_port_profile.ssh,
│   on vcd_nsxt_app_port_profile.tf line 92, in data "vcd_nsxt_app_port_profile" "ssh":
│   92: data "vcd_nsxt_app_port_profile" "ssh" {
 
 Probably not a bug but I'm failing to find any documentation that tells me how I retrieve the id's of system created app port profiles.
 
 Any assistance would be gratefully received.

**Comment by carmine73** [comment]
try this
```
data "vcd_nsxt_app_port_profile" "ssh" {
  name = "SSH"
  org = "System"
  scope = "SYSTEM"
}
```
I work as a org admin and it works this way
```
data "vcd_nsxt_app_port_profile" "my-app_port_profile" {
  context_id = local.my-vdc.id
  name       = local.app_port_profile.name
  scope      = "SYSTEM"
}
```

**Comment by pauljemmett** [comment]
Works perfectly thanks carmine73

**Comment by carmine73** [comment]
just to be sure, did you try this?
```
data "vcd_nsxt_app_port_profile" "ssh" {
  name  = "SSH"
  org   = "System"
  scope = "SYSTEM"
}
```
