### ISSUE TITLE
vmware/vcd 3.11 not available via Terraform Registry

### ISSUE THREAD

**Issue by des1redState** [vmware/terraform-provider-vcd#1163]
The `container-service-extension/v4.1` example requires `vmware/vcd` at `>= 3.11`. The latest available via the Terrafrom Registry is `3.10.0`.

https://github.com/vmware/terraform-provider-vcd/blob/main/examples/container-service-extension/v4.1/cluster/3.11-cluster-creation.tf#L20

https://registry.terraform.io/providers/vmware/vcd/latest/docs

**Comment by lvirbalas** [comment]
Correct. The referenced example is from unreleased code (cutting edge from main branch). This functionality together with the docs will be released with 3.11.0.

**Comment by lvirbalas** [comment]
@des1redState, we are striving for our traditional holiday release at the end or beginning of the new year.
