### ISSUE TITLE
Dependency between vcd_nsxt_edgegateway (Tier1) and an external_network segment

### ISSUE THREAD

**Issue by odraghi** [vmware/terraform-provider-vcd#1166]
Hello,

### Terraform Version
Terraform v1.6.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/vmware/nsxt v3.4.0
+ provider registry.terraform.io/vmware/vcd v3.11.0

### Affected Resource(s)

- vcd_nsxt_edgegateway
- vcd_external_network_v2

### Terraform Configuration Files

```hcl

variable "bpaas" {
  type = object({
    enabled               = bool
    prefix_length         = string
    ip_hsrp               = string
    ip_pool_start_address = string
    ip_pool_end_address   = string
  })
  default = {
    enabled               = false
    prefix_length         = "29"
    ip_hsrp               = "87.255.156.98"
    ip_pool_start_address = "87.255.156.102"
    ip_pool_end_address   = "87.255.156.102"
  }
}

resource "vcd_nsxt_edgegateway" "EDGE-TARGET" {
  org                 = var.tenant
  owner_id            = resource.vcd_org_vdc.VDC-TARGET.id
  name                = "${var.edge_gateway}-v2t-terraform-assistant"
  external_network_id = data.vcd_external_network_v2.PUBLIC-T0.id

  ## Conditional connexion to the External Network  Segment
  dynamic "external_network" {
    for_each = var.bpaas.enabled ? [1] : []

    content {
      external_network_id = vcd_external_network_v2.EXTERNAL-NETWORK-SEGMENT-BPAAS[0].id
      gateway             = var.bpaas.ip_hsrp
      prefix_length       = var.bpaas.prefix_length
      allocated_ip_count  = 1
      primary_ip          = var.bpaas.ip_pool_start_address
    }
  }

}

## Conditional External Network  Segment
resource "vcd_external_network_v2" "EXTERNAL-NETWORK-SEGMENT-BPAAS" {
  count = var.bpaas.enabled ? 1 : 0

  name        = local.bpaas_external_network_name
  description = "Interco BPAAS for ${local.sanitize_tenant_full_name}"

  nsxt_network {
    nsxt_manager_id   = data.vcd_nsxt_manager.main.id
    nsxt_segment_name = nsxt_policy_vlan_segment.VLAN_BPAAS[0].display_name
  }

  ip_scope {
    enabled       = false
    gateway       = var.bpaas.ip_hsrp
    prefix_length = var.bpaas.prefix_length

    # Address for cloud director Edge gateway OR security VM Appliance
    static_ip_pool {
      start_address = var.bpaas.ip_pool_start_address
      end_address   = var.bpaas.ip_pool_end_address
    }
  }
  depends_on = [
    nsxt_policy_vlan_segment.VLAN_BPAAS[0],
    time_sleep.WAIT_VCD_DISCOVER_NSXT_VLAN_BPAAS_SEGMENT[0]
  ]
}

```

### Expected Behavior
I would to have a bool that drive the connexion or not to an external network.
var.bpaas.enabled in my sample configuration is a bool.

When var.bpaas.enabled=true , Terrafrom sequence is:
1. create vcd_external_network_v2 type segment
2. connect the edgegateway to the external network segment

If I toggle var.bpaas.enabled to false,  terraform sequence would be:
1. disconnect the external network form the edge gateway
2. remove the external network segment

### Actual Behavior
When I change  var.bpaas.enabled to false, terraform try to remove the  vcd_external_network_v2 segment before removing it from the edge gateway..

Error: error deleting extNet: error in HTTP DELETE request: BAD_REQUEST - [ 07055a42-5cef-4d4d-a9d6-bb26c20ebe2c ] External network DMO 87.255.156.96_28 v1234_SPOTIFY_INT-BPAAS cannot be deleted, because it is in use by the following edge gateways: dmo0430ed-v2t-terraform-assistant(com.vmware.vcloud.entity.gateway:f59c883f-c349-4e8a-801b-6d59cf47b973).

**Comment by Didainius** [comment]
Thanks @odraghi for the issue,
The trick is that we don't have much control over Terraform dependency mechanism (this is outside of provider developer control). However, could a `lifecycle` parameter `create_before_destroy`help you? https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#create_before_destroy

Note. While they are configured in resources, we don't control them as well. Everything that comes from `lifecycle` is in direct control by Terraform itself, not providers.

Similar case where it helped - https://github.com/vmware/terraform-provider-vcd/issues/1125#issuecomment-1750203512

**Comment by odraghi** [comment]
Hello @Didainius 

lifecycle defenitly help in resource "vcd_external_network_v2".
That is harder to read /understand the config but it's working.

Another way of solving this could be put implement in vcd provider a dedicated resource like vcd_nsxt_edgegateway_external_network

**Comment by Didainius** [comment]
I am happy you have a way to make it working!

> Another way of solving this could be implementing in vcd provider a dedicated resource like vcd_nsxt_edgegateway_external_network

The trick is that it Edge Gateway API is not that flexible (it is one big structure) and we tend to avoid splitting modification of the same API endpoint and body in separate resources as this might introduce some "out of sync" scenarios

**Comment by Didainius** [comment]
Given my above quote we most probably will not introduce a new separate resource unless something changes. Closing for now but feel free to reopen/comment if anything

**Comment by odraghi** [comment]
Understood.
Thanks
