### ISSUE TITLE
NSX-T manager required to create a Provider VDC

### ISSUE THREAD

**Issue by JonathanWrightSE** [vmware/terraform-provider-vcd#1186]
### Terraform Version
Terraform v1.6.6
on windows_amd64

### Affected Resource(s)
vcd_provider_vdc

When creating a provider vdc in terraform, it is required to supply a reference to the NSX-T manager registered in vCloud Director. NSX-T is not a requirement of VCD and provider vdcs can be created in the UI with no network pool, so the NSX-T manager parameter is not required. Please removed this parameter's "required" status.

**Comment by JonathanWrightSE** [comment]
#### Addendum
The "network_pool-ids" parameter is also required in the vcd_provider_vdc resource, although it is not required in the UI.

Both these issues prevent me from using terraform to deploy VCD tenants for my customers that use portgroup-backed networking.

**Comment by dataclouder** [comment]
Hi,
Thanks for reporting this issue.
What you have observed is true. However, it was a deliberate choice on our side. When we implemented the provider VDC resource, we deliberately chose to disregard NSX-V dependencies, because we know that they will be discontinued soon.
Thus, our `vcd_provider_vdc` resource can only be created within a NSX-T environment.
The corresponding data source is able to reference existing provider VDCs, even the NSXV-backed ones.

**Comment by JonathanWrightSE** [comment]
Thank you for your super-fast response, dataclouder.

I understand you deciding to drop NSX-V support as it is depreciated and replaced with NSX-T, but what about service providers that use port-group backed networking? I do have customers who use this configuration. I seems that I'll need them to install an NSX manager just so they can create a PVDC, then the Organization VDC can use the port-group backed network pool.

Kind Regards

**Comment by dataclouder** [comment]
The current implementation only supports network pools backed by a NSX-T manager. Also that was a specific choice.
Could you show me (with screen shots) how you create a PVDC in the UI using port-group network pools?
If it is feasible, and it doesn't require NSX-V, we may consider it for a future enhancement.

**Comment by JonathanWrightSE** [comment]
I cannot create the pvdc using a port-group backed network pool.

To use the port-group backed NP in the UI, I create the PVDC with no network pool (an option in the UI) then assign the port-group backed NP to the organization VDC.

In Terraform I think I must create the PVDC with a NSX manager ID & a geneve backed NP, but then create the organization VDC with my port-group backed NP. I'm unsure about how well that will work right now...

**Comment by dataclouder** [comment]
I see. So, what you would need is the ability to create a PVDC without any network pools.
Is that correct?

**Comment by JonathanWrightSE** [comment]
Yes, correct.

**Comment by dataclouder** [comment]
Implemented in PR #1220
