### ISSUE TITLE
assign interfaces in vcd_ip_space_uplink

### ISSUE THREAD

**Issue by bogi0704** [vmware/terraform-provider-vcd#1207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a provider gateway using IP Spaces one is able to configure specific T0 Interfaces for that uplink via the VCD UI.

### New or Affected Resource(s)

* vcd_ip_space_uplink

### Terraform Configuration (if it applies)

Proposal of a new argument

```hcl
associated_interfaces = [nsxt_policy_tier0_gateway_interface.internet01.id, nsxt_policy_tier0_gateway_interface.internet02.id] // Optional (VCD 10.5.1+) / If one or more interfaces are specified, then NAT, Firewall and routing settings using this IP-Space will only apply to those interfaces instead of all connected interfaces. Default: []
```

### References

![grafik](https://github.com/vmware/terraform-provider-vcd/assets/39438845/8c70137c-562e-4a6a-9a6b-0ff7f56ff248)

**Comment by Didainius** [comment]
@bogi0704 , this is now implemented in https://github.com/vmware/terraform-provider-vcd/pull/1311
Would you possibly be able to validate the feature works for you?

**Comment by bogi0704** [comment]
@Didainius yes, I am planning to implement this in our stack. It may take some time though...

**Comment by Didainius** [comment]
> @Didainius yes, I am planning to implement this in our stack. It may take some time though...

Got it, thanks. So we have working tests as usual and it all should be good, but whenever possible, your feedback on is very valuable. If you get a chance to try - do post if it worked for you.
