### ISSUE TITLE
Incorrect resource imported when a shared AVI SEG is assigned to multiple NSX-T Edge GWs

### ISSUE THREAD

**Issue by jaymzmac** [vmware/terraform-provider-vcd#1245]
In our environment we have a AVI Service Engine Group that is configured in 'Shared' mode.

The [code](https://github.com/vmware/terraform-provider-vcd/blob/1f61f1eb157271cbe9cdd98698503f45148b22c7/vcd/resource_vcd_nsxt_alb_edgegateway_service_engine_group.go#L190) which is used to import an existing [Edge GW Service Engine Group Assignment](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/nsxt_alb_edgegateway_service_engine_group#importing) does not seem to filter based on the Edge GW ID.

This means that when attempting to import a vcd_nsxt_alb_edgegateway_service_engine_group resource, it is possible that a SEG assignment from a different Edge GW to the one specified in the import command may be imported.

### Terraform Version
Terraform v1.5.3
vmware/vcd v3.9.0

### Affected Resource(s)
- vcd_nsxt_alb_edgegateway_service_engine_group

### Terraform Configuration Files

```hcl

data "vcd_nsxt_alb_service_engine_group" "seg-vdc-shared" {
  name = "seg-vdc-shared"
}

data "vcd_nsxt_edgegateway" "edge1" {
  org = "org1"
  vdc = "vdc1"
  name = "edge1"
}

resource "vcd_nsxt_alb_edgegateway_service_engine_group" "org1-edge1-seg" {
  edge_gateway_id = data.vcd_nsxt_edgegateway.edge1.id
  service_engine_group_id = data.vcd_nsxt_alb_service_engine_group.seg-vdc-shared.id
}

```

### Steps to Reproduce
1. `terraform import vcd_nsxt_alb_edgegateway_service_engine_group.org1-edge1-seg org1.vdc1.edge1.seg-vdc-shared`

### Expected Behavior

I would expect `urn:vcloud:serviceEngineGroupAssignment:a66cc110-2409-4761-ab79-5354da79dfb7` to be imported as per the GET cloudapi/1.0.0/loadBalancer/serviceEngineGroups/assignments response:

```json
{
            "id": "urn:vcloud:serviceEngineGroupAssignment:a66cc110-2409-4761-ab79-5354da79dfb7",
            "serviceEngineGroupRef": {
                "name": "seg-vdc-shared"
            },
            "gatewayRef": {
                "name": "edge1",
            }
            "gatewayOwnerRef": {
                "name": "vdc1",
            },
            "gatewayOrgRef": {
                "name": "org1",
            },
            ...
},
{
            "id": "urn:vcloud:serviceEngineGroupAssignment:e9d87147-9944-45b2-b200-a071971ed4f6",
            "serviceEngineGroupRef": {
                "name": "seg-vdc-shared",
            },
            "gatewayRef": {
                "name": "edge2",
            },
            "gatewayOwnerRef": {
                "name": "vdc2",
            },
            "gatewayOrgRef": {
                "name": "org2",
            },
            ...
}
```

### Actual Behavior

`urn:vcloud:serviceEngineGroupAssignment:e9d87147-9944-45b2-b200-a071971ed4f6` is imported, which is assigned to a different Edge GW, belonging to a different Org.

### User Access rights 
System Administrator account used.

**Comment by Didainius** [comment]
@jaymzmac , thanks for the issue.
I think I have a fix for it in #1246  - would you like to validate it?
