### ISSUE TITLE
Plugin terraform-provider-vcd crushed during resource "vcd_network_routed" implementation 

### ISSUE THREAD

**Issue by AlexDubel** [vmware/terraform-provider-vcd#1250]
Hi, I found a bug trying to implement dhcp_pool in new nsx_t networks.
The idea was to copy the existing networks on NSX-V VDC to networks on NSX-T VDC (which was successful).  
After that, I want to add dhcp_pool to NSX-T networks, but only if the corresponding NSX-V has it (in my environment, in NSX-V VDC, I have three networks, but only one has dhcp_pool ).  
terraform-provider-vcd_v3.12.0.exe plugin saved the plan to: f1.tfplan but crushed during apply. 

### Terraform Version
Terraform v1.7.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/hcp v0.86.0
+ provider registry.terraform.io/hashicorp/vault v4.2.0
+ provider registry.terraform.io/vmware/nsxt v3.5.0
+ provider registry.terraform.io/vmware/vcd v3.12.0

### Affected Resource(s)
vcd_network_routed

### Debug Output

Log files can be found at
```
https://gist.github.com/AlexDubel/dc8ba286f8b55dc9dee1e08a506962d0 
```
### Expected Behavior
terraform plan is applied. 

### Actual Behavior
...
Plan: 3 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Saved the plan to: f1.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "f1.tfplan"
Releasing state lock. This may take a few moments...
vcd_network_routed.routed_net_dhcp_pool[2]: Creating...
vcd_network_routed.routed_net_dhcp_pool[1]: Creating...
vcd_network_routed.routed_net_dhcp_pool[0]: Creating...
╷
│ Error: Plugin did not respond
│
│   with vcd_network_routed.routed_net_dhcp_pool[2],
│   on networks.tf line 102, in resource "vcd_network_routed" "routed_net_dhcp_pool":
│  102: resource "vcd_network_routed" "routed_net_dhcp_pool" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with vcd_network_routed.routed_net_dhcp_pool[1],
│   on networks.tf line 102, in resource "vcd_network_routed" "routed_net_dhcp_pool":
│  102: resource "vcd_network_routed" "routed_net_dhcp_pool" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Plugin did not respond
│
│   with vcd_network_routed.routed_net_dhcp_pool[0],
│   on networks.tf line 102, in resource "vcd_network_routed" "routed_net_dhcp_pool":
│  102: resource "vcd_network_routed" "routed_net_dhcp_pool" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-vcd_v3.12.0.exe plugin:

panic: edge gateway 'urn:vcloud:gateway:a0b7e72e-9fc1-45ac-a008-de34b4cf0cef' not found: unable to find edge gateway: [ENF] entity not found

goroutine 112 [running]:
github.com/vmware/terraform-provider-vcd/v3/vcd.(*VCDClient).lockParentEdgeGtw(0xc000293a40, 0xc00048cd00)
        github.com/vmware/terraform-provider-vcd/v3/vcd/config.go:367 +0x1d9
github.com/vmware/terraform-provider-vcd/v3/vcd.resourceVcdNetworkRoutedCreate({0x21cc4e8, 0xc00025a8c0}, 0xc00048cd00, {0x1fe0be0, 0xc000293a40})
        github.com/vmware/terraform-provider-vcd/v3/vcd/resource_vcd_network_routed.go:197 +0xa5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00018e7e0, {0x21cc440, 0xc000664420}, 0xc00048cd00, {0x1fe0be0, 0x
c000293a40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:778 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00018e7e0, {0x21cc440, 0xc000664420}, 0xc0002c1e10, 0xc00048c980, {
0x1fe0be0, 0xc000293a40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000241d10, {0x21cc440?, 0xc00050bec0?}, 0xc
0008884b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xd5c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002748c0, {0x21cc440?, 0xc00050b500?}, 0xc00025a0e0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/tf5server/server.go:859 +0x56f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1fa2640, 0xc0002748c0}, {0x21cc440,
0xc00050b500}, 0xc00048c000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:503 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00026e000, {0x21cc440, 0xc00050b470}, {0x21d22e0, 0xc00016e820}, 0xc0001a8240, 0xc00023fb30, 0x
28dfbd8, 0x0)
        google.golang.org/grpc@v1.60.0/server.go:1372 +0xdd1
google.golang.org/grpc.(*Server).handleStream(0xc00026e000, {0x21d22e0, 0xc00016e820}, 0xc0001a8240)
        google.golang.org/grpc@v1.60.0/server.go:1783 +0xfb8
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
        google.golang.org/grpc@v1.60.0/server.go:1027 +0x106

Error: The terraform-provider-vcd_v3.12.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce
1. `terraform apply`

**Comment by Didainius** [comment]
Hello @AlexDubel ,
Could you try using [`vcd_network_routed_v2`](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/network_routed_v2) resource, which should be capable of handling NSX-T networks. As for DHCP management, the VCD API changed for NSX-T and there is a separate resource [`vcd_nsxt_network_dhcp`](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/nsxt_network_dhcp )  for handling DHCP pools

**Comment by Didainius** [comment]
Closing the issue - feel free to add comments if needed
