### ISSUE TITLE
Upgrading a TKG Cluster with a declared ssh key will cause cluster to be destroyed and re created

### ISSUE THREAD

**Issue by returntrip** [vmware/terraform-provider-vcd#1252]
@adambarreiro 

### Expected Behavior
Cluster is upgraded to v1.26.11 without being destroyed and re created (therefore loosing workloads)

### Actual Behavior
The cluster is being destroyed and recreated

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1) Create cluster on v1.25.7 with ssh key declared
2) Attempt upgrade to v1.26.11

### Factoids

Note the `forces replacement` at the ssh key line
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # vcd_cse_kubernetes_cluster.my_cluster must be replaced
-/+ resource "vcd_cse_kubernetes_cluster" "my_cluster" {
      ~ capvcd_version                = "v1.3.0" -> (known after apply)
      ~ cluster_resource_set_bindings = [
          - "cloud-director-crs-cm",
          - "csi-controller-crs-cm",
          - "csi-driver-crs-cm",
          - "csi-node-crs-cm",
        ] -> (known after apply)
      ~ cpi_version                   = "1.6.0" -> (known after apply)
      ~ csi_version                   = "1.6.0" -> (known after apply)
      ~ id                            = "urn:vcloud:entity:vmware:capvcdCluster:764106c1-cb29-4fce-ab33-9908bfc69f18" -> (known after apply)
      ~ kubeconfig                    = <<-EOT
            apiVersion: v1
            clusters:
            - cluster:
                certificate-authority-data: 
                server: https://10.124.0.3:6443
              name: testtf6
            contexts:
            - context:
                cluster: testtf6
                user: testtf6-admin
              name: testtf6-admin@testtf6
            current-context: testtf6-admin@testtf6
            kind: Config
            preferences: {}
            users:
            - name: testtf6-admin
              user:
                client-certificate-data: 
                client-key-data: 
        EOT -> (known after apply)
      ~ kubernetes_template_id        = "urn:vcloud:vapptemplate:c6ac16a7-3253-4d5a-a0e0-3d45b1639006" -> "urn:vcloud:vapptemplate:b45b4060-72e8-4e69-a460-34202eae139b"
      ~ kubernetes_version            = "v1.25.7+vmware.2" -> (known after apply)
        name                          = "testtf6"
      + ssh_public_key                = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKIw27J3znCLPBFEcf54ANGepC6XrsJ3A8fw8OOyCZK3 returntrip@labbejmp01" # forces replacement
      ~ state                         = "provisioned" -> (known after apply)
      ~ supported_upgrades            = [
          - "Ubuntu 20.04 and Kubernetes v1.25.13+vmware.1",
          - "Ubuntu 20.04 and Kubernetes v1.26.11+vmware.1",
          - "Ubuntu 20.04 and Kubernetes v1.26.8+vmware.1",
        ] -> (known after apply)
      ~ tkg_product_version           = "v2.2.0" -> (known after apply)
        # (11 unchanged attributes hidden)

      ~ control_plane {
          ~ ip                 = "10.124.0.3" -> (known after apply)
            # (4 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

P.S.: Adding `ssh_public_key` after having created a cluster using TF will trigger destroy and re create
P.P.s: Used branch from here https://github.com/vmware/terraform-provider-vcd/issues/1248#issuecomment-2045163836

**Comment by adambarreiro** [comment]
Hi @returntrip,

Thanks for finding this one, somehow it slipped during the tests. I will fix it with #1248.

The issue is that the SSH Public Key is not retrieved correctly from the cluster YAML due to a bug during its unmarshal, hence not saved in the state. Terraform then thinks that you're setting it up, asking for a forcefully replacement (as SSH Keys cannot be modified after creation).

**Comment by adambarreiro** [comment]
Merged #1248, will release a patch soon.

Thanks for reporting!

**Comment by returntrip** [comment]
Thanks @adambarreiro! Should I use main branch to continue my testing for CSE LCM or is ther a specific branch I can use for upgrade path/ssh fixes?

**Comment by adambarreiro** [comment]
Sure, main branch should have all the fixes now

**Comment by returntrip** [comment]
Figured it out, version 3.12.1 :)

**Comment by returntrip** [comment]
> as SSH Keys cannot be modified after creation

I am a bit worried about this staement. What if I need to add/modify/delete a key? The cluster would be destroyed and recreated?

**Comment by adambarreiro** [comment]
> > as SSH Keys cannot be modified after creation
> 
> I am a bit worried about this staement. What if I need to add/modify/delete a key? The cluster would be destroyed and recreated?

Yes, that would be the case. In general the resource does what the CSE UI allows to do, and so far it doesn't allow to change the SSH Key.

**Comment by returntrip** [comment]
Ah that is a shame :(. The hope would be that the GUI should mirror the XaC. Sad to see things done backwards.

**Comment by sahithi** [comment]
This is Sahithi from CSE team.

There are two different things. I am intentionally leaving the Terraform component out of the workflow in my description below as I don't know the full details of its inner workings.

1. Cluster Creation: The user wants to create a cluster with 3 control plane, 10 worker count with ssh key.
  * POST RDE API with capiYaml embedded in it. capiYaml is where the ssh key is inserted. Cluster gets created with say, 3 controlplane and 10 worker count

2. Cluster Updates: The user now wants to modify the ssh key.
  * PUT RDE API with the modified capiYaml with new ssh key. The cluster undergoes a node rollout (recreation of all nodes with no downtime for any applications). Currently, this use case is not supported via CSE UI, but it can be done via UI. Not sure of the terraform.
  
3. Cluster upgrades: User wants to change the K8s version in the capiYaml
  * PUT RDE API with the modified capiYaml with new K8s version. The cluster undergoes a node rollout (recreation of all nodes with no downtime for any applications). Currently, this use case is supported via CSE ui and via API.

**Comment by returntrip** [comment]
> 1. Cluster Creation: The user wants to create a cluster with 3 control plane, 10 worker count with ssh key.

Hi Sahithi,

This works fine except that the worker nodes are not reprovisioned as change to "KubeadmConfigTemplate" do not seem to trigger rollout. I had to manually trigger MD rollout

Some old slack ref where another user has same experience in CAPI land: https://kubernetes.slack.com/archives/C8TSNPY4T/p1654082739761259
