### ISSUE TITLE
vcd_api_token - Unable to register an API token:

### ISSUE THREAD

**Issue by cbotha** [vmware/terraform-provider-vcd#1257]
Hello,
### Terraform Version
Terraform v1.7.3
vmware/vcd v3.12.1

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_cse_kubernetes_cluster
- vcd_api_token

### Terraform Configuration Files

# Configure the VMware Cloud Director Provider
provider "vcd" {
  user                 = "none"
  password             = "none"
  auth_type            = "api_token"
  api_token            = "xxxxxxxxxxxxxxxxx"
  org                  = "ORG"
  vdc                  = "VDC"
  url                  = "https://our-portal/api"
  max_retry_timeout    = 600
}

terraform {
  required_providers {
    vcd = {
      version = "~> 3.12"
      source  = "vmware/vcd"
    }
  }
}

resource "vcd_cse_kubernetes_cluster" "tkgtest" {
    name = "tkgtest4"
    cse_version = "4.2.1"
    vdc_id = data.vcd_org_vdc.vdc.id
    network_id = data.vcd_network_routed_v2.routed.id
    kubernetes_template_id = data.vcd_catalog_vapp_template.tkg_ova.id
    api_token_file         = vcd_api_token.me.name
    
    control_plane {
        machine_count      = 1
        disk_size_gi       = 20
        sizing_policy_id   = data.vcd_vm_sizing_policy.tkgmedium.id
        storage_profile_id = data.vcd_storage_profile.pol.id
    }

    worker_pool {
    name               = "node-pool-1"
    machine_count      = 1
    disk_size_gi       = 20
    sizing_policy_id   = data.vcd_vm_sizing_policy.tkgmedium.id
    storage_profile_id = data.vcd_storage_profile.pol.id
    }

}

resource "vcd_api_token" "me" {
  name             = "me"
  file_name        = "/Users/me/Documents/tanzu/me.json"
  allow_token_file = true
}

### Debug Output
Error: [API token create] error creating API token: failed to register API token: error registering token: error in HTTP POST request: access_denied - Missing the following rights to perform this operation: API Tokens: Manage

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
A new API token should be created

### Actual Behavior
Error: [API token create] error creating API token: failed to register API token: error registering token: error in HTTP POST request: access_denied - Missing the following rights to perform this operation: API Tokens: Manage

The role has 
 ACCESS CONTROL  -> User - > Manage user's own API token.  Enabled as per docs.

also tried enabling and publishing with this permission added as well:
 ACCESS CONTROL  -> SDDC - > Manage user's own API token

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Didainius** [comment]
Hello @cbotha ,
So this issue looks to be unrelated to kubernetes, but more of API token provisioning problem. 
Are you trying to use existing API token to create a new one using `vcd_api_token`? 

If so - this is prohibited by VCD itself: https://blogs.vmware.com/cloudprovider/2022/03/cloud-director-api-token.html

> When accessing VMware Cloud Director by using an API access token, applications have only view rights for the following resources.

> User
> Group
> Roles
> Global roles
> Rights bundles

**Comment by cbotha** [comment]
Hi @Didainius 

Thanks for the prompt reply. Indeed you're right.
Based on some more reading it seems like the correct way to go about it is to make use of a VCD service account instead.

**Comment by Didainius** [comment]
> Hi @Didainius
> 
> Thanks for the prompt reply. Indeed you're right. Based on some more reading it seems like the correct way to go about it is to make use of a VCD service account instead.

Could be (I am not exactly sure if service accounts have any restrictions or not). FYI - this provider supports service accounts:
* https://registry.terraform.io/providers/vmware/vcd/latest/docs#connecting-with-a-service-account-api-token (auth)
* https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/service_account (creation)

**Comment by cbotha** [comment]
Thanks, will investigate this further. Closing the ticket in the meantime.

**Comment by JanneRantala** [comment]
Hi @cbotha! Did you found out how API tokens should be used? I'm facing the same error with both API token and service account API token.
