### ISSUE TITLE
(Datasource) NSX-T Edge gateway Plugin chrashes when reading Egde gateway with allocated IPv6 addresses. V2

### ISSUE THREAD

**Issue by Nagte502** [vmware/terraform-provider-vcd#1270]
Hi, We are unfortunately still experiencing an issue with the datasource 'vcd_edgegateway' when the edge has IPv6 addresses allocated.
When using this datasource on an edge gateway that has ipv6 IP allocations, we get the following error:

![image](https://github.com/vmware/terraform-provider-vcd/assets/129171276/7d7d6832-4ebe-4f6f-9d13-8f4a62a09770)

This is a different error now that we have updated to 3.12.1, but it still doesn't work... 
(https://github.com/vmware/terraform-provider-vcd/issues/1242)

When removing the IPv6 allocation from the edge, the plugin works fine again, as before.

Terraform vcd provider version v3.12.1
Terraform version v1.8.3

**Comment by Didainius** [comment]
@Nagte502 ,
Would you be able to validate the fix that I have done in #1275?

**Comment by Nagte502** [comment]
Unfortunately I haven't been able to do so yet. I hope to get to it early next week

**Comment by Nagte502** [comment]
I've quickly discussed with the team this morning about testing the branch. Since the tenant in question is a customer tenant, we can't quickly make changes to it. As a work around, IPv6 has been disabled for the customer. Testing the branch would only work with IPv6 enabled. However, I won't be able to do so without customer impact. Unfortunately I won't be able to test this branch because of this.

**Comment by Didainius** [comment]
Understood. Would you be able to tell the prefix of IPv6 subnet the customer had? I am suspecting this had to be something big e.g. /64 as it is the case when API starts to miss a few fields and we had this error

**Comment by Nagte502** [comment]
Yes, it's the same /64 network
