### ISSUE TITLE
CSE 4.2.2/4.2.3 Compatiblity

### ISSUE THREAD

**Issue by returntrip** [vmware/terraform-provider-vcd#1319]
Hi Team, are we safe to assume TFV 3.13.0 is compatible with CSE 4.2.2 as, basically, there are no funcionality changes between 4.2.1 and 4.2.2?

**Comment by returntrip** [comment]
I tested this in our lab and I could create a cluster using CSE 4.2.2 and TFV 3.13.0. Still would be good to get your feedback and also update the documetation/provider to formally support CSE 4.2.2. Thanks

**Comment by lvirbalas** [comment]
Hello, 3.13.0 doesn't support CSE 4.2.2.

**Comment by returntrip** [comment]
CSE 4.2.3 is GA. Would be good to get TFV compatible with this: https://docs.vmware.com/en/VMware-Cloud-Director-Container-Service-Extension/4.2.3/rn/vmware-cloud-director-container-service-extension-423-release-notes/index.html

**Comment by jliokaitis** [comment]
Hello team, vcd provider 3.14.0 supports cloud director 10.6, but does not support CSE 4.2.2, though according to vmware product interoperability matrix vcd 10.6 and cse 4.2.2 (or above) is the way to go. It would be nice to have support for CSE 4.2.2

**Comment by returntrip** [comment]
Any updates on this? Whilst one could use CSE 4.2.2 TKG 2.5.0 templates with the TF provider, CSE 4.2.3 TKG2.5.2 templates are not compatible with the provider at all. Customers cannot use TF for CSE TKG cluster provisioning.....

**Comment by adambarreiro** [comment]
Hello, thanks for your patience.

I'm preparing a PR to add 4.2.2 and 4.2.3 support here: #1357

Having early feedback would be great before doing a release.

Thanks in advance.

**Comment by returntrip** [comment]
@adambarreiro hi, many thanks for working on this. I am currently testing creation of k8s clusters. I managed to create clusters for 4.2.1, 4.2.2 and 4.2.3.

I have a question tho, if I am using CSE 4.2.3 in VCD and set `cse_version` to `4.2.1` should I see the components (CAPVCD, CSI, CPI, RDE) set to the compatible versions for CSE 4.2.1 (example CAPVCD 1.3.0)?

At the moment all clusters I create are generated  by TF with CSE 4.2.3 (RDE, CAPVCD, CSI, CPI) components as those are configured for at provider level.

I am wondering, why would I want to state the `cse_version` at all vs letting the TF provider use whatever CSE version is installed in VCD?

**Comment by returntrip** [comment]
I have created and destroyed many CSE 4.2.3 clusters, upgraded from CSE 4.2.1 TKG 2.5.0 to CSE 4.2.3 TKG 2.5.2 images, created a cluster with autoscaler enabled and it all seems to work. Thanks again for working on this.

**Comment by adambarreiro** [comment]
Hello, the v3.14.1 release is ready and supports CSE 4.2.2 and 4.2.3:
https://github.com/vmware/terraform-provider-vcd/releases/tag/v3.14.1
