### ISSUE TITLE
Implement test for guest customization initscript

### ISSUE THREAD

**Issue by lvirbalas** [vmware/terraform-provider-vcd#139]
We need a test to make sure initscript works and there are no regressions.

### Affected Resource(s)

Both vApp and VM needs this:

- vcd/resource_vcd_vapp.go
- vcd/resource_vcd_vapp_vm.go

### References

#119
#88
#62

**Comment by lvirbalas** [comment]
Idea: create an init script which opens up a TCP port and then connect to it from the test.

**Comment by pasikarkkainen** [comment]
@lvirbalas that sounds like a good idea to me!

**Comment by lvirbalas** [comment]
@pasikarkkainen first of all thank you for your fix above. I was trying it out and it was fun to see how initscript works! Now we just need a test to avoid regressions.

**Comment by Didainius** [comment]
We've got such test in #223 and a few more tests.
