### ISSUE TITLE
RFE: Allow configuring Distributed Firewall (Micro Segmentation) for NSX-T

### ISSUE THREAD

**Issue by pasikarkkainen** [vmware/terraform-provider-vcd#144]
Currently terraform-provider-vcd does not allow configuring vCloud Director Distributed Firewall feature (as provided by NSX for vNic-level filtering between VMs).

Distributed Firewall is configured/enabled per-VDC in vCloud Director, and allows filtering/firewalling traffic between VMs regardless of the network topology, so east-west filtering and Micro Segmentation is possible even for VMs which are in the same network/subnet. This is an important security feature.

For more information about NSX Distributed Firewall: https://fojta.wordpress.com/2017/03/01/vcloud-director-8-20-distributed-firewall/

It'd be great to be able to configure DFW with Terraform.

**Comment by lvirbalas** [comment]
@pasikarkkainen would you provide a stub `.tf` specification (resource examples) of how you would see this implemented?

**Comment by pasikarkkainen** [comment]
@lvirbalas : Ok, I'll try to get some kind of .tf specification written.

**Comment by nicslatts** [comment]
@lvirbalas I'd like to upvote this. When we come to setting "reasonable defaults" for a low-touch app deployment, we should include default FW rules. Initially these FW rules can be applied to an ESG, but we will need to account for the "flat network" architecture that the DFW allows, especially as we look to automate deployment of multi-tier apps. These multi-tier apps may reside on the same subnet, segregated by DFW rules.

**Comment by yaron** [comment]
This is the .tf example for the provider we're using internally:
`resource "vcd_distributed_firewall_rule" "incoming" {
  name   = "in http"
  action = "allow"

  source {
    type  = "securitygroup" // Also supports vm and ip
    value = "${var.securitygroup}"
  }

  destination {
    type  = "securitygroup" // Also supports vm and ip
    value = "${var.securitygroup}"
  }

  // 
  service {
    group_name = "http" // Service application groups
  }

  service {
    // source_port can also be set.
    destination_port = "80"
    protocol         = "tcp" // icmp needs no port
  }
}`

**Comment by nilic** [comment]
Would just like to upvote this. As a start, it would be nice to have a `distributed_firewall` argument for the `vcd_org_vdc` resource which would allow for enabling the DFW feature on an Org vDC.

**Comment by Didainius** [comment]
@nilic, there are a lot of parts missing distributed routing puzzle , but I think we have capability to enable distributed_routing at [edge gateway level](https://www.terraform.io/docs/providers/vcd/r/edgegateway.html#distributed_routing).

**Comment by nilic** [comment]
@Didainius Yes, distributed routing is there, but I don't think that distributed firewall is in any way related to distributed routing and even Edge GW. It's enabled on an Org vDC level through API:

![image](https://user-images.githubusercontent.com/6827325/69611136-72928880-102d-11ea-9275-773ff932c0e7.png)

or through the HTML5 portal Networking - Security - Configure Services (needs to be done by the System Administrator):

![image](https://user-images.githubusercontent.com/6827325/69611609-7541ad80-102e-11ea-9bf7-c5073ba01d94.png)

As a service provider, having an option to enable DFW through Terraform is interesting to us because it would allow us to enable it for selected customers at the time of customer provisioning (when we create their Organization, Organization vDC etc). 

So I guess there are two requests here - one to be able to enable DFW (which should maybe have a separate issue), and the original one, to be able to configure DFW rules.

**Comment by Didainius** [comment]
@nilic, thanks! That is a good explanation and a very good info when someone starts working on it

**Comment by steadyjaw** [comment]
We would like to use this as well.
Any update on this RFE?

**Comment by lvirbalas** [comment]
As it stands right now, the plan is to add it for NSX-**T** once we cover the fundamentals.

**Comment by steadyjaw** [comment]
awesome, thanks for the update.

**Comment by badsector3** [comment]
I need to use the DFW and would prefer to configure it via Terraform.  
Any update?

**Comment by Didainius** [comment]
> I need to use the DFW and would prefer to configure it via Terraform.  
> 
> Any update?

@badsector3 ,
Are you after nsx-v or nsx-t?

**Comment by pasikarkkainen** [comment]
I'd love to see DFW support also for NSX-V, as most of the environments I have access to are still based on NSX-V..

**Comment by badsector3** [comment]
@Didainius I sent email to cloud provider to confirm which one they can deploy for us on vCloud.
Which one has better Terraform support or which  one would you suggest deploying (if we can request that from the cloud provider)?
I know that nsx-t is newer, but  I would prefer creating the DFM rules via code than manually.

**Comment by Didainius** [comment]
@badsector3 ,
Eventually NSX-T will be everywhere and we have got priority for NSX-T so though it might sounds sad, but NSX-V will have less time investment going further.
Today you can't do DFW for any system, but the fact is that it will arrive for NSX-T first.

**Comment by badsector3** [comment]
@Didainius thanks for clarification on the matter. Do we have any idea when DFM for NSX-T will be available?

**Comment by mrdima** [comment]
Upvote here as well. Can we get an update on when this will be at least considered?

**Comment by Didainius** [comment]
NSX-T DFW resources exist now and latest 3.7.0 release brought in dynamic security group support
