### ISSUE TITLE
vApp + VM creation fails when multiple VMs are present in vApp

### ISSUE THREAD

**Issue by ukcloud-rubeon** [vmware/terraform-provider-vcd#172]
### Terraform Version

```
$ terraform version
Terraform v0.11.7
+ provider.vcd v2.0.0
```

### Affected Resource(s)

- `vcd_vapp`
- `vcd_vapp_vm`

### Terraform Configuration Files
```hcl
variable "catalog" {
  default = "MyVCD Catalogue"
}

variable "public_ip" {
  default = "1.2.3.4"
}

variable "vcd_max_retry_timeout" {
    default = 600
}

variable "centos" {
  default = "MyVCD_CentOS_7_3_x64_60GB_Small_v1.0.2"
}

variable "vcd_edgegateway" {
    default = "Internet_02(xxxx)"
}

variable "cidr" {
    default = {
        external = "172.16.3.0/24"
    }
}

variable "vcd_allow_unverified_ssl" {
  default = false
}

variable "vcd_logging" {
    default = true
}


variable "external" {
  default = {
      gw = "172.16.3.1"
      static_start_address = "172.16.3.2"
      static_end_address = "172.16.3.100"
      dhcp_start_address = "172.16.3.101"
      dhcp_end_address = "172.16.3.200"

  }
}

provider "vcd"  {
    user = "${var.vcd_creds["username"]}"
    password = "${var.vcd_creds["password"]}"
    org = "${var.vcd_creds["org"]}"
    vdc = "${var.vcd_creds["vdc"]}"
    url = "${var.vcd_creds["url"]}"
    allow_unverified_ssl = "${var.vcd_allow_unverified_ssl}"
    max_retry_timeout    = "${var.vcd_max_retry_timeout}"
    logging = "${var.vcd_logging}"
}


resource "vcd_network_routed" "external" {
    org = "${var.vcd_creds["org"]}"
    vdc = "${var.vcd_creds["vdc"]}"

    name = "external-network"
    edge_gateway = "${var.vcd_edgegateway}"
    gateway = "${var.external["gw"]}"

    static_ip_pool = {
        start_address = "${var.external["static_start_address"]}"
        end_address = "${var.external["static_end_address"]}"
    }

    dns1 = "8.8.8.8"
    dns2 = "8.8.4.4"

    dhcp_pool = {
        start_address = "${var.external["dhcp_start_address"]}"
        end_address = "${var.external["dhcp_end_address"]}"
    }

}

resource "vcd_vapp" "web" {
    name = "Web"
    depends_on = ["vcd_network_routed.external"]
}

resource "vcd_vapp_vm" "web1" {
    name = "web-01"
    vapp_name = "${vcd_vapp.web.name}"
    catalog_name = "${var.catalog}"
    template_name = "${var.centos}"
    memory = 2048
    cpus = 2
    network_name = "${vcd_network_routed.external.name}"
    # ip = "172.16.3.3"
    ip = "allocated"
    depends_on = ["vcd_vapp.web"]
}

resource "vcd_vapp_vm" "web2" {
    name = "web-02"
    vapp_name = "${vcd_vapp.web.name}"
    catalog_name = "${var.catalog}"
    template_name = "${var.centos}"
    memory = 2048
    cpus = 2
    network_name = "${vcd_network_routed.external.name}"
    # ip = "172.16.3.3"
    ip = "allocated"
    depends_on = ["vcd_vapp.web"]
}

```

### Debug Output

- https://gist.github.com/ukcloud-rubeon/bea6b4636d4e71554e8a638e43ffda14/raw/984391c7de18754bd04109dbb6450ddceef28eed/govcd.log
- https://gist.github.com/ukcloud-rubeon/1724aa1615cd0db2ea527d8dc14e8e16

### Panic Output

None.

### Expected Behavior

vApp with 2 VMs successfully created.

### Actual Behavior

vApp VM creation fails with other `busy completing an operation VAPP_DEPLOY`:

```
* vcd_vapp_vm.web1: error Powering Up: &errors.errorString{s:"error powering on VM: API Error: 400: [ b2281781-8176-4d89-b996-55003dd1701c ] The entity web-02 is busy completing an operation VAPP_DEPLOY."}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
0. `terraform init`
1. `terraform plan`
2. `terraform apply`

### Important Factoids

Successful Creation of vApp VM appears to trigger immediate vApp power cycle, which will error out when
other VMs in vApp are busy

**Comment by lvirbalas** [comment]
CC: @dataclouder @vbauzysvmware @Didainius

**Comment by vbauzysvmware** [comment]
Thank you @ukcloud-rubeon for robust Issue with information. I identified issue and as it is expected is due race conditioning. VM resource doesn't seem was implemented with intention to support multi VM creation for one vAPP in older version. I'll look how to improve this.

**Comment by vbauzysvmware** [comment]
Well I have solution which fix this issue. And it works with `count`. It will take a little time for fix to come in repo as we moving to new terraform-go modules and all PR stopped in mean time. If you are urgent I can provide patch.

**Comment by ukcloud-rubeon** [comment]
Hi, @vbauzysvmware  thanks for the update!

It's not extremely urgent, great to know there's a fix in the works. If there's a branch for the fix, I'd be happy to do testing.

Thanks,
Eric

**Comment by vbauzysvmware** [comment]
I created branch with fix: https://github.com/vbauzysvmware/terraform-provider-vcd/tree/fix-multi-vm-creation

**Comment by nicslatts** [comment]
@lvirbalas was this fix merged into the master branch for version 2.2? Received some feedback yesterday that a plan with multiple VMs fails with timeout. Perhaps they are using an outdated version.

**Comment by Didainius** [comment]
I can see that this particular fix was merged and released in `2.1`. Are there any more details about the problem?

**Comment by nicslatts** [comment]
@Didainius thanks, no more details yet but I'll do some digging.

**Comment by Didainius** [comment]
@nicslatts, @ukcloud-rubeon , do we think this is still relevant? Even more improvements happened in this space after this issue so I'm pretty sure this should not occur unless confirmed.
