### ISSUE TITLE
RFE: Allow configuring of vApp network firewall / NAT

### ISSUE THREAD

**Issue by floriankammermann** [vmware/terraform-provider-vcd#193]
This is a feature request to implement the possibility to implement the configuration of the firewall / NAT of the vApp network.

vApp network configuration was introduced with https://github.com/terraform-providers/terraform-provider-vcd/commit/5cab61f74b82e9ccbcd89897ed3215c57aa6d407

Next step would be to introduce the possibility to configure the firewall / NAT of a vApp network.

**Comment by lvirbalas** [comment]
Hi Florian,

Please suggest a .tf resource configuration design/sample you'd like to see to kick-start development. Also, don't hesitate to implement this if you'd like - we have PRs coming in from community on other features.

**Comment by lvirbalas** [comment]
FYI: @vbauzysvmware

**Comment by floriankammermann** [comment]
Suggestion for enhancement of `vcd_vapp_network` resource:
```
resource "vcd_vapp_network" "vapp-test-net" {
  depends_on    = ["vcd_vapp.vapp-test"]
  name               = "vapp-test-net"
  vapp_name          = "vapp-test"
  parent_network     = "test-net"
  fence_mode         = "natRouted"
  gateway            = "192.168.3.1"
  netmask            = "255.255.255.0"
  static_ip_pool {
    start_address = "192.168.3.2"
    end_address   = "192.168.3.254"
  }
  firewall_rule {
      description = "testrule1"
      policy = "allow"
      protocol = "any"
      destination_port = "any"
      destination_ip = "any"
      source_port = "any"
      source_ip = "internal"
    }
}
```

Suggestion for a `vcd_vapp_network_nat` resource:
```
resource "vcd_vapp_network_nat" "vapp-test-net-nat" {
  depends_on    = ["vcd_vapp_vm.vapp-test-vm"]
  vapp_name = "vapp-test"
  vapp_network_name = "vapp-test-net"
  nat_type = "ipTranslation"
  
  rule {
    external_ip_address = "192.168.3.2"
    mapping_mode = "manual"
    vm_name = "vapp-test-vm"
    vm_nic_id = 0
  }
}
```

For completness the `vapp-test-vm`:
```
resource "vcd_vapp_vm" "vapp-test-vm" {
  depends_on    = ["vcd_vapp.vapp-test"]
  vapp_name     = "${vcd_vapp.vapp-test.name}"
  name          = "vapp-test-vm"
  catalog_name  = "vm-images"
  template_name = "Ubuntu16.04x64"
  memory        = 1024
  cpus          = 1
  vapp_network_name  = "vapp-test-net"
  ip            = "192.168.3.2"
}
```

Explanation:
* `vcd_vapp_network` -> `parent_network` is the [ParentNetwork](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L206)
* `vcd_vapp_network` -> `fence_mode` is the [FenceMode](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L208)
* `vcd_vapp_network` -> `firewall_rule` is the [FirewallRule](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1440)
* `vcd_vapp_network_nat` -> `nat_type` is the [NatType](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1481)
* `vcd_vapp_network_nat` -> `rule` is the [NatRule](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1492)
* `vcd_vapp_network_nat` -> `rule` -> `external_ip_address` is the [ExternalIPAddress](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1545)
* `vcd_vapp_network_nat` -> `rule` -> `mapping_mode` is the [MappingMode](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1544)
* `vcd_vapp_network_nat` -> `rule` -> `vm_name` is the [VAppScopedVMID](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1546) but expressed as the `vcd_vapp_vm` `name`
* `vcd_vapp_network_nat` -> `rule` -> `vm_nic_id` is the [VMNicID](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1547)


Design consideration:
* Because of the creation flow, I needed to extract `vcd_vapp_network_nat` in its own resource. 
  Since the flow is like this `vcd_vapp` -> `vcd_vapp_network` -> `vcd_vapp_vm` -> `vcd_vapp_network_nat`

Open Questions:
* Is it ok to have the firewall rule in the `vcd_vapp_network`. Or should it be its own resource? Perhaps we can enhance the existing [vcd_firewall_rules](https://www.terraform.io/docs/providers/vcd/r/firewall_rules.html) resource?

Problems:
* I used the [NatOneToOneVMRule](https://github.com/vmware/govcloudair/blob/master/types/v56/types.go#L1501), but there are other NatRule types. How to model this into the tf resouce definition?

**Comment by vbauzysvmware** [comment]
Great ideas and thank you for your effort. I checked in and ideas looks good. My consideration are:
* Usually we try to follow UI capabilities - to not mess up and easier to understand for users
* I think vApp firewall resources should separate. It same case as with NAT configuration - you should have VM and NIC's to setup rule or you can use "external"/"internal". But anyways generic case is use as separate resource.
* I think we should have separate vApp fire wall resource and not reuse `vcd_firewall_rules` - as  it has more properties and not just only one different one. For e.g. we can not make one firewall rule and say apply to edge_gateway or vApp network.

**Comment by pasikarkkainen** [comment]
+1 for this RFE. I need vApp Networks with NAT configurable rules aswell.

**Comment by Didainius** [comment]
We have this functionality for a long time now.
