### ISSUE TITLE
Redesign vApp and VM resources

### ISSUE THREAD

**Issue by vbauzysvmware** [vmware/terraform-provider-vcd#217]
Current implementation allows to manage VM stuff and other things in vApp resources which should be separately managed in own resources. And VM have own resource already.

Aim so to design new vApp and VM resource to solve various currently existing various issues. After design approved - implement the changes.

kradalby in his repo have already tried to do that and have one of possible designs and implementations.
Documentation of resources:
https://github.com/terraform-providers/terraform-provider-vcd/blob/d5c14ed706f95139576f2b5b71fac63f639f89c1/website/docs/r/vapp.html.markdown
https://github.com/terraform-providers/terraform-provider-vcd/blob/d5c14ed706f95139576f2b5b71fac63f639f89c1/website/docs/r/vm.html.markdown

 All code is one big PR which has to be closed as too old and too big to be merged.
https://github.com/terraform-providers/terraform-provider-vcd/pull/74

**Comment by vbauzysvmware** [comment]
For me known:
* Vapp resource allows work with VM
* Do not allow to add vapp_network
* Works only with one network
* Power off not in right places or done when not needed

**Comment by vbauzysvmware** [comment]
VM should support more custimizations some e.g. can be found in https://github.com/terraform-providers/terraform-provider-vcd/pull/74/commits/98b1990213dd3abb939b9ee90b010b22673699a0. For e.g. values: AdminPasswordAuto, AdminPassword, AdminAutoLogonEnabled, ResetPasswordRequired, etc.

**Comment by vbauzysvmware** [comment]
Add storage profile support for VM: https://github.com/terraform-providers/terraform-provider-vcd/pull/74/commits/eb9c484c5205fda3b98d3506b9a5b132bf5adf78

**Comment by Didainius** [comment]
We are way beyond this initial discussion and we have quite a few features added from that list. Also there is standalone VM.
