### ISSUE TITLE
Catalog: specify site

### ISSUE THREAD

**Issue by lroellin** [vmware/terraform-provider-vcd#232]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

**Feature Request**

Originally opened this here (https://github.com/vmware/go-vcloud-director/issues/187), copy-pasting info:

To attach a media to a VM, the media's catalog and the VM's DC need to be on the same site. (So I'm told).

In the GUI (at least the Flash UI) I can specify this. I haven't found it in this provider.

**Comment by vbauzysvmware** [comment]
@lroellin, please elaborate. Could you be more specific what you specify in UI? screenshots would help.

**Comment by lroellin** [comment]
Actually, I've since changed teams and I'm not responsible for the project anymore.

When creating a catalog, I can specify that it needs to be on a specific site. I can then specify what vDC the catalog should be "sitting in".

The problem is, that at least in our installation, a media cannot be mounted on a vApp VM, if the vApp VM and the catalog in which this media lies are not in the same site. 

I therefore wanted to have an extra property on the 'catalog' resource where I could specify this "backing vDC".

**Comment by vbauzysvmware** [comment]
@lroellin  thank you for information

**Comment by Didainius** [comment]
I think this is about specifying storage policies and our `vcd_catalog` resource supports it starting with v3.1.0 -> https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/catalog#storage_profile_id
