### ISSUE TITLE
Rename vcd_edgegateway_vpn to vcd_vpn resource for consistency

### ISSUE THREAD

**Issue by lvirbalas** [vmware/terraform-provider-vcd#269]
The goal of this issue to track a semantic change in the sake of consistency of resource names that can be done with 3.0.0:

- Rename `vcd_edgegateway_vpn` resource to `vcd_vpn`

### Affected Resource(s)

- `vcd_edgegateway_vpn`

### Important Factoids

- We are now adding a separate resource `vcd_edgegateway` 
- We are adding more resources that are hierarchically under EG (`vcd_lb_service_monitor`, `vcd_lb_server_pool`, etc.), but we are *not* naming them with the long `vcd_edgegateway_` prefix to avoid extra long names

### References

https://github.com/terraform-providers/terraform-provider-vcd/pull/263
https://github.com/terraform-providers/terraform-provider-vcd/issues/223

**Comment by Didainius** [comment]
NSX-V Is not getting more investments and this is no longer relevant.
