### ISSUE TITLE
VDC creation fails when Provider VDC name contains spaces

### ISSUE THREAD

**Issue by acederlund** [vmware/terraform-provider-vcd#306]
### Terraform Version
Terraform v0.12.6
+ provider.vcd v2.4.0

### Affected Resource(s)
- vcd_org_vdc

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

```hcl
### Terraform Configuration Files
resource "vcd_org" "new_org" {
  name             = "${var.cust_name_short}"
  full_name        = "${var.cust_name_long}"
  description      = "${var.cust_name_desc}"
  is_enabled       = "true"
  delete_recursive = "true"
  delete_force     = "true"
  can_publish_catalogs = "false"
}


resource "vcd_org_user" "vcduser" {
  org = "${var.cust_name_short}"

  name          = "${var.cust_admin_user}"
  description   = "${var.cust_admin_desc}"
  role          = "Organization Administrator"
  password      = "${var.cust_admin_pass}"
}


resource "vcd_org_vdc" "orgvdc" {
  name = "${var.cust_vdc_name}"
  description = "${var.cust_vdc_desc}"
  org = "${var.cust_name_short}"

  allocation_model = "AllocationVApp"
  network_pool_name = "Labb VDC-VXLAN-NP"
  provider_vdc_name = "Labb VDC"

  storage_profile {
    name = "vCloud Storage"
    default = true
    limit = 0
  }

  compute_capacity {
    cpu {
      limit = 0
    }

    memory {
      limit = 0
    }
  }


  enabled = true
  enable_thin_provisioning = true
  enable_fast_provisioning = true
  delete_force = true
  delete_recursive = true

}
```

### Debug Output
https://gist.github.com/acederlund/d157a5dab69707344f725f688d00026f

### Expected Behavior
A new organization VDC should have been created.

### Actual Behavior
An error was returned: Error: error retrieving query: [ParseErr]: error parsing error body for non-200 request: EOF (&{Status:400 Unknown Version StatusCode:400 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Length:[0]] Body:{} ContentLength:0 TransferEncoding:[] Close:true Uncompressed:false Trailer:map[] Request:0xc000410400 TLS:0xc0002c2d10})

### Steps to Reproduce
1. `terraform apply`

### References
Not to my knowledge.

**Comment by elandmancrs** [comment]
I've received this when vCLoud is under high load sometimes. 
Try the add the -parallelism=1 to your apply. 
I usually have to change between 1 & 2 depending on times of day(load).
Cheers

**Comment by acederlund** [comment]
> 
> 
> I've received this when vCLoud is under high load sometimes.
> Try the add the -parallelism=1 to your apply.
> I usually have to change between 1 & 2 depending on times of day(load).
> Cheers

Hi,

Thanks for the input! I've tried this, but the environment is a test environment with practically no load at all. It could be a vCD bug as well, so I'll try and patch to the latest 9.7 build.

**Comment by dataclouder** [comment]
Hi
Thanks for reporting this issue.

One possibility is that the VDC creation happened too early, before the org was created.

If you run `terraform apply` again after the failure, does the task complete?

If yes, what you need to do is replacing `org = "${var.cust_name_short}"` with `org = "${vcd_org.new_org.name}"`.

If not, we would need more info. You can enable the operations log by adding `logging = "true"`
to the provider section, and then submit it with a Gist. Make sure that the log didn't get any private info before submitting (it should not, but look just in case)

**Comment by acederlund** [comment]
Thanks for the update. I've added the dependency for org on the vdc and user resource, but in subsequent runs I still get the error. Here's the Gist, I've censored the hostname for vCCD.
https://gist.github.com/acederlund/909b00410ef82bece4a4ddd68c6d903d

**Comment by dataclouder** [comment]
I suspect the issue is in the Provider VDC name containing a space.
Could you try renaming the **Provider VDC** temporarily without a space and repeating the `apply`?

**Comment by acederlund** [comment]
> 
> 
> I suspect the issue is in the Provider VDC name containing a space.
> Could you try renaming the **Provider VDC** temporarily without a space and repeating the `apply`?

I suspect you are on to something here! I changed the name and removed the space (which updates the network pool automatically), and after updating my terraform config it now applies correctly!

vcd_org_vdc.orgvdc: Creation complete after 30s [id=urn:vcloud:vdc:a4d7f884-2402-4321-828b-66e823571a6a]

Could this bug be related to terraform or vcloud director?

**Comment by dataclouder** [comment]
I think it's in our code (go-vcloud-director).
I am changing the title of the issue to reflect this finding

**Comment by vbauzysvmware** [comment]
Fix in PR now.
