### ISSUE TITLE
Add resources to create and manage security groups

### ISSUE THREAD

**Issue by jpbuecken** [vmware/terraform-provider-vcd#315]
Hi,

could you please add support to create security groups and manage it members:
This is the corresponding vCD documentation:

https://docs.vmware.com/en/vCloud-Director/9.0/com.vmware.vcloud.tenantportal.doc/GUID-7343CBF0-561F-4C0F-B7A4-016067F79203.html

https://docs.vmware.com/en/vCloud-Director/9.0/com.vmware.vcloud.tenantportal.doc/GUID-A7F70068-0DA4-4FB8-9185-6608AA8B4346.html

I'm not sure about the best way to implement management of membership. AWS, OCI and Openstack implement this as part of the port/network interface or of the VM/instance resource. 
But vCD follow another approach in its GUI. Straight forward is to configure membership in the resource which create it. 
Or you implement an attachment resource which attach a security group to a member (VM, Network, ....)
All three ways will have its advantage and disadvantage.

### Terraform Version
ALL

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_security_group  (suggestion)

### Terraform Configuration Files
No HCL suggestion yet, maybe similar to https://www.terraform.io/docs/providers/aws/r/security_group.html
https://www.terraform.io/docs/providers/aws/r/network_interface.html (for attachment)

**Comment by Didainius** [comment]
We already have some security groups for NSX-T and NSX-V will not have any major investment.
