### ISSUE TITLE
Provider VDC (PVDC) resource

### ISSUE THREAD

**Issue by lvirbalas** [vmware/terraform-provider-vcd#326]
Placeholder for implementing `vcd_provider_vdc` (or just `vcd_vdc`) resource.
Includes ability to assign metadata too.

**Comment by dataclouder** [comment]
Implemented with PR #1073

**Comment by dataclouder** [comment]
[vcd_provider_vcd](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/provider_vdc)
