### ISSUE TITLE
Enhance guest properties support

### ISSUE THREAD

**Issue by swerveshot** [vmware/terraform-provider-vcd#350]
### Terraform Version
Terraform v0.12.10
\+ provider.vcd v2.5.0

### Affected Resource(s)
- vcd_vapp_vm

### Actual Behavior
Although I am very pleased with initial support for guest properties, the current implementation is rather basic. As an example here is a screenshot from the vSphere web client of a vApp VM I created with the vCD provider. You can see the key for setting a hostname is used and the label is set to whatever key is used. Also a default value is set rather than an actual value. Lastly only a string datatype is supported at the moment.

![image](https://user-images.githubusercontent.com/10358044/66747869-dbf77700-ee85-11e9-9382-5faef67f6908.png)

### Expected Behavior
It would be preferable to have the ability to set a label, value, default value and datatype. Such as is possible when deploying a OVA directly on vSphere.

![image](https://user-images.githubusercontent.com/10358044/66747993-49a3a300-ee86-11e9-91bd-a580cb3b7105.png)

### Steps to reproduce

1. Download [one of the nested ESXi virtual appliances](https://www.virtuallyghetto.com/nested-virtualization/nested-esxi-virtual-appliance) from @lamw 
2. Upload the OVA file to a catalog
3. Use the Terraform project below as a basis to create a vApp
4. Observe the guest properties that are used

```
provider "vcd" {
  version = "~> 2.5.0"
  url      = "https://my-vcdserver/api"
  user     = "my-user"
  password = "my-password"
  org      = "my-org"
  allow_unverified_ssl = "true"
  logging = "false"
}

resource "vcd_vapp" "my-vapp" {
  name = "my-vapp"
  org = "my-org"
  vdc = "my-vdc"
}

resource "vcd_vapp_vm" "my-vm" {
  count         = 1
  vapp_name     = "${vcd_vapp.my-vapp.name}"
  org           = "my-org"
  vdc           = "my-vdc"
  // format vm name using a zero-prefix and a count
  name          = "${format("my-vm-%02d", count.index + 1)}"
  catalog_name  = "my-catalog"
  template_name = "my-vapp-template"
  expose_hardware_virtualization = "true"
  cpus          = 2
  memory        = 6144
  accept_all_eulas = "true"
  
  network {
    type               = "org"
    name               = "my-vdcnet"
    // select an IP address from a variable
    ip                 = "${var.my_ip[count.index]}"
    ip_allocation_mode = "MANUAL"
    is_primary         = true
  }

guest_properties = {
    "guestinfo.hostname" = "my-hostname"
}

  depends_on = ["vcd_vapp.my-vapp"]
}
```

### References
[Deploying Nested ESXi is even easier now with the ESXi Virtual Appliance](https://www.virtuallyghetto.com/2015/12/deploying-nested-esxi-is-even-easier-now-with-the-esxi-virtual-appliance.html) - This document lists all of the guest properties for a nested ESXi server.

**Comment by vbauzysvmware** [comment]
Thank you for your proposal. We will look into it.

**Comment by swerveshot** [comment]
Thanks @vbauzysvmware! If there's anything I can contribute, lease let me know.

**Comment by patsevanton** [comment]
Hello!
```
terraform -version
Terraform v0.13.5
+ provider registry.terraform.io/vmware/vcd v3.0.0
VMware Cloud Director version: 10.2.0.17008054
```
I try set hostname in vm in parameter guest_properties.
But don`t work.

```
  guest_properties = {
    "guest.hostname"   = "ansible-server"
  }
```
In vm:
```
[root@centos ~]#
```

**Comment by Didainius** [comment]
Hello @patsevanton,
This is probably the never-ending story of guest tools and how the image works with them.
Do you know if `cloud-init` is executed well and is it using `DataSourceOVF`?
If so - looking at the code of `DataSourceOVF` (provided it is the right version) it should be able to read hostname from `hostname` or `local-hostname` guest property. (as per this code https://github.com/canonical/cloud-init/blob/master/cloudinit/sources/DataSourceOVF.py#L436-L455)

**Comment by patsevanton** [comment]
@Didainius Hello! Thanks for answer.
I don`t use cloud-init

What is cloud-init use?
 - https://github.com/vmware/cloud-init-vmware-guestinfo
 - classic cloud-init ?

**Comment by Didainius** [comment]
@patsevanton,
`cloud-init` is like an engine for customization, but then it has datasources (like plugins - https://cloudinit.readthedocs.io/en/latest/topics/datasources.html) for getting metadata as different platforms feed in metadata differently.
Your CentOS image might or might not have cloud-init by default - this is why I am asking.
What I saw was that usually a default image would not include the more sophisticated https://github.com/vmware/cloud-init-vmware-guestinfo, but only DataSourceOVF which is pretty limited.

As a first step I can propose to try and see `cloud-init` logs in the booted up to machine which at least in Ubuntu are usually located in:
* /var/log/cloud-init.log
* /var/log/cloud-init-output.log
* /var/log/vmware-imc/toolsDeployPkg.log

**Comment by patsevanton** [comment]
Thanks! I will try

**Comment by patsevanton** [comment]
I created vmware template from image + https://github.com/vmware/cloud-init-vmware-guestinfo

Run terraform code without guest_properties, but

```
cat /var/log/cloud-init.log
cat: /var/log/cloud-init.log: No such file or directory

cat /var/log/cloud-init-output.log
cat: /var/log/cloud-init-output.log: No such file or directory

cat /var/log/vmware-imc/toolsDeployPkg.log
cat: /var/log/vmware-imc/toolsDeployPkg.log: No such file or directory
```

**Comment by patsevanton** [comment]
```
 cat /etc/cloud/cloud.cfg.d/99-DataSourceVMwareGuestInfo.cfg
# Cloud-Init Datasource for VMware Guestinfo
#
# Copyright (c) 2018 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Apache 2.0 license (the "License").
# You may not use this product except in compliance with the Apache 2.0 License.
#
# This product may include a number of subcomponents with separate copyright
# notices and license terms. Your use of these subcomponents is subject to the
# terms and conditions of the subcomponent's license, as noted in the LICENSE
# file.

datasource_list: [ "VMwareGuestInfo" ]
```

**Comment by Didainius** [comment]
@patsevanton ,
Have you ever get to a working solution for this?

**Comment by Didainius** [comment]
OK. This means I am closing it down now.
