### ISSUE TITLE
Add catalog details represeting properties as computed fields

### ISSUE THREAD

**Issue by vbauzysvmware** [vmware/terraform-provider-vcd#365]
We can enhance catalog with additional fields which provides more details about catalog.
For e.g.  isShared, isPublished, ownerName, numberOfVAppTemplates,numberOfMedia, etc.

**Comment by mikeletux** [comment]
This feature will be available in v3.6.0.
Feature merge in https://github.com/vmware/terraform-provider-vcd/pull/800
