### ISSUE TITLE
Implement meta data support for available resources

### ISSUE THREAD

**Issue by vbauzys** [vmware/terraform-provider-vcd#372]
A several resource already support meta data. Most of existing resources have also metadata ability.
Aim is add metadata ability to all possible resource.

Catalog
CatalogItem - implemented
Disk
Media - implemented
Network(Nsxv)
Organization
vApp - implemented
vAppTemplate
VDC - implemented
vdcStorageProfle
edge gtw(NSXV)
providerVDC
pvdcStorageProfle - 
VM - implemented

**Comment by lvirbalas** [comment]
Please provide an exact list of resources where metadata is still missing and should be added.

**Comment by acederlund** [comment]
Hi,

I've found that the vcd_org object is lacking metadata properties, and would be greatful to get support for this since we're using it for integration with billing systems :)

So far, I've found these other resources capable of metadata, but either lacks metadata properties or is lacking resourcetypes:
- Provider VDC (no object here, not sure it's needed either)
- Organizations
- Catalogs (tho there is support for both catalog items and media items)
- Storage Policies

There might be more, but this is what I've found so far.

**Comment by dataclouder** [comment]
Hi @acederlund,
Currently we don't have plans to add provider VDC and storage policy resources or data sources. 

Regarding metadata,  we want to add metadata handling to Orgs, catalogs, networks, but it won't happen in the present release.

Instead, we're working on a system that uses metadata for filtering data sources, even for resources that can't modify metadata. A prototype will soon be available.

**Comment by lvirbalas** [comment]
> Currently we don't have plans to add provider VDC

To be more specific: we have PVDC in the pipeline, but not in the near term plans.

**Comment by mikeletux** [comment]
@vbauzysvmware catalog implemented as per #780

**Comment by carmine73** [comment]
Any step forward for `vcd_org` metadata?

**Comment by adambarreiro** [comment]
@carmine73 Yes, currently we're preparing [a PR](https://github.com/vmware/terraform-provider-vcd/pull/790) to add this feature.

**Comment by bogi0704** [comment]
Are different User Access Levels ("Read/Write","Read only","Hidden") also in scope for the metadata fields. We would like to use hidden Attributes as an msp for our internal automations and processes, but also enable our customers to set read/write attributes for processes that they should be able to influence.

**Comment by vbauzysvmware** [comment]
> @carmine73 Yes, currently we're preparing [a PR](https://github.com/vmware/terraform-provider-vcd/pull/790) to add this feature.

@adambarreiro could you link all metadata PR to this Issue? :)

**Comment by adambarreiro** [comment]
Current metadata support additions:
- VDC networks #804
- Organizations #797
- Disks #797
- Catalogs #780

Will update this message once we get more going :)

**Comment by carmine73** [comment]
> Are different User Access Levels ("Read/Write","Read only","Hidden") also in scope for the metadata fields? We would like to use hidden Attributes as an msp for our internal automations and processes, but also enable our customers to set read/write attributes for processes that they should be able to influence.

anything planned on that? thanks

**Comment by adambarreiro** [comment]
Hi @carmine73, sorry for the late response! We're planning to add the user access levels in the next release (v3.8.0)

**Comment by adambarreiro** [comment]
Hi folks! We have the new `metadata_entry` attribute in all previous resources and data sources implemented in v3.8.0 that was just released. For example [this one](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#metadata). It supports all the types, user access levels and domain.

Hence I'm closing this issue.
