### ISSUE TITLE
Terraform crash 

### ISSUE THREAD

**Issue by gevraud** [vmware/terraform-provider-vcd#381]
Hi, 

I am trying simple config with version of vcd provider and I got new a terraform crash error on "github.com/terraform-providers/terraform-provider-vcd/vcd.setOrgVdcData".

vcd provider : 2.5
terraform : 0.12.08

Here is the logs :
[crash.log](https://github.com/terraform-providers/terraform-provider-vcd/files/3789511/crash.log)
Regards

**Comment by dataclouder** [comment]
Hi,
Thanks for reporting an issue.
Please post the script that you were executing when the crash occurred. (Remove sensitive info before posting)

**Comment by buec011** [comment]
I'm not sure if it is related, but you are using terraform 0.12, but your syntax 
`org     = "${data.vcd_org.elk.name}"`

is terraform 0.11

In terraform 0.12 the same line should be

`org     = data.vcd_org.elk.name`

**Comment by gevraud** [comment]
Hi,

I tried the new syntax (removed the "{}" on vars) but still the same issue

Regards

**Comment by gevraud** [comment]
Hi,

I have tried with 3 roles with the user. : 
- my cloud user
- my cloud super user
- my cloud org admin

Result is the same. The user is a local user.

Regards

**Comment by gevraud** [comment]
Hi, 

There are only 2 VDC's in this org . As I don't know which one is the "default" one, I created 2 datasources. Also, I tried with different role (user, super user, org admin)

Result is the same.

Regards

**Comment by vbauzysvmware** [comment]
Hi @gevraud - to better understand issue we need more logs from go-vcloud-director which should be enabled.
How to enable is mentioned in documentation: https://www.terraform.io/docs/providers/vcd/index.html - parameters logging, logging_file.

**Comment by vbauzysvmware** [comment]
If more information will arrive, then this issue could be reopen. Yet please try latest release of provider and terraform.
