### ISSUE TITLE
vcd_vapp_vm: network: Do not reboot VM if you add/update network interface

### ISSUE THREAD

**Issue by jpbuecken** [vmware/terraform-provider-vcd#388]
If you add a second network interface to a vm in vcd_vapp_vm via terraform, the VM will be rebootet. If you do the same with API /HTML5 client, you don't have a downtime.

We have use cases that require additional interfaces of other or even same network, but with zero downtime.

### Terraform Version
Terraform v0.12.13
+ provider.vcd v2.6.0-3e0dc271671b000a4809f020e98b9e32415f52fc (self build of https://github.com/terraform-providers/terraform-provider-vcd/pull/386 )

### Affected Resource(s)
Please list the resources as a list, for example:
- vpc_vapp_vm

### Terraform Configuration Files
```hcl
  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = var.private_ip == null ? "POOL" : "MANUAL"
    ip                 = var.private_ip
    is_primary         = true
  }
  # added this after initial apply:
  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = "POOL"
  }
```

```hcl
> terraform apply
vcd_vapp.vapp: Refreshing state... [id=urn:vcloud:vapp:68b35c78-a561-43e0-943f-ad4d61f2bffc]
vcd_vapp_vm.instance: Refreshing state... [id=urn:vcloud:vm:92eef41b-c39e-4305-bb5e-4562a184817c]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vcd_vapp_vm.instance will be updated in-place
  ~ resource "vcd_vapp_vm" "instance" {
        accept_all_eulas               = true
        catalog_name                   = "linux"
        computer_name                  = "test1"
        cpu_cores                      = 1
        cpus                           = 1
        expose_hardware_virtualization = false
        guest_properties               = {}
        href                           = "https://test/api/vApp/vm-92eef41b-c39e-4305-bb5e-4562a184817c"
        id                             = "urn:vcloud:vm:92eef41b-c39e-4305-bb5e-4562a184817c"
        memory                         = 1024
        metadata                       = {}
        name                           = "test1"
        power_on                       = true
        storage_profile                = "test"
        template_name                  = "centos"
        vapp_name                      = "test1"

        network {
            ip                 = "10.65.67.100"
            ip_allocation_mode = "MANUAL"
            is_primary         = true
            mac                = "00:50:56:0b:01:47"
            name               = "test-network-01"
            type               = "org"
        }
      + network {
          + ip_allocation_mode = "POOL"
          + name               = "test-network-01"
          + type               = "org"
        }
    }
```

### Expected Behavior
Adding a network interface should behave the same as in HTML5 GUI.
Adding network interface should be possible without downtime for the OS.

### Actual Behavior
The VM will be rebootet

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Add code for additional network interface
3. `terraform apply`

**Comment by Didainius** [comment]
Thanks @buec011, I'll have a look at it.

**Comment by buec011** [comment]
Hello Didainus, thank you.
For your information:

The reboot is also triggered if I change the network of an existing interface only.
e.g. created with
```
  network {
    type               = "none"
    ip_allocation_mode = "NONE"
  }
```
then change to
```
  network {
    type               = "org"
    name = "test-network-01"
    ip_allocation_mode = "POOL"
  }
```
Diff is
```
      ~ network {
          ~ ip_allocation_mode = "NONE" -> "POOL"
            is_primary         = false
            mac                = "00:50:56:0b:01:5c"
          + name               = "test-network-01"
          ~ type               = "none" -> "org"
        }
```
Reboot occurs

**Comment by Didainius** [comment]
Thanks - yes indeed. At the moment it uses the "cold" method for all network changes. I need to validate which parameters can be done in "hot" vs "cold" manner.

**Comment by NilsBusche** [comment]
Hi, what's the current state for this issue?

**Comment by vbauzysvmware** [comment]
PR is merged. Anyone interested can test ;-)

**Comment by jpbuecken** [comment]
Hi,
it looks like it still reboots if you remove an interface.
For a modern linux system (CentOS7, SLES12, SLES15) it is not a problem to hot remove the interface:

HCL:
```hcl
  network {
    type               = "org"
    name               = vcd_vapp_org_network.vappnetattach.org_network_name
    adapter_type       = var.nic_controller
    ip_allocation_mode = var.private_ip == null ? "POOL" : "MANUAL"
    ip                 = var.private_ip
    is_primary         = true
  }

  network {
    type               = "org"
    name               = vcd_vapp_org_network.vappbackupnetattach.org_network_name
    adapter_type       = var.nic_controller
    ip_allocation_mode = "POOL"
    is_primary         = false
  }

```
Remove the second network description and apply

**Comment by jpbuecken** [comment]
I see we only requested add and update via this issue...

**Comment by vbauzysvmware** [comment]
> Hi,
> it looks like it still reboots if you remove an interface.
> For a modern linux system (CentOS7, SLES12, SLES15) it is not a problem to hot remove the interface:
> 
> HCL:
> 
> ```terraform
>   network {
>     type               = "org"
>     name               = vcd_vapp_org_network.vappnetattach.org_network_name
>     adapter_type       = var.nic_controller
>     ip_allocation_mode = var.private_ip == null ? "POOL" : "MANUAL"
>     ip                 = var.private_ip
>     is_primary         = true
>   }
> 
>   network {
>     type               = "org"
>     name               = vcd_vapp_org_network.vappbackupnetattach.org_network_name
>     adapter_type       = var.nic_controller
>     ip_allocation_mode = "POOL"
>     is_primary         = false
>   }
> ```
> 
> Remove the second network description and apply

Well with linux I tried cold reboot was needed, that's why it was implemented as it is now. I would need to verify that API allows hot removal on latest linux release. If yes - we get question how to implement such logic and not lock to specific linux version checking...

**Comment by jpbuecken** [comment]
> Well with linux I tried cold reboot was needed, that's why it was implemented as it is now. I would need to verify that API allows hot removal on latest linux release. If yes - we get question how to implement such logic and not lock to specific linux version checking...

Oh, tested with VCD 10.1 and you are right, at least the GUI does not allow you to remove it (Hardware Verison vmx-14).
I will check VCD 10.0.1, I'm sure I did this in the past ...

**Comment by jpbuecken** [comment]
It is working in VCD 10.0.1 (tested with SLES12, vmx-14). It looks like a VCD UI issue. Not tested if it is still possible with API or maybe API version 33 instead of 34...

**Comment by jpbuecken** [comment]
Hello,
should I open a new request or could you review the request to not reboot if you `remove` a network interface.

VMware VCD support confirmed it is a bug with 10.1 and will be fixed in 10.2.

So with VCD not 10.1 it is possible to hot remove the network interface as well.

> Well with linux I tried cold reboot was needed, that's why it was implemented as it is now. I would need to verify that API allows hot removal on latest linux release. If yes - we get question how to implement such logic and not lock to specific linux version checking...

So I assume this test was based on VCD 10.1. Since it is not needed to lock to specific linux version (only exclude a specific VCD version), it should not be a bigger problem than hot add/update.

**Comment by vbauzysvmware** [comment]
Hi @jpbuecken did you get any URL to the bug?

**Comment by jpbuecken** [comment]
> Hi @jpbuecken did you get any URL to the bug?

Hi, I have a Service Request ID, SR 20151879808. Does this help?
(I did not open the bug myself, it has been opened by a member of our team dedicated to the VCD plattform)

**Comment by vbauzysvmware** [comment]
Hi @jpbuecken, I made last minutes changes for coming release. Could you test/verify it? https://github.com/vmware/terraform-provider-vcd/pull/568. P.s. it's based on other PR, so shows more changes.

**Comment by jpbuecken** [comment]
> Hi @jpbuecken, I made last minutes changes for coming release. Could you test/verify it? #568. P.s. it's based on other PR, so shows more changes.

Does the PR include https://github.com/vmware/terraform-provider-vcd/pull/556 ? In that case I only need to build and test with one version :-)

**Comment by vbauzysvmware** [comment]
> > Hi @jpbuecken, I made last minutes changes for coming release. Could you test/verify it? #568. P.s. it's based on other PR, so shows more changes.
> 
> Does the PR include #556 ? In that case I only need to build and test with one version :-)

sorry, #556 not included

**Comment by Didainius** [comment]
> > > Hi @jpbuecken, I made last minutes changes for coming release. Could you test/verify it? #568. P.s. it's based on other PR, so shows more changes.
> > 
> > 
> > Does the PR include #556 ? In that case I only need to build and test with one version :-)
> 
> sorry, #556 not included

It is included now :)

**Comment by vbauzysvmware** [comment]
> > > > Hi @jpbuecken, I made last minutes changes for coming release. Could you test/verify it? #568. P.s. it's based on other PR, so shows more changes.
> > > 
> > > 
> > > Does the PR include #556 ? In that case I only need to build and test with one version :-)
> > 
> > 
> > sorry, #556 not included
> 
> It is included now :)

Yes, everything now included :)

**Comment by lvirbalas** [comment]
@jpbuecken Would you able to try this out and confirm on your side? We are aiming to finish merging what goes into 3.0 this Friday. Thanks!

**Comment by jpbuecken** [comment]
I'm working on it, will test #568 today.

**Comment by jpbuecken** [comment]
Just tested #568 with VCD 10.0, terraform 0.13 , and GuestOS sles15_Guest64.

Worked for me
