### ISSUE TITLE
Add support to configure SSL VPN PLUS

### ISSUE THREAD

**Issue by vfuyong** [vmware/terraform-provider-vcd#398]
Currently there is no resource to configure SSL VPN PLUS for clients. 

### Terraform Version
2.5.0

**Comment by lvirbalas** [comment]
@vfuyong please add more details on the requests and screen shots of the corresponding feature in the UI.

BTW, which company are you coming from?

**Comment by nilic** [comment]
I'll try to add some more info at least on the SSL VPN Plus feature.

In order for it to be visible in the UI:

- Edge GW needs to be advanced

- Org needs to be assigned the appropriate Remote Access and SSL VPN Organization Rights: https://blogs.vmware.com/cloudprovider/2017/05/enabling-organization-rights-in-vcloud-director.html

- Org user also needs to have assigned the appropriate Remote Access and SSL VPN Organization Rights (eg. Organization Administrator does not have these rights by default)

Then SSL VPN Plus tab is available by selecting the Edge Gateway and Configure Services option:

![sslvpn1](https://user-images.githubusercontent.com/6827325/69581853-94612080-0fd7-11ea-8d23-21d93f288466.png)

![sslvpn2](https://user-images.githubusercontent.com/6827325/69581871-9c20c500-0fd7-11ea-98a9-2fd185174390.png)

![sslvpn3](https://user-images.githubusercontent.com/6827325/69581879-a17e0f80-0fd7-11ea-9ae8-6a90b04ab471.png)

etc.

**Comment by Didainius** [comment]
NSX-V is not getting time investment, and we support NSX-T VPN tunnels (the only thing available so far)
