### ISSUE TITLE
Cleanup HCL examples in website as per new Terraform syntax

### ISSUE THREAD

**Issue by Didainius** [vmware/terraform-provider-vcd#417]
Terraform syntax previously required quoted variables to refer items in such way:
```hcl
some_value = "${resource.name.field}"
```

Terraform now fires a lot of warning message when using such quoted variables as the new syntax requires it to be as such:

```hcl
some_value = resource.name.field
```

Our website documentation still has a lot of examples written in older syntax and this issue is set to track work of cleanup.

**Comment by Didainius** [comment]
Partly related - #409 (because it is documentation improvement)

**Comment by vladdoster** [comment]
@Didainius I'll take this. Preparing PR now.

**Comment by vladdoster** [comment]
@Didainius Changes made in PR #705
