### ISSUE TITLE
Change vApp ownership

### ISSUE THREAD

**Issue by danonh** [vmware/terraform-provider-vcd#425]
Hi all,
Is there an option to change vApp ownership using Terraform vcd provider? If it's not implemented yet, are there any plans to include that functionality in near future?
Regards,

**Comment by lvirbalas** [comment]
Hi @danonh 

Would you propose how would you like to see the HCL configuration for this? I mean a snippet of a .tf file.

Happy Holidays!

**Comment by Didainius** [comment]
This was implemented - https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_access_control
