### ISSUE TITLE
Add support for additional arguments in the vcd_edgegateway_vpn resource

### ISSUE THREAD

**Issue by nilic** [vmware/terraform-provider-vcd#440]
Hi guys,

there are a few options available in the UI when creating a new Edge Gateway VPN which would be useful to have in the `vcd_edgegateway_vpn` resource.

These options are:

- whether the VPN is enabled or not
- whether Perfect Forward Secrecy (PFS) is enabled
- which Diffie-Helman Group is used

Here are screenshots for these options from the (HTML5) UI in vCD 9.5:

![image](https://user-images.githubusercontent.com/6827325/72911018-ac37f500-3d39-11ea-9971-e4b0c7ccf3de.png)

![image](https://user-images.githubusercontent.com/6827325/72911580-9b3bb380-3d3a-11ea-8789-5c4c43a99650.png)

Thanks!

**Comment by nilic** [comment]
Also, what's currently missing to be able to provide end-to-end IPSec VPN support in Terraform, is an option to enable IPSec VPN service on the Edge Gateway. This could be done via an argument in the `vcd_edgegateway` resource (similarly to what was done with Load Balancing through `lb_enabled`), but since IPSec VPN service has additional global settings (logging, PSK etc), maybe it would make sense to implement this in a new resource (similarly to `vcd_nsxv_dhcp_relay`).

**Comment by Didainius** [comment]
related to VPN as well https://github.com/terraform-providers/terraform-provider-vcd/issues/398

**Comment by thundertaker** [comment]
Hello! I also need parameters described in the issue description. Also, I need even more additional settings:

* `ike_option` (represented as `ikeOption` in NSX REST API)
* `digest_algorithm` (represented as `digestAlgorithm` in NSX REST API)

**Comment by Didainius** [comment]
NSX-V is not getting time investment, and we support NSX-T VPN tunnels (the only thing available so far)
