### ISSUE TITLE
vcd_vapp_vm: Add option to manage memory and vCPU hot add

### ISSUE THREAD

**Issue by jpbuecken** [vmware/terraform-provider-vcd#452]
Similar to
`expose_hardware_virtualization`
the "Hardware" Section of a VM has two more checkboxes.
In the H5 of VCD 10 they are called "Memory hot add" and "Virtual CPU hot add".

Please add parameter to vcd_vapp_vm to change those options.

### Terraform Version
Terraform v0.12.18
+ provider.null v2.1.2
+ provider.vcd v2.7.0-66b85e48d7e6c1fee41a2b26f1f4ac0ccc57e1e0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "instance" {
  lifecycle {
    prevent_destroy = "true"
  }
  # we do not reference via vcd_vapp.vapp.name
  # if we do, a rename of vapp will re-create the vm
  # (terraform engine will add the reference to the dependency tree)
  depends_on = [vcd_vapp.vapp]

  name          = var.hostname
  computer_name = var.hostname
  vapp_name     = var.hostname
  catalog_name  = var.image_catalog
  template_name = var.image_string
  cpus          = var.cpu
  cpu_cores     = var.core
  memory        = var.ram
  # Power on after preboot guestcustomization settings set via null resource below
  power_on = true

  # suggested hcl:
  memory_hot_add = true
  virtual_cpu_hot_add = true

  network {
    type               = "org"
    name               = var.network
    ip_allocation_mode = var.private_ip == null ? "POOL" : "MANUAL"
    ip                 = var.private_ip
    is_primary         = true
  }
}
```

### Expected Behavior
Change Memory/CPU hot add feature via terraform

### Actual Behavior
Option not provided by vcd provider

**Comment by lvirbalas** [comment]
In UI:

<img width="801" alt="Screenshot 2020-06-30 at 10 49 35" src="https://user-images.githubusercontent.com/11330689/86098887-6852d400-babf-11ea-960a-a4a278f2e888.png">

**Comment by Didainius** [comment]
@jpbuecken,
Just double checking to avoid confusion - am I correct that your end goal is to be able to update CPU/memory config in the resource without powering off the VM when the following are set to true:
```hcl
  memory_hot_add = true
  cpu_hot_add = true
```

**Comment by jpbuecken** [comment]
> @jpbuecken,
> Just double checking to avoid confusion - am I correct that your end goal is to be able to update CPU/memory config in the resource without powering off the VM when the following are set to true:
> 
> ```terraform
>   memory_hot_add = true
>   cpu_hot_add = true
> ```

Exactly!

So we have two issues here:
1) Enable hot add for cpu and memory via terraform (this issue)
2) Perform a cpu add and/or memory add via terraform without shutdown via terraform, if hot add is enabled correspondingly

For part 2 I'm goign to open a second issue. It should be independent how hot add has been enabled (via UI, derived from catalog item or via terraform). In all cases the change of cpu or memory in via terraform should perform a online change

**Comment by jpbuecken** [comment]
The hot add function can be set via UI or derived from a catalog template. 
We already provide catalog items with hot add enabled.
This is just a backup if we have a catalog item without active hot add.

Since we have a workaround for this issue, the second part is more important.
I opened an extra issue for that here
https://github.com/terraform-providers/terraform-provider-vcd/issues/531

Our customers try to avoid any downtime if possible. Every solution that does not require a reboot will help us.

**Comment by vbauzysvmware** [comment]
PR is merged. Anyone interested can test ;-)

**Comment by jpbuecken** [comment]
Tested. Works for me.
