### ISSUE TITLE
vcd_edgegateway_vpn - id for vpn tunnel not unique

### ISSUE THREAD

**Issue by username-is-already-taken2** [vmware/terraform-provider-vcd#460]
Hi there,

I noticed today when using 'vcd_edgegateway_vpn' resource to define an additional vpn tunnel that terraform wasn't adding the second tunnel it was amending the vpn tunnel that was already there.

It looks like the resource is defaulting to the edge gateway name as the ID for each tunnel.
![image](https://user-images.githubusercontent.com/13700297/75444527-823aa980-595b-11ea-9c29-646979c441b8.png)

I'm not very good with go to confirm that within the code but I thought I would mention it.

### Terraform Version
Terraform v0.12.20
+ provider.vcd v2.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_edgegateway_vpn

**Comment by Didainius** [comment]
Yes, you may be right and there are some tasks  which I am cross-referencing other VPN related tasks - #398, #440

**Comment by thundertaker** [comment]
Also confirming the issue, now it's not possible to create more than one instance of `vcd_edgegateway_vpn` resource using the same edge gateway.

**Comment by kbzyx** [comment]
Also confirming the issue, from the picture you can see that we have 2 different vpn's in the state file, but since they have the same ID only one of them is created. 

![same_id](https://user-images.githubusercontent.com/45608706/86914180-227db780-c120-11ea-8134-e8e97443de7b.png)

Every other apply will try to destroy current vpn and replace it with the one which is not created.

**Comment by hmilkovi** [comment]
Also confirming the issue

**Comment by total13** [comment]
Additionaly, seems Diffie Hellman cannot be adjusted via terraform, if that can be also added

**Comment by igorgnip-gmail** [comment]
> Also confirming the issue, now it's not possible to create more than one instance of `vcd_edgegateway_vpn` resource using the same edge gateway.

I am trying to understand - is this a 1 IPSEC tunnel per edge gateway, or there can be more than one but each must have unique ID ?

Thanks

**Comment by igorgnip-gmail** [comment]
Also, while deploying terraform defined vpn tunnel, even manually configured tunnels (which had same local id) were deleted.

**Comment by kbzyx** [comment]
> > Also confirming the issue, now it's not possible to create more than one instance of `vcd_edgegateway_vpn` resource using the same edge gateway.
> 
> I am trying to understand - is this a 1 IPSEC tunnel per edge gateway, or there can be more than one but each must have unique ID ?
> 
> Thanks

Hello, these are 2 completely different VPN tunnels, which are having same ID in the terraform state file, which leads to missconfiguration in the virtual cloud director.

**Comment by Didainius** [comment]
We are not investing into NSX-V anymore, but NSX-T has it's own resource for VPN
