### ISSUE TITLE
Unable to create an Org VDC Edge Gateway in vCloud director 10.0.0.15449638, NSX-T 2.5.1.0.0.15314288

### ISSUE THREAD

**Issue by vlogic** [vmware/terraform-provider-vcd#486]
We are unable to create an Org VDC Edge Gateway in vCloud director 10.0.0.15449638 with NSX-T 2.5.1.0.0.15314288 via terraform. We get an http 500 server error.

### Terraform Version
Terraform v0.12.24
+ provider.vcd v2.7.0

Terraform v0.12.24
+ provider.vcd v2.8.0 (https://github.com/Didainius/terraform-provider-vcd/tree/test-pvdc-nsxt-fix)

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

```

# Connect VMware vCloud Director Provider
provider "vcd" {
  user                 = var.vcd_user
  password             = var.vcd_pass
  org                  = "System"
  url                  = var.vcd_url
  max_retry_timeout    = var.vcd_max_retry_timeout
  allow_unverified_ssl = var.vcd_allow_unverified_ssl
}

resource "vcd_edgegateway" "egw" {
  org = var.org_name
  vdc = var.vdc_name
  name                    = "VDC-network"
  description             = "edge gateway for network"
  configuration           = "compact"
  advanced                = true

  external_network {
    name = "nsx-t"
    subnet {
      gateway               = "10.10.10.1"
      netmask               = "255.255.255.192"
      use_for_default_route = true

      suballocate_pool {
        start_address = "10.10.10.2"
        end_address   = "10.10.10.10"
      }
    }
  }
}
```

### Debug Output
TRACE gist https://gist.github.com/vlogic/c99635ef520eceaba8e8e2d757ec9e3f

Terraform will perform the following actions:

  # vcd_edgegateway.egw will be created
  + resource "vcd_edgegateway" "egw" {
      + advanced                        = true
      + configuration                   = "compact"
      + default_external_network_ip     = (known after apply)
      + default_gateway_network         = (known after apply)
      + description                     = "edge gateway for network"
      + distributed_routing             = false
      + external_network_ips            = (known after apply)
      + fw_default_rule_action          = "deny"
      + fw_default_rule_logging_enabled = false
      + fw_enabled                      = true
      + ha_enabled                      = false
      + id                              = (known after apply)
      + lb_acceleration_enabled         = false
      + lb_enabled                      = false
      + lb_logging_enabled              = false
      + lb_loglevel                     = "info"
      + name                            = "VDC-network"
      + org                             = "demo"
      + use_default_route_for_dns_relay = (known after apply)
      + vdc                             = "demo"

      + external_network {
          + enable_rate_limit   = false
          + incoming_rate_limit = 0
          + name                = "nsx-t"
          + outgoing_rate_limit = 0

          + subnet {
              + gateway               = "10.10.10.1"
              + netmask               = "255.255.255.192"
              + use_for_default_route = true

              + suballocate_pool {
                  + end_address   = "10.10.10.2"
                  + start_address = "10.10.10.10"
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vcd_edgegateway.egw: Creating...

Error: error creating edge gateway: error instantiating a new Edge Gateway: API Error: 500: [ d4fa550a-3ee8-4ee5-a807-905002af50c0 ] class java.lang.NullPointerException

  on main.tf line 11, in resource "vcd_edgegateway" "egw":
  11: resource "vcd_edgegateway" "egw" {

### Expected Behavior
What should have happened?
An VDC edge gateway should be created in vCloud

### Actual Behavior
What actually happened?
Nothing is created

### Steps to Reproduce
terraform apply

### Important Factoids
vCloud director 10.0.0.15449638
NSX-T 2.5.1.0.0.15314288
Terraform v0.12.24
+ provider.vcd v2.7.0
Terraform v0.12.24
+ provider.vcd v2.8.0 (https://github.com/Didainius/terraform-provider-vcd/tree/test-pvdc-nsxt-fix)

**Comment by Didainius** [comment]
Hello @vlogic,
Thanks for the issue. We are yet to catch up on NSX-T. The PR mentioned above so far is to make pPdc lookup possible.
Still, could you enable logging with https://www.terraform.io/docs/providers/vcd/index.html#logging and it should generate a go-vcloud-director log which should dig into details of API calls and errors ir proposes. Feel free to double checking if you need to mask any data (like hostnames, etc). Password should not be there by default.

**Comment by pasikarkkainen** [comment]
Any news related to adding NSX-T support?

**Comment by lvirbalas** [comment]
NSX-T support will be coming this year. And, given the size of effort, it most probably will come incrementally through more than one release.

**Comment by Didainius** [comment]
Org Vdc will support NSX-T in 3.0.0 version
