### ISSUE TITLE
vdc_lb_server_pool member port should not required

### ISSUE THREAD

**Issue by simdevmat** [vmware/terraform-provider-vcd#490]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_lb_server_pool

### Terraform code
```
resource "vcd_lb_server_pool" "servers" {
  org          = var.org_name
  vdc          = var.vdc
  edge_gateway = var.edge_name

  name                 = var.name
  description          = var.desc
  algorithm            = var.alg
  enable_transparency  = "true"

  dynamic "member" {
    for_each = var.members
    content {
      condition       = "enabled"
      name            = member.key
      ip_address      = member.value
      monitor_port    = 443
      weight          = 1
    }
  }
}
```
### Panic Output
```
Error: Missing required argument

  on .terraform/modules/firewall/main.tf line 191, in resource "vcd_lb_server_pool" "infra-servers":
 191:     content {

The argument "port" is required, but no definition was found.
```

### Expected Behavior
Member port should not be required, as proven using vCloud Director Console. 

Prevents us from using multiple port virtual servers

### Actual Behavior
Member port is required

### Steps to Reproduce
1. `terraform validate`

### Important Factoids
N/A

### References
N/A

**Comment by Didainius** [comment]
Not investing to NSX-V at the moment.
