### ISSUE TITLE
Error creating VMs using module

### ISSUE THREAD

**Issue by kelt1k** [vmware/terraform-provider-vcd#495]
Hi there,

I'm trying to use terraform for managing my vm via module and have an error after creation of first VM:
```
[VM creation] error adding VM: error instantiating a new VM: API Error: 500: [ 262787f0-6295-4984-b6bb-08ceb0ecd61c ] Unable to perform this action. Contact your cloud administrator.

  on ../vm_create_vcloud/main.tf line 14, in resource "vcd_vapp_vm" "vm":
  14: resource "vcd_vapp_vm" "vm" {
```
It's seams that problem is with terraform trying to use the same vcd_internal_disk for the next VM

### Terraform Version
Terraform v0.12.24
+ provider.vcd v2.8.0

### Affected Resource(s)
- vcd_vapp_vm
- vcd_internal_disk

### Terraform Configuration Files
```base main.tf
resource "vcd_vm_internal_disk" "disk1" {
  org          = var.vcd_org
  vdc          = var.vcd_vdc
  vm_name      = vcd_vapp_vm.vm.name
  vapp_name    = var.vapp_name
  size_in_mb   = var.internal_disk_size
  bus_type     = var.internal_disk_bus_type
  bus_number   = 0
  unit_number  = 1
  allow_vm_reboot = true
  depends_on      = [vcd_vapp_vm.vm]
}

resource "vcd_vapp_vm" "vm" {
  org           = var.vcd_org
  vdc           = var.vcd_vdc
  vapp_name     = var.vapp_name
  name          = var.vm_name
  catalog_name  = var.catalog_name
  template_name = var.template_name
  memory        = var.vm_memory
  cpus          = var.vm_cpu_count
  cpu_cores     = var.vm_core_count_cpu
 
  network {
    type               = var.network_type
    name               = var.network_name
    ip_allocation_mode = var.ip_allocation_mode
    is_primary         = var.is_primary
    ip                 = var.vm_primary_ip
  }
}

```infrastructure main.tf
module "kuber-np-c-mon1" {
  source = "../vm_create_vcloud"

  vm_name = "c-mon1"
  vm_cpu_count = 2
  vm_memory = 2048
  internal_disk_size = 100240
  vm_primary_ip = "192.168.14.201"

  vcd_user = var.vcd_user
  vcd_url = var.vcd_url
  vcd_pass = var.vcd_pass
  vcd_token = var.vcd_token
}

module "kuber-np-c-mon2" {
  source = "../vm_create_vcloud"

  vm_name = "c-mon2"
  vm_cpu_count = 2
  vm_memory = 2048
  internal_disk_size = 100240
  vm_primary_ip = "192.168.14.202"

  vcd_user = var.vcd_user
  vcd_url = var.vcd_url
  vcd_pass = var.vcd_pass
  vcd_token = var.vcd_token
}

module "kuber-np-c-mon3" {
  source = "../vm_create_vcloud"

  vm_name = "c-mon3"
  vm_cpu_count = 2
  vm_memory = 2048
  internal_disk_size = 100240
  vm_primary_ip = "192.168.14.203"

  vcd_user = var.vcd_user
  vcd_url = var.vcd_url
  vcd_pass = var.vcd_pass
  vcd_token = var.vcd_token
}

module "kuber-np-c-osd1" {
  source = "../vm_create_vcloud"

  vm_name = "c-osd1"
  vm_cpu_count = 2
  vm_memory = 4096
  internal_disk_size = 250000
  vm_primary_ip = "192.168.14.221"

  vcd_user = var.vcd_user
  vcd_url = var.vcd_url
  vcd_pass = var.vcd_pass
  vcd_token = var.vcd_token
}

module "kuber-np-c-osd2" {
  source = "../vm_create_vcloud"

  vm_name = "c-osd2"
  vm_cpu_count = 2
  vm_memory = 4096
  internal_disk_size = 250000
  vm_primary_ip = "192.168.14.222"

  vcd_user = var.vcd_user
  vcd_url = var.vcd_url
  vcd_pass = var.vcd_pass
  vcd_token = var.vcd_token
}

module "kuber-np-c-osd3" {
  source = "../vm_create_vcloud"

  vm_name = "c-osd3"
  vm_cpu_count = 2
  vm_memory = 4096
  internal_disk_size = 250000
  vm_primary_ip = "192.168.14.223"

  vcd_user = var.vcd_user
  vcd_url = var.vcd_url
  vcd_pass = var.vcd_pass
  vcd_token = var.vcd_token
}

module "kuber-np-c-mds1" {
  source = "../vm_create_vcloud"

  vm_name = "c-mds1"
  vm_cpu_count = 2
  vm_memory = 4096
  internal_disk_size = 100000
  vm_primary_ip = "192.168.14.211"

  vcd_user = var.vcd_user
  vcd_url = var.vcd_url
  vcd_pass = var.vcd_pass
  vcd_token = var.vcd_token
}
```

### Expected Behavior
All VMs described in plan should appear

### Actual Behavior
Error after creating first VM

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
vCloud Director version: 9.7.0.14534864 Fri Aug 30 14:29:55 EEST 2019

**Comment by Didainius** [comment]
Hello,
Thanks for the issue. Would you be able to turn on logging by setting these environment variables and running apply once more:
```hcl
export TF_LOG_PATH=tf.log            
export TF_LOG=trace                  
export GOVCD_LOG_FILE=go-vcloud-director.log
export GOVCD_LOG=true     
```
If you are on windows it should be `SET` instead of `export` IIRC.

Double check that there is nothing you want to hide from the logs and share it here.

Thanks!

**Comment by kelt1k** [comment]
@Didainius 
logs are here https://github.com/kelt1k/terraform_issue/blob/master/go-vcloud-director.log
https://github.com/kelt1k/terraform_issue/blob/master/tf.log

**Comment by vbauzysvmware** [comment]
Hi @kelt1k,

Could you also check what error is showed in vCD Recent tasks? Maybe there is more details there.

Thank you.

**Comment by kelt1k** [comment]
hi @Didainius unfortunately there no any errors in vCD UI corresponding to this actions ( 
actually the one VM creating and the all next fails. 
If I try to use it this plan again and again - finally all VM will be created but it's not my expected behavior

**Comment by kelt1k** [comment]
I think the problem can be in internal dick id, because when I run terraform plan against my already created  infrastructure i get this output 
`module.kuber-np-c-osd2.vcd_vapp_vm.vm: Refreshing state... [id=urn:vcloud:vm:779312b0-cda0-4996-bf1b-98dd9428bc84]
module.kuber-np-c-mon3.vcd_vapp_vm.vm: Refreshing state... [id=urn:vcloud:vm:e8663ac9-0f2d-4dc3-bbc3-70691d510f51]
module.kuber-np-c-mon1.vcd_vapp_vm.vm: Refreshing state... [id=urn:vcloud:vm:f0b75b1d-f59b-47ae-b610-0a638250f45d]
module.kuber-np-c-mon2.vcd_vapp_vm.vm: Refreshing state... [id=urn:vcloud:vm:2a94231e-a5d5-488c-8f2f-dffde10b7828]
module.kuber-np-c-osd1.vcd_vapp_vm.vm: Refreshing state... [id=urn:vcloud:vm:7bedf2d3-cb84-405a-9a6d-4a7497f3bc30]
module.kuber-np-c-osd3.vcd_vapp_vm.vm: Refreshing state... [id=urn:vcloud:vm:33cc8018-a0e5-40f6-9673-a67d173900fe]
module.kuber-np-c-mds1.vcd_vapp_vm.vm: Refreshing state... [id=urn:vcloud:vm:9bd3ed21-b4bc-4612-adda-754e3127498b]
module.kuber-np-c-mds1.vcd_vm_internal_disk.disk1: Refreshing state... [id=2001]
module.kuber-np-c-osd3.vcd_vm_internal_disk.disk1: Refreshing state... [id=2001]
module.kuber-np-c-osd2.vcd_vm_internal_disk.disk1: Refreshing state... [id=2001]
module.kuber-np-c-mon2.vcd_vm_internal_disk.disk1: Refreshing state... [id=2001]
module.kuber-np-c-osd1.vcd_vm_internal_disk.disk1: Refreshing state... [id=2001]
module.kuber-np-c-mon1.vcd_vm_internal_disk.disk1: Refreshing state... [id=2001]
module.kuber-np-c-mon3.vcd_vm_internal_disk.disk1: Refreshing state... [id=2001]`

**Comment by Didainius** [comment]
@kelt1k,
I see you have quite a few modules here which makes it a bit troublesome to troubleshoot and replicate the error. Maybe you are able to isolate this problem to a very minimal example without modules and just a few resources which could ease our chances of replication?
That way we could trigger the error on our end and troubleshoot it

**Comment by Didainius** [comment]
@kelt1k , 
I am closing this as it has not had response for a year+. Feel free to reopen if you have a small example replicating it.
