### ISSUE TITLE
vcd_org_vdc storageprofile 

### ISSUE THREAD

**Issue by kozy** [vmware/terraform-provider-vcd#497]
Hi there,

when using the vcd_org_vdc data, there are `storage_profile` fields. In there is a `limit` attribute, but to see how much is available at some point I am also looking for a `used` field. Is this field missing or how can I get that information?

Thank you!

**Comment by Didainius** [comment]
Hello @kozy,
Looking at the code definition I am afraid this field is not available at the moment: https://github.com/terraform-providers/terraform-provider-vcd/blob/master/vcd/datasource_vcd_org_vdc.go#L99-L127

**Comment by kozy** [comment]
I see. Is it available in the vcd api, at the same place it fetches limit? I've been trying to wrap my head around the vcd api but am afraid it needs to be individually fetched, though I could not find where. Is it easy to give some hints on the top of your head? Maybe I can make pull request then

**Comment by vbauzysvmware** [comment]
Well it's not easy when we fix this we will need to handle this situation also. https://github.com/terraform-providers/terraform-provider-vcd/issues/461. Short investigation showed that handling storage profiles will need separate API calls. So govcd needs to implement such functionality first.

**Comment by kozy** [comment]
In that case I'll leave it for now and wait patiently. Thanks for your help @vbauzysvmware

**Comment by vbauzysvmware** [comment]
fixed and will be released in 3.1 version

**Comment by kozy** [comment]
Great, hope to test it soon. Thank you!
