### ISSUE TITLE
Issue while creating External Network with multiple IP Pools and Static IP Pools using dynamic block

### ISSUE THREAD

**Issue by sibbasriv** [vmware/terraform-provider-vcd#503]
Hi Team,

Seeing an issue while creating an External Network with multiple IP Pools and Static IP Pools. terraform apply deploys the External Network very first time but when run again, it tries to override the IP Pools and Static IP Pools dynamic block. The order of dynamic block seems to be getting changed when running terraform plan/apply.

### Terraform Version
Terraform v0.12.24
+ provider.vcd v2.8.0

### Affected Resource(s)
vcd_external_network

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```
resource "vcd_external_network" "net" {
  depends_on  = [var.dependency]
  for_each    = var.externalNetworks
  name        = each.value.portgroup_name
  description = "Provisioned: Customer External Network"
  dynamic "ip_scope" {
    for_each = each.value.ip_scopes
    //for_each = { for item in each.value.ip_scopes : index(each.value.ip_scopes, item) => item}
    content {
      gateway         = ip_scope.value.gateway
      netmask         = ip_scope.value.netmask
      dynamic "static_ip_pool" {
        for_each = ip_scope.value.static_ip_pools
        content {
          start_address = static_ip_pool.value.start_address
          end_address   = static_ip_pool.value.end_address
        }
      }
    }
  }
  vsphere_network {
    name    = each.value.portgroup_name
    type    = "DV_PORTGROUP"
    vcenter = var.vcenterEndpoint
  }
}
```

### Expected Behavior
terraform plan/apply should not show any outstanding change.

### Actual Behavior

    -/+ resource "vcd_external_network" "net" {
        description                        = "Provisioned: Customer External Network"
      ~ id                                 = "urn:vcloud:network:5ce92091-33c9-4e7e-91e1-f16641baffb3" -> (known after apply)
        name                               = "colo-smdt-vlan-717"
        retain_net_info_across_deployments = false
      ~ ip_scope {
          ~ gateway = "10.6.6.1" -> "10.5.5.1" # forces replacement
            netmask = "255.255.255.0"
          ~ static_ip_pool {
              ~ end_address   = "10.6.6.12" -> "10.5.5.22" # forces replacement
              ~ start_address = "10.6.6.10" -> "10.5.5.20" # forces replacement
            }
        }
      ~ ip_scope {
          ~ gateway = "10.5.5.1" -> "10.6.6.1" # forces replacement
            netmask = "255.255.255.0"
          ~ static_ip_pool {
              ~ end_address   = "10.5.5.22" -> "10.6.6.12" # forces replacement
              ~ start_address = "10.5.5.20" -> "10.6.6.10" # forces replacement
            }
        }
        vsphere_network {
            name    = "colo-smdt-vlan-717"
            type    = "DV_PORTGROUP"
            vcenter = "labgvcd-vcenter1.edisonqa.sgns.net"
        }
    }

       
    -/+ resource "vcd_external_network" "net" {
        description                        = "Provisioned: Customer External Network"
      ~ id                                 = "urn:vcloud:network:b94c16d1-acc4-4f18-9b88-957f24f77c31" -> (known after apply)
        name                               = "inet-smdt-vlan-515"
        retain_net_info_across_deployments = false
      ~ ip_scope {
          ~ gateway = "10.2.2.1" -> "10.1.1.1" # forces replacement
            netmask = "255.255.255.0"
          ~ static_ip_pool {
              ~ end_address   = "10.2.2.12" -> "10.1.1.22" # forces replacement
              ~ start_address = "10.2.2.10" -> "10.1.1.20" # forces replacement
            }
        }
      ~ ip_scope {
          ~ gateway = "10.1.1.1" -> "10.2.2.1" # forces replacement
            netmask = "255.255.255.0"
          ~ static_ip_pool {
              ~ end_address   = "10.1.1.22" -> "10.2.2.12" # forces replacement
              ~ start_address = "10.1.1.20" -> "10.2.2.10" # forces replacement
            }
        }
        vsphere_network {
            name    = "inet-smdt-vlan-515"
            type    = "DV_PORTGROUP"
            vcenter = "labgvcd-vcenter1.edisonqa.sgns.net"
        }
    }

**Comment by sibbasriv** [comment]
> Hi Team,
> 
> Seeing an issue while creating an External Network with multiple IP Pools and Static IP Pools. terraform apply deploys the External Network very first time but when run again, it tries to override the IP Pools and Static IP Pools dynamic block. The order of dynamic block seems to be getting changed when running terraform plan/apply.
> 
> ### Terraform Version
> Terraform v0.12.24
> 
> * provider.vcd v2.8.0
> 
> ### Affected Resource(s)
> vcd_external_network
> 
> If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
> 
> ### Terraform Configuration Files
> resource "vcd_external_network" "net" {
> depends_on = [var.dependency]
> for_each = var.externalNetworks
> name = each.value.portgroup_name
> description = "Provisioned: Customer External Network"
> dynamic "ip_scope" {
> for_each = each.value.ip_scopes
> //for_each = { for item in each.value.ip_scopes : index(each.value.ip_scopes, item) => item}
> content {
> gateway = ip_scope.value.gateway
> netmask = ip_scope.value.netmask
> dynamic "static_ip_pool" {
> for_each = ip_scope.value.static_ip_pools
> content {
> start_address = static_ip_pool.value.start_address
> end_address = static_ip_pool.value.end_address
> }
> }
> }
> }
> vsphere_network {
> name = each.value.portgroup_name
> type = "DV_PORTGROUP"
> vcenter = var.vcenterEndpoint
> }
> }
> 
> ### Expected Behavior
> terraform plan/apply should not show any outstanding change.
> 
> ### Actual Behavior
> -/+ resource "vcd_external_network" "net" {
> description = "Provisioned: Customer External Network"
> ~ id = "urn:vcloud:network:5ce92091-33c9-4e7e-91e1-f16641baffb3" -> (known after apply)
> name = "colo-smdt-vlan-717"
> retain_net_info_across_deployments = false
> 
> ```
>   ~ ip_scope {
>       ~ gateway = "10.6.6.1" -> "10.5.5.1" # forces replacement
>         netmask = "255.255.255.0"
> 
>       ~ static_ip_pool {
>           ~ end_address   = "10.6.6.12" -> "10.5.5.22" # forces replacement
>           ~ start_address = "10.6.6.10" -> "10.5.5.20" # forces replacement
>         }
>     }
>   ~ ip_scope {
>       ~ gateway = "10.5.5.1" -> "10.6.6.1" # forces replacement
>         netmask = "255.255.255.0"
> 
>       ~ static_ip_pool {
>           ~ end_address   = "10.5.5.22" -> "10.6.6.12" # forces replacement
>           ~ start_address = "10.5.5.20" -> "10.6.6.10" # forces replacement
>         }
>     }
> 
>     vsphere_network {
>         name    = "colo-smdt-vlan-717"
>         type    = "DV_PORTGROUP"
>         vcenter = "labgvcd-vcenter1.edisonqa.sgns.net"
>     }
> }
> ```
> 
> -/+ resource "vcd_external_network" "net" {
> description = "Provisioned: Customer External Network"
> ~ id = "urn:vcloud:network:b94c16d1-acc4-4f18-9b88-957f24f77c31" -> (known after apply)
> name = "inet-smdt-vlan-515"
> retain_net_info_across_deployments = false
> 
> ```
>   ~ ip_scope {
>       ~ gateway = "10.2.2.1" -> "10.1.1.1" # forces replacement
>         netmask = "255.255.255.0"
> 
>       ~ static_ip_pool {
>           ~ end_address   = "10.2.2.12" -> "10.1.1.22" # forces replacement
>           ~ start_address = "10.2.2.10" -> "10.1.1.20" # forces replacement
>         }
>     }
>   ~ ip_scope {
>       ~ gateway = "10.1.1.1" -> "10.2.2.1" # forces replacement
>         netmask = "255.255.255.0"
> 
>       ~ static_ip_pool {
>           ~ end_address   = "10.1.1.22" -> "10.2.2.12" # forces replacement
>           ~ start_address = "10.1.1.20" -> "10.2.2.10" # forces replacement
>         }
>     }
> 
>     vsphere_network {
>         name    = "inet-smdt-vlan-515"
>         type    = "DV_PORTGROUP"
>         vcenter = "labgvcd-vcenter1.edisonqa.sgns.net"
>     }
> }
> ```

**Comment by sibbasriv** [comment]
terraform.tfvars.json input variable section for external network

```
"internet": {
        "active_uplinks": "Active-lag",
        "ip_scopes": [
          {
            "edgeIP": "10.1.1.21",
            "gateway": "10.1.1.1",
            "netmask": "255.255.255.0",
            "static_ip_pools": [
              {
                "end_address": "10.1.1.22",
                "start_address": "10.1.1.20"
              }
            ],
            "suballocate_pool": [
              {
                "end_address": "10.1.1.22",
                "start_address": "10.1.1.21"
              }
            ]
          },
          {
            "edgeIP": "10.2.2.11",
            "gateway": "10.2.2.1",
            "netmask": "255.255.255.0",
            "static_ip_pools": [
              {
                "end_address": "10.2.2.12",
                "start_address": "10.2.2.10"
              }
            ],
            "suballocate_pool": [
              {
                "end_address": "10.2.2.12",
                "start_address": "10.2.2.11"
              }
            ]
          }
        ],
        "number_of_ports": 128,
        "portgroup_name": "vlan-test",
        "portgroup_vlan": 515,
        "standby_uplinks": ""
      }
```

**Comment by sibbasriv** [comment]
What I have observed is, the order of IP Scope ("ip_scope") is reverse in the terraform state file and when I run plan/apply the second time, Terraform detects it as a change for both the IP Scopes. 
I have also observed the same issue when having multiple Static IP Pool "static_ip_pool" under IP Scope ("ip_scope").

**Comment by sibbasriv** [comment]
Please advise a workaround. Thanks!

**Comment by Didainius** [comment]
Hello @sibbasriv ,
This is related to #395 which we haven't tackled yet. In the meantime could you try using `ignore_changes` as documented in Terraform page: https://www.terraform.io/docs/configuration/resources.html#ignore_changes

**Comment by Didainius** [comment]
I am closing this in favor of #395 as it is the main issue.
