### ISSUE TITLE
vcd_vapp_vm: network: Add connected attribute

### ISSUE THREAD

**Issue by jpbuecken** [vmware/terraform-provider-vcd#521]
Hello,
the VCD allows you to add a network adapter to a VM, but do not connect the network yet.
(The interface does not have a link inside the operating system).

This is missing  for network adapter defined in vcd_vapp_vm

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "instance" {
[...]

  network {
    type               = "org"
    name               = "mynetwork"
    ip_allocation_mode = "POOL"
    connected  = false
  }
}

```

In UI, this setting is here, in Details of a VM:

![image](https://user-images.githubusercontent.com/38046041/85433960-8f704980-b585-11ea-9377-108c32e76ec0.png)

**Comment by lvirbalas** [comment]
And, of course, add a test for this when implementing.

**Comment by vbauzysvmware** [comment]
Hi @jpbuecken 
I merged to master this feature so if you eager, you can check ;-)

**Comment by jpbuecken** [comment]
Nice work! Did not test it yet. Our use case are RHEL8 based systems (CentOS8), and the network manager does automatically configure DHCP on connected interfaces. But our test list to integrate CentOS8 in VCD is long and a bigger task.

Hopefully some other features may reach master, maybe https://github.com/terraform-providers/terraform-provider-vcd/issues/509 :-)  Then I may test it altogether

**Comment by vbauzysvmware** [comment]
Well #509 is in progress, but still will take some time to publish. #536 is published already.

**Comment by jpbuecken** [comment]
Tested. Works for me.

**Comment by vbauzysvmware** [comment]
> Tested. Works for me.

thank you ;-)

**Comment by jpbuecken** [comment]
Hi, found a bug:
If you create an interface with
```hcl
  network {
    type               = "none"
    ip_allocation_mode = "NONE"
  }
```
Then every run of terraform apply / plan want to set the connected attribute to true.
I think the default for `ip_allocation_mode = "NONE"` should be `connected = false`.

      ~ network {
            adapter_type       = "VMXNET3"
          ~ connected          = false -> true
            ip_allocation_mode = "NONE"
            is_primary         = false
            mac                = "00:50:56:01:00:d4"
            type               = "none"
        }

**Comment by vbauzysvmware** [comment]
> Hi, found a bug:
> If you create an interface with
> 
> ```terraform
>   network {
>     type               = "none"
>     ip_allocation_mode = "NONE"
>   }
> ```
> 
> Then every run of terraform apply / plan want to set the connected attribute to true.
> I think the default for `ip_allocation_mode = "NONE"` should be `connected = false`.
> 
> ```
>   ~ network {
>         adapter_type       = "VMXNET3"
>       ~ connected          = false -> true
>         ip_allocation_mode = "NONE"
>         is_primary         = false
>         mac                = "00:50:56:01:00:d4"
>         type               = "none"
>     }
> ```

It is mentioned in documentation:
* `connected` - It defines if NIC is connected or not. Network with `ip_allocation_mode=NONE` can't be connected by default, please use `connected=false` in such case.

**Comment by jpbuecken** [comment]
> It is mentioned in documentation that for "None" - connected=false is needed:
>
>connected - It defines if NIC is connected or not. Network with ip_allocation_mode=NONE can't be connected by default, > >please use connected=false in such case.

OK , Works for me
