### ISSUE TITLE
vcd_vapp_vm: Do not reboot for changes of memory and cpu, if memory and cpu hot add is active

### ISSUE THREAD

**Issue by jpbuecken** [vmware/terraform-provider-vcd#531]
For a VM, you can activate memory and cpu hot add.

In VCD UI, in Details of a VM:

![image](https://user-images.githubusercontent.com/38046041/86382933-3e034100-bc8e-11ea-9951-f4d2e07d7b66.png)

If those settings are active, increase of cpu or memroy via terraform should not reboot the VM.

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
  # We do not reference via vcd_vapp.vapp.name
  #    if we do, a rename of vapp will re-create the resource
  # Add id in a constraint to set vapp_name, such that terraform evaluate dependencies correctly
  #    otherwise this resource will not be recreated, if vapp is recreated

  vapp_name     = vcd_vapp.vapp.id == "always-not-equal" ? null : var.hostname
  name          = var.hostname
  computer_name = var.hostname
  catalog_name  = var.image_catalog
  template_name = var.image_string
  cpus          = 2
  cpu_cores     = 1
  memory        = 4096
  power_on      = true

  network {
    type               = "org"
    name               = vcd_vapp_org_network.vappnetattach.org_network_name
    adapter_type       = var.nic_controller
    ip_allocation_mode = var.private_ip == null ? "POOL" : "MANUAL"
    ip                 = var.private_ip
    is_primary         = true
  }
}
```

### Expected Behavior
Assume you increase the values of `cpus` or `memory` in the acl above. 
Then run terraform apply.
The new values should be set in VCD without a reboot / downtime.

### Actual Behavior
Currently, the VM is rebooted. Hot add is a feature you cannot use with terraform.

**Comment by vbauzysvmware** [comment]
PR is merged. Anyone interested can test ;-)

**Comment by jpbuecken** [comment]
The new parameter `prevent_update_power_off `: 
Does it refer to the new cpu_hot_add_enabled and memory_hot_add_enabled only or to other operations of vcd_vapp_vm that may require a reboot?
If it refers to the hot add parameter only,, the documentation could be more clear here.

**Comment by vbauzysvmware** [comment]
prevent_update_power_off is new field/helper field.  It works in general. It allows user to have fail safe. If something changes which and update will require power off, then this field set to True will make update to fail. So user can decide what to do - choose timing and other means.
