### ISSUE TITLE
Possible FenceMode missing for vApp network when creating a VM within a vApp

### ISSUE THREAD

**Issue by Tensibai** [vmware/terraform-provider-vcd#539]
### Terraform Version
Terraform v0.12.28
+ provider.vcd v2.9.0

### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "t1xxx99" {
  vapp_name    = "COMPANY_VM"
  name         = "t1xxx99"
  catalog_name = "CAT-COMPANY" 
  template_name = "ubuntu-16.04"
  
  network {
    type               = "vapp"
    name               = "COMPANY-L2-APP-NON-PROD-VLAN36"
    adapter_type       = "VMXNET3"
    ip_allocation_mode = "MANUAL"
    ip                 = "10.20.136.34"
    is_primary         = true
  }
}
```

### Debug Output
Pretty long so in a gist as redacted files (in a sensible manner, each replacement was matching a specific thing and is consistent along the files).

https://gist.github.com/Tensibai/d81d1c09477293a0e7eb83aad4299ea6

### Panic Output
```
Error: unable to process network configuration: unable to find vApp network COMPANY-L2-APP-NON-PROD-VLAN36: configured vApp network isn't found: COMPANY-L2-APP-NON-PROD-VLAN36

  on vm.tf line 14, in resource "vcd_vapp_vm" "t1xxx99":
  14: resource "vcd_vapp_vm" "t1xxx99" {
```
### Expected Behavior
A virtual machine should have been created in the vApp

### Actual Behavior
Terraform halt on error as it can't find the network while the network is present in the go-vcloud-director.log.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I guess my account has the vApp user role, so restricted on what I can see on the org level but haven't been able to get a confirmation by my provider yet.

### References
N/A

### My guesses
The function checking if the network given is properly a vApp network accept only NAT and isolated (FenceModeNAT and FenceModeIsolated) networks, from [go-vcloud-director/v2/govcd/vapp_network.go](https://github.com/terraform-providers/terraform-provider-vcd/blob/master/vendor/github.com/vmware/go-vcloud-director/v2/govcd/vapp_network.go#L280-L288) lines 280-288:

```
// IsVappNetwork allows to identify if given network config is a vApp network and not a vApp Org network
func IsVappNetwork(networkConfig *types.NetworkConfiguration) bool {
	if networkConfig.FenceMode == types.FenceModeIsolated ||
		(networkConfig.FenceMode == types.FenceModeNAT && networkConfig.IPScopes != nil &&
			networkConfig.IPScopes.IPScope != nil && len(networkConfig.IPScopes.IPScope) > 0 &&
			!networkConfig.IPScopes.IPScope[0].IsInherited) {
		return true
	}
	return false
}
```

My vApp network is bridged with and org network:

```
    <NetworkConfig networkName="COMPANY-L2-APP-NON-PROD-VLAN36">
        <Link rel="repair" href="https://my.provider.com/api/admin/network/7b258bbaredacted907fcc87a9c5/action/reset"/>
        <Description></Description>
        <Configuration>
            <IpScopes>
                <IpScope>
                    <IsInherited>true</IsInherited>
                    [Redacted for size]
                </IpScope>
            </IpScopes>
            <ParentNetwork href="https://my.provider.com/api/admin/network/8249f377redacted22eb74350bfa" id="8249f377redacted22eb74350bfa" name="COMPANY-L2-APP-NON-PROD-VLAN36"/>
            <FenceMode>bridged</FenceMode>
            <RetainNetInfoAcrossDeployments>false</RetainNetInfoAcrossDeployments>
            <GuestVlanAllowed>false</GuestVlanAllowed>
        </Configuration>
        <IsDeployed>true</IsDeployed>
    </NetworkConfig>
```

I can not use the org network , trying with type org instead of vApp returns a 403 error.
I can use the vApp network in UI to assign an ethernet card.

So I _suspect_ the bridge type should be allowed on top of the two other FenceMode [from constant here](https://github.com/terraform-providers/terraform-provider-vcd/blob/master/vendor/github.com/vmware/go-vcloud-director/v2/types/v56/constants.go#L140-L144).

My idea would be to patch the IsVappNetwork to add another alternative allowing bridged and inherited IP scope as far as I can tell.

I'm a bit green on terraform and vcloud, so this could be a terrible idea and the proper solution is to use type="org" and request the necessary rights on the user account to read the org networks, if so this issue can be closed.

**Comment by vbauzysvmware** [comment]
Hi @Tensibai,

Please change `  type = "vapp"` ->   type = "org". You are using vAPP Org network, not vAPP network.

**Comment by vbauzysvmware** [comment]
User gets error due limited rights he has:

 terraform refresh
data.vcd_vapp_org_network.orgVLAN36: Refreshing state...
data.vcd_vapp_network.VLAN36: Refreshing state...
data.vcd_network_direct.NETDIRECT: Refreshing state...
Error: [direct network read] network not found: [get network] error getting network COMPANY-L2-APP-NON-PROD-VLAN36: error retrieving org vdc network: API Error: 403: [ fb95ae02-b8e9-4bbc-a9e7-63ca14daa6ce ] Either you need some or all of the following rights [ORG_VDC_NETWORK_VIEW] to perform operations [ORGANIZATION_VDC_NETWORK_VIEW] for xxxxx

**Comment by vbauzysvmware** [comment]
Real issue user face is:
``` Either you need some or all of the following rights [ORG_VDC_NETWORK_VIEW] to perform operations [ORGANIZATION_VDC_NETWORK_VIEW] for...
```
#541solves issue with checking Org VD network.
