### ISSUE TITLE
error updating network connection: Cannot find the declaration of element 'NetworkConnectionSection'.

### ISSUE THREAD

**Issue by a-stein** [vmware/terraform-provider-vcd#548]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Tested with v0.12.29 and v0.13

### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
provider "vcd" {
  user     = var.vcd_user
  password = var.vcd_pass
  org      = var.vcd_org
  vdc      = var.vcd_vdc
  url      = var.vcd_url
}

resource "vcd_vapp" "rancher-cluster" {
  name = var.vcd_vapp_name
}

resource "vcd_vapp_org_network" "vapp-network" {
  vapp_name         = vcd_vapp.rancher-cluster.name
  org_network_name  = "net"
}

resource "vcd_vapp_vm" "rancher-master" {

  vapp_name     = var.vcd_vapp_name
  name          = "test-vm"
  catalog_name  = var.vcd_catalog_name
  template_name = var.vcd_template_name
  memory        = 4096
  cpus          = 2
  cpu_cores     = 1

  metadata = {
    role    = "master"
    env     = var.vcd_vapp_name
    version = "v1"
  }

  network {
    type = "org"
    name = "net"
    // needs pool configured in vsphere cloud network adapter
    ip_allocation_mode = var.network_ip_allocation_mode
    is_primary         = var.network_is_primary
  }

  guest_properties = {
    "guest.hostname" = "test-vm"
  }
}

```

### Debug Output
/

### Panic Output
/

### Expected Behavior
The specified vcd_vapp_vm resource with a attached network should be created.

### Actual Behavior
The VM is created and has the network attached but Terraform returns the following error message.

```Error: unable to update network configuration: error updating network connection: API Error: 400: [ 670168e0-3e48-4417-bb2d-cf3658e76d18 ] HTTP 400 Bad Request
 - cvc-elt.1: Cannot find the declaration of element 'NetworkConnectionSection'.

  on main.tf line 12, in resource "vcd_vapp_vm" "rancher-master":
  12: resource "vcd_vapp_vm" "rancher-master" {
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Same error with vcd provider version 2.8 and 2.9

### References
https://www.vmware.com/support/vcd/doc/rest-api-doc-1.5-html/types/NetworkConnectionSectionType.html

**Comment by vbauzysvmware** [comment]
First thing to avoid confusions regarding race conditions - scripts has to be created using references to resources which they depend on - this helps to manage hierarchy of creation, update and deletion of resources.

Please try like this:

```
provider "vcd" {
  user     = var.vcd_user
  password = var.vcd_pass
  org      = var.vcd_org
  vdc      = var.vcd_vdc
  url      = var.vcd_url
}

resource "vcd_vapp" "rancher-cluster" {
  name = var.vcd_vapp_name
}

resource "vcd_vapp_org_network" "vapp-network" {
  vapp_name         = vcd_vapp.rancher-cluster.name
  org_network_name  = "net"
}

resource "vcd_vapp_vm" "rancher-master" {

  vapp_name     = vcd_vapp.rancher-cluster.name
  name          = "test-vm"
  catalog_name  = var.vcd_catalog_name
  template_name = var.vcd_template_name
  memory        = 4096
  cpus          = 2
  cpu_cores     = 1

  metadata = {
    role    = "master"
    env     = var.vcd_vapp_name
    version = "v1"
  }

  network {
    type = "org"
    name = vcd_vapp_org_network.vapp-network.org_network_name
    // needs pool configured in vsphere cloud network adapter
    ip_allocation_mode = var.network_ip_allocation_mode
    is_primary         = var.network_is_primary
  }

  guest_properties = {
    "guest.hostname" = "test-vm"
  }
}

**Comment by a-stein** [comment]
Hi, I updated my code and tried it on a clean enviornment but I still get the same error message. I'm using the following vCloud version: 10.1.1.16282995

**Comment by vbauzysvmware** [comment]
Hi, is this VCD backed by Nsx-T or Nsx-V ? 
to better understand issue we need more logs from go-vcloud-director which should be enabled.
How to enable is mentioned in documentation: https://www.terraform.io/docs/providers/vcd/index.html - parameters logging, logging_file.

**Comment by a-stein** [comment]
The VCD is using NSX-V. 

[go-vcloud-director.log](https://github.com/vmware/terraform-provider-vcd/files/5128068/go-vcloud-director.log)

**Comment by Didainius** [comment]
@a-stein ,
Thanks for logs. Very odd as I had similar example succeeding using PhotonOs (http://dl.bintray.com/vmware/photon/3.0/GA/ova/photon-hw11-3.0-26156e2.ova).
Would you be able to test out your configuration with Photon OS template as we want to understand if this is related to template.

Thanks

**Comment by a-stein** [comment]
@Didainius I get the same error message using the provided Photon OS template.

What really confuses me is that when I look in the VCD the VM is created and the network is attached, but Terraform still throws the exception

**Comment by vbauzysvmware** [comment]
@a-stein 
What user type(Role) you are using?

P.s. We can't replicate the issue.

**Comment by a-stein** [comment]
@vbauzysvmware 

The user has the role "Organization Administrator"

**Comment by Didainius** [comment]
Very strange. I have tried with "vApp author" and "Organization Administrator". It always worked on exactly the same version as yours. May I also ask which OS are you running Terraform on?

**Comment by Didainius** [comment]
This is my exact config:
```hcl

resource "vcd_vapp" "rancher-cluster" {
  name = "rancher"
}

resource "vcd_vapp_org_network" "vapp-network" {
  vapp_name         = vcd_vapp.rancher-cluster.name
  org_network_name  = "net-dainius-r"
}

resource "vcd_vapp_vm" "rancher-master" {

  vapp_name     = vcd_vapp.rancher-cluster.name
  name          = "test-vm"
  catalog_name  = "cat-dainius"
  template_name = "empty-vapp-vm"
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1

  network {
    type = "org"
    name = vcd_vapp_org_network.vapp-network.org_network_name
    // needs pool configured in vsphere cloud network adapter
    ip_allocation_mode = "POOL"
    is_primary         = true

  }
}
```

Org network `net-dainius-r` is routed

**Comment by a-stein** [comment]
I tried it on Windows as well as Alpine in a Docker container. Is it maybe related to the VCD API version?

**Comment by Didainius** [comment]
It should not as `terraform-provider-vcd` binary implies default version which I used as well on exactly the same build version as yours. Need to think of what else it could be.

**Comment by a-stein** [comment]
Hi, our VCD distributor resolved the problem.

The problem was related to the ssl certifiacte chain that the provider requires. To quote roughly, the vcd provider needs the full certificate chain while terraform in general works with a shorter version.

**Comment by Didainius** [comment]
That is very surprising! Do you have any more details as this might be very good knowledge for others.

**Comment by marcusnh** [comment]
Hi, I have the same error with the same configuration. What was the fix?

**Comment by roman-aleksejuk-telia** [comment]
@a-stein Please provide more details on the resolution of that issue if possible! 😊
Stuck with the same issue.

**Comment by a-stein** [comment]
@roman-aleksejuk-telia Sorry to hear that you run into the same problem. Sadly I can't remember the details about this issue and how we solved it.
