### ISSUE TITLE
vcd_network_direct: Import fails with no parent network found

### ISSUE THREAD

**Issue by djvl** [vmware/terraform-provider-vcd#554]
### Terraform Version

Terraform v0.13.2
+ provider registry.terraform.io/terraform-providers/vcd v2.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_network_direct

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vcd = {
      source  = "terraform-providers/vcd"
      version = "= 2.9"
    }
  }
}

provider "vcd" {
  alias                = "dc02"
  user                 = var.vcd_user
  password             = var.vcd_pass
  org                  = var.vcd_org_dc02
  vdc                  = var.vcd_vdc_dc02
  url                  = var.vcd_url_dc02
  max_retry_timeout    = var.vcd_max_retry_timeout
  allow_unverified_ssl = var.vcd_allow_unverified_ssl
}

resource "vcd_network_direct" "stretched-dc02" {
  provider     = vcd.dc02
  name              = "10.17.48.244-254"
  org               = var.vcd_org_dc02
  vdc               = var.vcd_vdc_dc02
  external_network  = "COMPUTE"
}
```

### Debug Output
See both attached files for the debug output:

[tf.log](https://github.com/vmware/terraform-provider-vcd/files/5195211/tf.log)
[go-vcloud-director.log](https://github.com/vmware/terraform-provider-vcd/files/5195244/go-vcloud-director.log)

### Expected Behavior
Successful import of existing network resource as stated by the documentation:
https://www.terraform.io/docs/providers/vcd/r/network_direct.html#importing

### Actual Behavior
Import fails with the error message below:
```
$ terraform import vcd_network_direct.stretched-dc02 "202125;VDC Demo11 Zone02;82.201.5.116-118"
vcd_network_direct.stretched-dc02: Importing from ID "202125;VDC Demo11 Zone02;82.201.5.116-118"...

Error: [direct network import] no parent network found for 82.201.5.116-118
```

### Steps to Reproduce
1. `terraform import` command like above.

### Notes
We have access to the VDC as 'Organization Administrator'. Which is sufficient to create an vApp and connect the existing direct network '82.201.5.116-118' manually using the administrative webinterface.

**Comment by dataclouder** [comment]
Hi,
Thanks for reporting this issue.

It looks like you are trying to import using a non-system administrator account.
As stated in the documentation, all operations on direct network **resources** require a system administrator.

You can, however, use a [direct network data source](https://www.terraform.io/docs/providers/vcd/d/network_direct.html) as org user.

**Comment by djvl** [comment]
Hi, thanks for your quick response! I have changed the resource into an data source and now I can use it. Did not thought about the data source solution. Thanks again!
