### ISSUE TITLE
vcd_vapp_vm - Clone from running VM resource

### ISSUE THREAD

**Issue by GuybrushThreepwood-Dev** [vmware/terraform-provider-vcd#562]
Hi,

We have a scenario where in vCloud Director we need to create new VMs from a running VM, rather than a Template VM in a catalog library.
I can't find an option with Terraform to use the vCloud director "Copy To" function. Is this available in Terraform at present, or if not possible at all? If it is possible but not available yet, could I raise a feature request please?

Many thanks.

**Comment by vbauzysvmware** [comment]
Hi @GuybrushThreepwood-Dev - current implementation doesn't have such functionality. Thank for your idea. This issue can stay and will work as feature request in backlog.

**Comment by GuybrushThreepwood-Dev** [comment]
Hi @vbauzysvmware,

Many thanks.
