### ISSUE TITLE
Add a resource for creating new roles

### ISSUE THREAD

**Issue by nikolaifa** [vmware/terraform-provider-vcd#564]
### Feature request

A new resource capable of creating new roles with customized permissions. 

This is useful for us for deployments of numerous different tenants with differing permission requirements.

**Comment by jpbuecken** [comment]
Will help us as well: Use case: Via terraform template we can make sure our roles are the same between integration and production VCD installations.

**Comment by dataclouder** [comment]
Implemented in #677
