### ISSUE TITLE
vcd provider not available in terraform registry

### ISSUE THREAD

**Issue by mkot02** [vmware/terraform-provider-vcd#570]
### Terraform Version
```
$ terraform version
Terraform v0.13.4
```

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vcd = {
      source = "vmware/vcd"
    }
  }
  required_version = ">= 0.13"
}

provider "vcd" {
  auth_type            = "integrated"
  org                  = "***"
  vdc                  = "***"
  url                  = "***"
}

resource "vcd_vapp" "vapp_test" {
  name = "vApp_Test"
}

```

### Expected Behavior
vcd provides should be available in terraform registry

### Actual Behavior
vcd provides is not available in terraform registry

### Steps to Reproduce
```shell
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of vmware/vcd...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider vmware/vcd:
provider registry registry.terraform.io does not have a provider named
registry.terraform.io/vmware/vcd

```

### Other
https://registry.terraform.io/v1/providers/vmware/vcd
```json
{"errors":["Not Found"]}
```

**Comment by lvirbalas** [comment]
Hello,

Starting with the next 3.0.0 release it will be published in the registry. 3.0.0 is coming very soon. We're at the point of merging final PRs and then enter the pre-release certification phase.

**Comment by Didainius** [comment]
Just for reference - 3.0.0 is released and it is available in registry - https://registry.terraform.io/providers/vmware/vcd/latest
