### ISSUE TITLE
Error while installing vmware/vcd v3.0.0

### ISSUE THREAD

**Issue by elandmancrs** [vmware/terraform-provider-vcd#578]
Hi there,

I'm not sure if this is a result of my corporate network messing with the download... i have tried on a personal device with the same result. Any ideas?

### Terraform Version
0.13.4

### Plugin usage
version.tf file....
```
terraform {
  required_providers {
    vcd = {
      source  = "vmware/vcd"
      version = "3.0.0"
    }
  }
  required_version = ">= 0.13"
}
```

### Error message
> terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of vmware/vcd...
- Installing vmware/vcd v3.0.0...

Error: Failed to install provider

Error while installing vmware/vcd v3.0.0: archive has incorrect SHA-256
checksum 16c456799b1cf056d1b77307ceedef1ab853bbf1545cc95e5898216537d6b765
(expected 64d4c42dd8239516369c98bd3e7df052dcac4f5671aee613d31db016a638702e)

**Comment by dataclouder** [comment]
Hi
Could you try downloading the file manually and running the checksum locally using your own tools?

The file corresponding to the expected checksum is [terraform-provider-vcd_3.0.0_windows_amd64.zip](https://github.com/vmware/terraform-provider-vcd/releases/download/v3.0.0/terraform-provider-vcd_3.0.0_windows_amd64.zip)

I don't use Windows, but looking around I found [this article](https://www.rekha.com/how-to-perform-shasum-checks-in-windows-10.html) that explains how to do it.

**Comment by elandmancrs** [comment]
Hi there,
Thanks for the manual test. It helped me confirm its my corporate network, likely AV messing with the archive.
Thank you for your effort!
