### ISSUE TITLE
Unable to get NSX-T backed vcd_external_network_v2

### ISSUE THREAD

**Issue by medea61** [vmware/terraform-provider-vcd#581]
Hi there,

### Terraform Version
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/vmware/vcd v3.0.0

### Affected Resource(s)
- vcd_external_network_v2

### Terraform Configuration Files
```hcl
data "vcd_external_network_v2" "ext_net" {
  name = "t0-CL-WRKL-ZRH2-1"
}
```
### Debug Output
https://gist.github.com/medea61/2239b01a7c69d3a7e7aafbdb75f67c95

### Expected Behavior
vcd_external_network_v2 datasource should have been pulled from the API

### Actual Behavior
provider is unable to find object

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
This is an NSX-T only VCD installation

**Comment by Didainius** [comment]
@medea61 ,
For reference - was it a wrong name?

**Comment by medea61** [comment]
@Didainius yes. the name had a space in the front **and** in the back on the target system, thus tf was unable to find it.
