### ISSUE TITLE
data vcd_edgegateway object not yet supporting NSX-T?

### ISSUE THREAD

**Issue by medea61** [vmware/terraform-provider-vcd#582]
### Terraform Version
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/vmware/vcd v3.0.0

### Affected Resource(s)
- vcd_edgegateway

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vcd = {
      source = "vmware/vcd"
      version = "3.0.0"
    }
  }
}

# Configure the VMware vCloud Director Provider
provider "vcd" {
  user                 = var.vcd_user
  password             = var.vcd_pass
  auth_type            = "integrated"
  org                  = "System"
  url                  = var.vcd_url
  max_retry_timeout    = "60"
  allow_unverified_ssl = false
}

data "vcd_edgegateway" "this_eg" {
  name = "t1-terraform_trial-alloc"
  org  = var.org_name
  vdc  = var.ovdc_name
}
```

### Debug Output
https://gist.github.com/medea61/5ea4a61525d9613c9366f91aed1acea5

### Expected Behavior
get object of type vcd_edgegateway

### Actual Behavior
Error: unable to read general load balancer settings: unable to read load balancer configuration: 500 Server Error

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
This is an NSX-T only environment

**Comment by Didainius** [comment]
Yes, first iteration of NSX-T support (V3.0.0) only works with org vdc and external network. Next version will have more - including edge gateway (a separate resource)

**Comment by medea61** [comment]
well then... looking forward to the next release then. :)
