### ISSUE TITLE
external_networks deprecation

### ISSUE THREAD

**Issue by dprosper** [vmware/terraform-provider-vcd#588]
With the external_networks deprecation in v3.0 https://registry.terraform.io/providers/vmware/vcd/latest/docs#removed-resources-and-fields how can I obtain the names of all defined networks in my Edge Gateway?  

Previously in v2.9 I was able to get the list of all networks attached to my edge gateway and use that information to read their names (line 50), and use that information to obtain more details, etc... 
![image](https://user-images.githubusercontent.com/11874942/98007412-5cef1c80-1dc1-11eb-9191-18d4e96db8cb.png)

With v3.0 I only get the name of 1 of the networks, how do I obtain the name of the second network?  

Might be related to #577

**Comment by Didainius** [comment]
@dprosper ,
indeed the old structure wasn't able to hold complexity of configuration, but it is true this broke. It only returns 1 external network in datasource because of Terraform SDK V1 bug. Our `master` branch now was migrated to Terraform SDK V2 which is capable of returning multiple elements in `TypeSet`. Would you be able to try building from master and see if it helps. I could help building if needed.

**Comment by dprosper** [comment]
@Didainius Thank you for the quick response.  I can see the two external_networks under the edge gateway, and was able to work the Terraform template with that.  When do you anticipate this update to be made available in the registry? 

I no longer see the default gateway, there used to be a field called default_gateway_network in the state, will that make it back in as well?

**Comment by Didainius** [comment]
We are not aiming to return the deprecated fields, but the `external_network` structure will return all networks (not only a single one). The `default_gateway_network` is the one where `use_for_default_route=true` (as in your above screenshot)

**Comment by dprosper** [comment]
ah I see that now, that will work even better. Thx

**Comment by dprosper** [comment]
rough timeline for this update to make it to the registry? just looking to plan. thx

**Comment by Didainius** [comment]
> ah I see that now, that will work even better. Thx
Np. As I said - if you are willing to test it - you could build the provider from our `master` branch. It should already work. I could also build it for you or help.

>rough timeline for this update to make it to the registry? just looking to plan. thx
A bit early to state there is a chance it happens late this year.

**Comment by dprosper** [comment]
I built and tested it, it works and I made pre-leminary updates to my Terraform template in a branch.  

That template is part of a public tutorial we have which I need to plan to update once it is released, I have now locked the template to v 2.9.0 of the provider as 3.0 breaks it, thus the reason I was asking, so no rush. 

Thank you again.  

I think we can close this issue.

**Comment by carmineesposito73** [comment]
@dprosper, @Didainius I need your help (I'm sorry).
I haven't find a way to migrate from:
```
  network_name = vcd_edgegateway.edge1.default_gateway_network
```
to the new way (it should be somethink like this):
```
  network_name = [ for net in vcd_edgegateway.edge1.external_network : net.name if net.subnet.use_for_default_route ]
```
thank you very much

**Comment by Didainius** [comment]
@carmineesposito73 ,
What is your goal? Is it to find default network name?

**Comment by carmineesposito73** [comment]
@Didainius yes

**Comment by Didainius** [comment]
@carmineesposito73 ,
Now that makes sense and may have made life worse. Now the question - is this the only place where you can get name of network? (are you using a datasource only?)
I need to think about an HCL snippet to pull this out yet

**Comment by carmineesposito73** [comment]
I just hit into this.
I though it was an "easy" solution to get the name of the default external network.

> We are not aiming to return the deprecated fields, but the `external_network` structure will return all networks (not only a single one). The `default_gateway_network` is the one where `use_for_default_route=true` (as in your above screenshot)

I don't know if there's another way to get that name if I'm an org-admin and I get an edge created by the provider

**Comment by dprosper** [comment]
not the best solution on my part, but that is what i am using right now.  the provider includes only two networks, the `external_network` array sorts the networks by the network name.  based on the naming scheme used by the provider the external network that has `use_for_default_route=true` is always the second one in the array, so i use `data.vcd_edgegateway.edge.external_network)[1].name` to read it.   

i know this is not long term and may fail at one point if the naming scheme changes or terraform changes their sorting order, or ... but that is what i did.

**Comment by carmineesposito73** [comment]
@dprosper, do I make something wrong?

```
output "default_ext_net" {
  value       = data.vcd_edgegateway.my-edge1.external_network[0].name
  description = "Default ext net"
}
```
```
$ terraform plan

Error: Invalid index

  on datasrc-vcloud-org-training.tf line 114, in output "default_ext_net":
 114:   value       = data.vcd_edgegateway.my-edge1.external_network[0].name

This value does not have any indices.
```
This is the edge output after datasource
```
my-edge1 = {
    configuration                   = "compact"
    default_external_network_ip     = "156.A.X.91"
    description                     = "edge gw created by terraform"
    distributed_routing             = false
    external_network                = [
        {
            enable_rate_limit   = false
            incoming_rate_limit = 0
            name                = "Internet_01"
            outgoing_rate_limit = 0
            subnet              = [
                {
                    gateway               = "156.A.X.1"
                    ip_address            = ""
                    netmask               = "255.255.255.128"
                    suballocate_pool      = [
                        {
                            end_address   = "156.A.X.94"
                            start_address = "156.A.X.92"
                            },
                        ]
                    use_for_default_route = true
                    },
                ]
            },
        {
            enable_rate_limit   = false
            incoming_rate_limit = 0
            name                = "TI-Services"
            outgoing_rate_limit = 0
            subnet              = [
                {
                    gateway               = "10.23.97.1"
                    ip_address            = ""
                    netmask               = "255.255.255.0"
                    suballocate_pool      = []
                    use_for_default_route = false
                    },
                ]
            },
        ]
. . .
```

**Comment by dprosper** [comment]
@carmineesposito73 try

`tolist(data.vcd_edgegateway.my-edge1.external_network)[0].name`

**Comment by carmineesposito73** [comment]
@dprosper thanks!

**Comment by carmineesposito73** [comment]
@dprosper @Didainius finally I've found a way:

suggested by @dprosper 
```
output "default_ext_net" {
  value       = tolist(data.vcd_edgegateway.my-edge1.external_network)[0].name
  description = "Default ext net"
}
```
with if
```
output "default_ext_net_if" {
  value       = element([ for net in data.vcd_edgegateway.my-edge1.external_network : net.name if tolist(net.subnet)[0].use_for_default_route ], 0)
  description = "Default ext net"
}
```
results:
```
Changes to Outputs:
  + default_ext_net    = "Internet_01-RZ"
  + default_ext_net_if = "Internet_01-RZ"
```

**Comment by jefftp** [comment]
@dprosper Are you running: `tolist(data.vcd_edgegateway.my-edge1.external_network)[0].name`
with an org admin account? I'm running into a permissions error on my end.

Error: error fetching external network (Internet External Network) details error fetching external network details functionality requires System Administrator privileges
