### ISSUE TITLE
Can't create new vm with vcd_vm_internal_disk in tf file

### ISSUE THREAD

**Issue by Asgoret** [vmware/terraform-provider-vcd#589]
Hi to all. 

When I add `vcd_vm_internal_disk` to my TF file I can't create new VMs. It's always failed on vcd_vm_internal_disk creating. Seems that this module tries to create new disks within just import them from fresh VM. Is there any solution on how to fix it and force it to work properly?

```
resource "vcd_vapp_vm" "node_zone_5" {
  vapp_name     = vcd_vapp.developers-cluster.name
  name          =  format("node-%02d.${var.zone_5}.${var.cluster_type}.${var.domain}", count.index + 1)
  computer_name = format("node-%02d.${var.zone_5}.${var.cluster_type}.${var.domain}", count.index + 1)
  count         = var.node_zone_5_count
  catalog_name  = var.temlate_catalog
  template_name = var.vm_teample_node
  memory        = var.node_zone_5_memory
  cpu_cores     = var.node_zone_5_cpu_cores
  cpus          = var.node_zone_5_cpus
  vdc           = ...
  org           = var.vcd_org
  power_on      = "true"
  network {
    type               = "org"
    name               = var.vcd_network_name_dmz
    ip_allocation_mode = "DHCP"
  }
  network {
    type               = "org"
    name               = "Storage-Network"
    ip_allocation_mode = "POOL"
  }
  override_template_disk {
    bus_type         = "paravirtual"
    size_in_mb       = "51200"
    bus_number       = 0
    unit_number      = 0
    storage_profile  = "Tier B"
  }
  metadata = { ... }
  customization { initscript    = ...  }

  lifecycle {
    prevent_destroy = false
    ignore_changes = [
      customization
    ]
  }
}



resource "vcd_vm_internal_disk" "node_zone_5_root_disk" {
  vapp_name       = vcd_vapp.developers-cluster.name
  vdc             = var.vcd_vapp_vdc
  vm_name         = format("node-%02d.${var.zone_5}.${var.cluster_type}.${var.domain}", count.index + 1)
  count           = var.node_zone_5_count
  bus_type        = "paravirtual"
  size_in_mb      = "51200"
  bus_number      = 0
  unit_number     = 0
  storage_profile  = "Tier B"
  depends_on      = [vcd_vapp_vm.node_zone_5]
}

```
cc @vbauzysvmware @Didainius

**Comment by vbauzysvmware** [comment]
Hi @Asgoret, could you share the error? I can't reproduce it, though I tested with removed `var` and `counts`.

**Comment by Asgoret** [comment]
Hi @vbauzysvmware 
I've got from console this error:
```
error updating VM disks: error waiting for task completion after internal disks update for VM node-01.prestage.dev.dlg: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ 282da54c-7801-472d-88cd-e1689fb8fe4b ] Unable to perform this action. Contact your cloud administrator.
```

Asked for details from a provider. What parameters did you change so it worked?

**Comment by vbauzysvmware** [comment]
Hi @Asgoret,

I just removed count and used static VM name. Seems your error comes from VCD - internal error.

to better understand issue we need more logs from go-vcloud-director which should be enabled.
How to enable is mentioned in documentation: https://www.terraform.io/docs/providers/vcd/index.html - parameters logging, logging_file.

Also after error you can check UI task list, it may show more information. If not, maybe needed to look in VCD logs, bet let's see if our logs show more.

**Comment by Asgoret** [comment]
@vbauzysvmware 
Cut of other nodes (hope don't cut of something useful)
[logs.txt](https://github.com/vmware/terraform-provider-vcd/files/5494216/logs.txt)

**Comment by vbauzysvmware** [comment]
I think I have an idea what is the issue:

Why do you override template without resizing disk? - this code part not needed
```
  override_template_disk {
    bus_type         = "paravirtual"
    size_in_mb       = "51200"
    bus_number       = 0
    unit_number      = 0
    storage_profile  = "Tier B"
  }
```
and then create new internal disk with same bus and unit number? 

```
resource "vcd_vm_internal_disk" "node_zone_5_root_disk" {
  vapp_name       = vcd_vapp.developers-cluster.name
  vdc             = var.vcd_vapp_vdc
  vm_name         = format("node-%02d.${var.zone_5}.${var.cluster_type}.${var.domain}", count.index + 1)
  count           = var.node_zone_5_count
  bus_type        = "paravirtual"
  size_in_mb      = "51200"
  bus_number      = 0
  unit_number     = 0
  storage_profile  = "Tier B"
  depends_on      = [vcd_vapp_vm.node_zone_5]
}
```

Seems that fails due that you try to create two disk with same bus_number and unit_number.

**Comment by Asgoret** [comment]
@vbauzysvmware I override template because it has 32GB root disk and I need 50GB). I use this construction due to this part of the documentation: https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vm_internal_disk
![Screenshot from 2020-11-05 16-04-25](https://user-images.githubusercontent.com/30697011/98244523-a76ac780-1f80-11eb-8a62-8eaaf4189c71.png)

**Comment by vbauzysvmware** [comment]
If your aim was to increase size of template internal disk, then solution is this:
```
  override_template_disk {
    bus_type         = "paravirtual"
    size_in_mb       = "51200"
    bus_number       = 0
    unit_number      = 0
    storage_profile  = "Tier B"
  }
```
This resource creates new disk for your VM:
```
resource "vcd_vm_internal_disk" "node_zone_5_root_disk" {
  vapp_name       = vcd_vapp.developers-cluster.name
  vdc             = var.vcd_vapp_vdc
  vm_name         = format("node-%02d.${var.zone_5}.${var.cluster_type}.${var.domain}", count.index + 1)
  count           = var.node_zone_5_count
  bus_type        = "paravirtual"
  size_in_mb      = "51200"
  bus_number      = 0
  unit_number     = 0
  storage_profile  = "Tier B"
  depends_on      = [vcd_vapp_vm.node_zone_5]
}

```

**Comment by Asgoret** [comment]
@vbauzysvmware so there is no opportunity to add internal disk in tf state for next modifications due to VM creating process?

**Comment by vbauzysvmware** [comment]
@Asgoret yes got it right, for internal disk which comes from template there isn't. You have to import them as `vcd_vm_internal_disk` to manage them later.  `override_template_disk` allows to resize on VM creation if don't need manage disk later. But for new disks which aren't on template `vcd_vm_internal_disk` creates/updates - manages state of the internal disk in usual way.

**Comment by Asgoret** [comment]
@vbauzysvmware strange but ok...is there any chance in the future that this module will read meta from VM and add internal disk due create process?

**Comment by vbauzysvmware** [comment]
Well am not sure, VM template are culprit here - they don't have ID's so we get IDs and can manage them when VM is created from template.

**Comment by Asgoret** [comment]
@vbauzysvmware they have IDs. I got all information from state file
![Screenshot from 2020-11-05 16-42-52](https://user-images.githubusercontent.com/30697011/98249765-b143f900-1f87-11eb-93b1-b273676f13b7.png)

**Comment by vbauzysvmware** [comment]
:)) because they already created.
If you open `template_name = var.vm_teample_node` template you are using and open XML you will see no Id's.

**Comment by Asgoret** [comment]
Hm...maybe, but there is `depends_on`. So we can read tf state file after resource with VM were created (If i understand correctly when resource complete his work it wrote to tf state immediately)

**Comment by vbauzysvmware** [comment]
We tried a few ways to make better, yet this approach was most functionality with minimum func lost. I won't go deep to other limitations from terraform and API. If you see possibility to make it working - you can make contribution we are open to look it, review it and accept it. Also please keep in mind that there is a lot push from other users to manage other VM configurations as separate resources due other various reasons to have better scripting capabilities.

**Comment by Asgoret** [comment]
@vbauzysvmware thanks for answers, I`ll close the issue.
