### ISSUE TITLE
Please add ssh-keys to metadata or customization 

### ISSUE THREAD

**Issue by patsevanton** [vmware/terraform-provider-vcd#591]
Please add ssh-keys to metadata or customization 
For example:
```
resource "vcd_vapp_vm" "vm1" {
  vapp_name     = vcd_vapp.vms.name
  name          = "apatsev1"
  catalog_name  = "CentOS"
  template_name = "CentOS7_64-bit"
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1

  customization {
    enabled                = true
    ssh-keys = "centos:${file("~/.ssh/id_rsa.pub")}"
}

}
```
OR
```
resource "vcd_vapp_vm" "vm1" {
  vapp_name     = vcd_vapp.vms.name
  name          = "apatsev1"
  catalog_name  = "CentOS"
  template_name = "CentOS7_64-bit"
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1

  metadata = {
    ssh-keys = "centos:${file("~/.ssh/id_rsa.pub")}"
  }

}
```

**Comment by Didainius** [comment]
Hello @patsevanton,
The resource follows VCD UI and guest customization does not have `ssh-keys` option as there is no standartized option to configure guest OS.

How you inject SSH keys very much depend on what customization tooling your guest OS uses. Maybe `initscript` could help you (https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#initscript) or if it is the cloud-init you are using it may be `guest_properties` you are interested in https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#guest_properties

Are you aware how your guest OS accepts configuration parameters?

**Comment by patsevanton** [comment]
CentOS accepts configuration parameters

**Comment by Didainius** [comment]
Thanks,
Which configuration parameters exactly?

**Comment by Didainius** [comment]
Did you find out the mechanism to feed in ssh-keys? I'd want to resolve the issue but it would be good to find out the way that has worked for you and document it here

**Comment by patsevanton** [comment]
Not now. Thanks!
