### ISSUE TITLE
Request - Get all vcd_network_direct from datasource

### ISSUE THREAD

**Issue by Kronk74** [vmware/terraform-provider-vcd#596]
Hi,

### Terraform Version
v0.13.4

### Affected Datasource(s)
- vcd_network_direct

Is it possible to have all vcd_network_direct ? Like,why not, : vcd_network**s**_direct ? :)

Best regards,

Thomas

**Comment by Didainius** [comment]
Hello @Kronk74,
Usually in this provider one datasource returns one complete structure of objects however there is an open PR to list objects (https://github.com/vmware/terraform-provider-vcd/pull/594). You could combine the two to make a list of datasources (by  iterating over the list in a data source).

**Comment by Kronk74** [comment]
Hi @Didainius,

Good to see that there is a PR to list objects :) 

To deal with it I created a local variable like this : 

`  network_infos = {    
   test1 = data.vcd_network_direct.test1,    
   test2 = data.vcd_network_direct.test2
  }
`

And add datasources associated : 

`data "vcd_network_direct" "test1" {                                                                                                                                                                                                          
  filter {
    name_regex = "test1"
  }
}
data "vcd_network_direct" "test2" {
  filter {
    name_regex = "test2"
  }
}
`

After that, I use the network that I want for each vm.

It works but I wanted to know if it is possible to already group it into a resource.

Maybe the PR will allow me avoid this way of working :)

**Comment by Didainius** [comment]
@Kronk74 ,
I really hope so. I will close the issue for the time as we expect to have that listing option in next release. Feel free to reopen/add more details if needed.
