### ISSUE TITLE
vcd_edgegateway.external_network is listed as an optional argument but is enforced.

### ISSUE THREAD

**Issue by drgr33n-vw** [vmware/terraform-provider-vcd#601]
### Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.18.0
+ provider registry.terraform.io/vmware/vcd v3.0.0

### Affected Resource(s)
**vcd_edgegateway**

### Terraform Configuration Files
```
resource "vcd_edgegateway" "egw" {
  configuration = "full"
  distributed_routing = false
  fips_mode_enabled = false
  fw_default_rule_action = "deny"
  fw_default_rule_logging_enabled = false
  fw_enabled = true
  ha_enabled = true
  lb_acceleration_enabled = false
  lb_enabled = false
  lb_logging_enabled = false
  lb_loglevel = "info"
  name = "${vcd_org_vdc.vdc.name} Edge"
  org = var.vcd_org
  use_default_route_for_dns_relay = true
  vdc = vcd_org_vdc.vdc.name
}
```

### Debug Output
Error: "external_network": required field is not set

  on vdc.tf line 55, in resource "vcd_edgegateway" "egw":
  55: resource "vcd_edgegateway" "egw" {
     

### Expected Behavior
external_network shouldn't be a required option.

### Actual Behavior
Terraform fails with a missing argument error.

### Steps to Reproduce
terraform plan

**Comment by dataclouder** [comment]
`external_network` is a required option. It was listed as optional in the documentation as a leftover of a previous situation where there were two ways of selecting it, and the provider complained if both ways were empty. When we removed the deprecated way of selecting an external network, we forgot to update the docs. It will be amended in the next release

**Comment by drgr33n-vw** [comment]
OK, I have a situation where I cannot import these resources then. When I import an edgegateway it's created without the "external_network" argument. The trouble is I don't have systems admin privileges so I'm ending up in a situation where I cannot proceed after importing the resource as the apply fails to update the resource if I add a blank entry. Would you like me to submit another ticket or would you consider this not a bug?

**Comment by dataclouder** [comment]
To import an edge gateway, you only need `name`, `org`, and `vdc`.
But even if you can import it, you can't use it as a resource, because you don't have system admin privileges.

However, as a non-system administrator, you can change the settings of an edge gateway using a data source + an instance of  [vcd_edgegateway_settings](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/edgegateway_settings)

**Comment by drgr33n-vw** [comment]
Thanks for the tips. So the only reason I'm importing it is so I can make use of the state variables within other resources etc. I am a edge case I suppose so I'll have to fork and make external_network optional for now. Thanks for a quick reply.

**Comment by Didainius** [comment]
@drgr33n-vw ,
Would you be able to share more details what exactly you use? Even if we don't immediately fix it this might give us context while designing resource/data sources in future.
