### ISSUE TITLE
datasource_vcd_org should provide the list of org vdcs and catalogs

### ISSUE THREAD

**Issue by carmineesposito73** [vmware/terraform-provider-vcd#603]
### Terraform Version
```
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/vmware/vcd v3.1.0
```
### Affected Resource(s)
datasource_vcd_org

### Description
while the response of `GET https://selfdcvcloud.nuvolaitaliana.it/api/admin/org/<ORG-ID>` contains the lists of vdcs and catalogs, datasource_vdc_org does not provides these lists
```
    <Catalogs>
        <CatalogReference href="https://cloud.provider.ulr/api/admin/catalog/6f2c0f31-df24-435b-ac31-eabb34f76512" name="PublicCatalog" type="application/vnd.vmware.admin.catalog+xml"/>
    </Catalogs>
    <Vdcs>
        <Vdc href="https://cloud.provider.ulr/api/vdc/4eb1b3cf-d259-4932-844c-f8d212a177e2" id="urn:vcloud:vdc:4eb1b3cf-d219-4932-844c-f8d212a177e2" name="org-training_PAYG_1" type="application/vnd.vmware.vcloud.vdc+xml"/>
    </Vdcs>
```

### Proposal
datasource_vcd_org should import the lists of vdcs names and catalogs names, otherwise it's necessary to access the cloud portal to get these names (as a org admin)

**Comment by Didainius** [comment]
Hello @carmineesposito73 ,
Are you after just a list of items? We have actually already created a resource for listing item names (or IDs) and it is in master, but not yet released. Next release will contain it.
https://github.com/vmware/terraform-provider-vcd/blob/master/website/docs/d/resource_list.html.markdown

As I see you have it built from master (3.1.0) - maybe you could validate if this is sufficient for your needs.

**Comment by carmineesposito73** [comment]
I'll try as soon as possible, thanks

**Comment by Didainius** [comment]
I'll just close it for now, but feel free to re-open if it this option has problems or you have any other ideas.

**Comment by carmineesposito73** [comment]
This is what I need, it works, thanks
```
## vdcs list
data "vcd_resource_list" "my-vdcs-list" {
  name          = "vdcs_list"
  resource_type = "vcd_org_vdc" 
  list_mode     = "name"
}

## source vdc
data "vcd_org_vdc" "my-vdc1" {
  org   = data.vcd_org.my-org.name
  name  = data.vcd_resource_list.my-vdcs-list.list[0]
}
```

**Comment by carmineesposito73** [comment]
It seems to me that getting a list of external networks of a specific provider vdc is not possible. Am I right?
Also provider vdc list is missing, correct?

**Comment by dataclouder** [comment]
You can have a list of external networks, unrelated to the provider VDC. Our current API can't filter further.

At the moment, `vcd_resource_list` lacks the ability of listing provider VDCs, network pools, vCenters. The API can see them, but we don't have yet corresponding resources to tie to such entities.
