### ISSUE TITLE
vcd provider problem with resources deleted outside of terraform

### ISSUE THREAD

**Issue by pasikarkkainen** [vmware/terraform-provider-vcd#611]
Hello,

Current version of Terraform vcd provider (v3.1.0) does not seem to work in the scenario if some of the vCD resources (vApps) are deleted from vCD manually / outside of terraform. vcd provider just gives a generic error and does not work. One needs to figure out the missing vCD resource somehow, and then manually delete it from the terraform state to get the vcd provider working again.

Earlier version of vcd provider (v2.3.0) did work OK in this scenario, ie. it noticed the resource (vApp/VM) is missing from vCD, and re-provisioned it to fix the situation automatically.

### Terraform Version
terraform v0.12.29
terraform vcd provider v3.1.0

### Affected Resource(s)
- vcd_vapp
- vcd_vapp_vm

### Expected Behavior
- Terraform vcd provider should show an error with the actual missing resource name/ID mentioned.
- Terraform vcd provider should re-provision the missing resources.

### Actual Behavior
- Terraform vcd provider gives a generic error message:
- ```Error: error finding Vapp: [ENF] entity not found``` 
- .. and refuses to do anything. terraform "plan", "apply" or "destroy" actions don't work in this scenario.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` and get some vapps/VMs provisioned to vCD.
2. Delete one of the vApps manually from vCD UI, or by using for example vcd-cli.
3. Run `terraform plan`, `terraform apply` or `terraform destroy` again and it'll fail with a generic error which doesn't mention which resource is not found / missing.

### Important Factoids
Currently running vCD 10.1.2

**Comment by murakest** [comment]
Hello,
when is it expected this issue to be fixed?

**Comment by dataclouder** [comment]
We have no timeline for this issue yet. We are aware of it and we'll look into it when we clear the current backlog

**Comment by durehed** [comment]
@dataclouder when, approximately, will the current backlog be cleared?

**Comment by dataclouder** [comment]
Sorry, can't provide any detail yet. We are currently focused on different priorities

**Comment by mightydok** [comment]
+1

**Comment by de1ayer** [comment]
+1

**Comment by claudineimatos** [comment]
Hi, I really consider this problem a major. How may it be prioritized or at least remediated?
+1

**Comment by mij0r** [comment]
+1

**Comment by danielfeiler** [comment]
Hi,
I have the same problem here with the following Versions:
Terraform v1.0.7
provider registry.terraform.io/vmware/vcd v3.3.1
VMware Cloud Director-Version: 10.1.2.16779297 Fri Aug 21 06:43:19 UTC 2020

**Comment by moskey71** [comment]
Same issue here
---
Terraform 0.15.5
vmware/vcd 3.1.0
vCD version: 10.3.0.18295834

**Comment by vbauzysvmware** [comment]
Solved and fix will be released in 3.6
