### ISSUE TITLE
NSX-T support for vcd_edgegateway_vpn

### ISSUE THREAD

**Issue by JimmyK112** [vmware/terraform-provider-vcd#617]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.14.4
+ provider registry.terraform.io/vmware/vcd v3.1.0

### Affected Resource(s)
- vcd_edgegateway_vpn

### Terraform Configuration Files
```hcl
resource "vcd_edgegateway_vpn" "vpn" {
  edge_gateway        = "test"
  name                = "vpn"
  description         = "Description"
  encryption_protocol = "AES256"
  mtu                 = 1400
  peer_id             = "1.1.1.1"
  peer_ip_address     = "1.1.1.1"
  local_id            = "2.2.2.2"
  local_ip_address    = "2.2.2.2"
  shared_secret       = "secret"

  peer_subnets {
    peer_subnet_name    = "DMZ_WEST"
    peer_subnet_gateway = "10.0.10.1"
    peer_subnet_mask    = "255.255.255.0"
  }


  local_subnets {
    local_subnet_name    = "DMZ_EAST"
    local_subnet_gateway = "192.168.1.1"
    local_subnet_mask    = "255.255.255.0"
  }
}
```

### Debug Output
Error: error setting ipsecVPNConfig rules: &errors.errorString{s:"error reconfiguring Edge Gateway: API Error: 400: [ e2295134-4ac5-4c62-8ac8-a1101d9e8d5e ] Backing NSX "" is not a NSX-V manager. Cannot be used for Nsx-V api calls."}

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Not sure if there should be created a new resourced dedicated for NSX-T VPN or this one needs to be modified.

**Comment by Didainius** [comment]
Hello @JimmyK112 ,
This is in our radar, but we have to pave the way to it yet with NSX-T resources. There will be a new resources to handle VPN in NSX-T.

**Comment by Didainius** [comment]
Ref #618 for tracking
