### ISSUE TITLE
Add VPN support for NSX-T 

### ISSUE THREAD

**Issue by Didainius** [vmware/terraform-provider-vcd#618]
This provider currently has only limited support for VPN (and only NSX-V).
This issue is to track work for implementing NSX-T VPN.

**Comment by JimmyK112** [comment]
Any updates for this with the coming 3.2 release?

**Comment by Didainius** [comment]
@JimmyK112 ,
We are paving the way there by adding NSX-T Org VDC networks, but VPN will not make 3.2 for sure.

**Comment by JimmyK112** [comment]
Aight, do we got a timeline?

**Comment by lvirbalas** [comment]
Upcoming:
- 3.2.0 early March – NSX-T networks
 
Then **_PRELIMINARY_**:
- 3.3.0 – NSX-T Firewall capabilities
- 3.4.0 - Load Balancer or VPN

Each release takes up to three months.
