### ISSUE TITLE
Create new resource for NSX-T firewall management

### ISSUE THREAD

**Issue by Didainius** [vmware/terraform-provider-vcd#622]
NSX-T edge gateway firewall requires new resource and this task is to track this work.

**Comment by raymonddejong** [comment]
If this is a new resource a technical requirement would be this resource supports NSX-T Policy API. In Policy API this is just the creation of a Group in which you specify IP(s), IP Set(s) and such. Documentation for the NSX-T provider with examples here: https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_group

**Comment by Didainius** [comment]
> If this is a new resource a technical requirement would be this resource supports NSX-T Policy API. In Policy API this is just the creation of a Group in which you specify IP(s), IP Set(s) and such. Documentation for the NSX-T provider with examples here: https://registry.terraform.io/providers/vmware/nsxt/latest/docs/resources/policy_group

We are consuming VCD API which does NSX-T configuration/API calls by itself. I believe it does use Policy API because VCD does have IP Sets, Security groups, and Application Profiles for firewall configurations.

**Comment by systems-levigo** [comment]
Thanks for the merge request!
We also need the implementation for NSX-T and would therefore be very happy about the merge.

**Comment by Didainius** [comment]
> Thanks for the merge request!
> We also need the implementation for NSX-T and would therefore be very happy about the merge.

Work is in progress about it. We already have code for prerequisites ( Security groups, IP sets and Application Port profiles.) (some are in PRs).
