### ISSUE TITLE
Error Refreshing Vapp after VM Creation

### ISSUE THREAD

**Issue by bagels-sec** [vmware/terraform-provider-vcd#626]
Hi there,

When trying to spin up a vm inside a newly created vapp I am getting a series of two errors, it appears to be possibly related to refreshing the vapp state after vm creation.

```
Error: [VM creation] error getting VM BTMDC01 : error refreshing vApp: error decoding response: strconv.ParseInt: parsing "17179869184": value out of range
```
```
Error: error finding Vapp: error decoding response: strconv.ParseInt: parsing "17179869184": value out of range
```

### Terraform Version
Terraform v0.14.4
+ provider registry.terraform.io/vmware/vcd v3.1.0

### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files
```
resource "vcd_vapp" "dcs" {
  name = "BTM" 
  power_on = true
}
resource "vcd_catalog" "demo_catalog" {
  name        = "Testcatalog"
  description = "OS templates Test"

  delete_force     = "true"
  delete_recursive = "true"
}
resource "vcd_catalog_item" "demo_linux" {
  catalog     = vcd_catalog.demo_catalog.name
  name        = "LinuxTest"
  description = "Linux VMTest"

  ova_path = "C:/tf/tenant/PhotonOS4test.ova"

  show_upload_progress = true
}
resource "vcd_vapp_org_network" "direct-network" {
  vapp_name         = vcd_vapp.dcs.name
  org_network_name  = "BTM-CORE-DC"
  depends_on = [vcd_vapp.dcs]
}
resource "vcd_vapp_vm" "dc01" {
  vapp_name     = "BTM"
  name          = "BTMDC01"
  catalog_name  = "Testcatalog"
  template_name = "LinuxTest"
  accept_all_eulas = "true"
  power_on = true
  memory        = 8192
  cpus          = 2
  network {
  type               = "org"
  name               = vcd_vapp_org_network.direct-network.org_network_name
    ip_allocation_mode = "DHCP"
  }
}
```

### Debug Output
[debug_out.log](https://github.com/vmware/terraform-provider-vcd/files/5850329/debug_out.log)

### Expected Behavior
A Vapp with the name BTM should be created.
A test photonOS image uploaded to it.
A VM named BTMDC01 should be created and powered on.

### Actual Behavior
Vapp Gets Created ok
Catalog gets created okay, OVA uploads fine
VM gets created but we then get the error "Error: error finding Vapp: error decoding response: strconv.ParseInt: parsing "17179869184": value out of range"

### Steps to Reproduce
1. `terraform plan -out main.tfplan`
2. `terraform apply main.tfplan`

### Important Factoids
1. terraform is being run from a windows host
2. VMware Cloud Director version: 10.2.0.17008054

**Comment by dataclouder** [comment]
Thanks for reporting this issue.
Tentatively, it could be the field `VirtualQuantity` in structure `VirtualHardwareItem`. It should be `int64` instead of `int`.
Needs investigation

**Comment by bagels-sec** [comment]
cheers @dataclouder , you were correct! :) 
I  have changed type from int to int64 and rebuilt - it now works.
I'll Create a pull request with fix.

**Comment by dataclouder** [comment]
Credit due to @Didainius who suggested that `VirtualQuantity` could be the culprit.

**Comment by Didainius** [comment]
@bagels-sec ,
I have looked at your PR https://github.com/vmware/go-vcloud-director/pull/355/files and I think this is not the place where it occurs. 
I have made an attempt to change field types in other place (https://github.com/vmware/go-vcloud-director/pull/354/commits/a0119e41f9a74225baa84f28e19d2f2cadc401ba)

Do you still have that exact image that triggered your error to validate it? I could link you to a specific Terraform version which uses my PR with changed type of VirtualQuantity

**Comment by bagels-sec** [comment]
@Didainius - Apologies, Go is not my native language.. yet!
Sure thing - I will be happy to test out if you can link me to a version with your PR applied.

**Comment by Didainius** [comment]
> @Didainius - Apologies, Go is not my native language.. yet!

No worries - this is not easy to get into a long lived library :)



> Sure thing - I will be happy to test out if you can link me to a version with your PR applied.

This PR https://github.com/vmware/terraform-provider-vcd/pull/628 will include it. (or you can directly checkout my branch https://github.com/Didainius/terraform-provider-vcd/tree/pr-openapi-routed-network). 
Not sure which OS you are using but if it supports `make` and you have Go - `make install` should do the trick

**Comment by kokkerhout** [comment]
I'm having trouble to "destroy" an existing vApp. 

When I add a vApp in main.tf. Run 'apply' it's created as expected.
When I remove the code in 'main.tf' and run 'apply' again it want's to destroy the vApp but it's unable to do it.

Can this be related to this bug?

**Comment by Didainius** [comment]
@kokkerhout ,
Doesn't sound like it as it is very specific. Could you open a separate github issue with your HCL definition and error details?

**Comment by bagels-sec** [comment]
Hey @Didainius - apologies about delay, I have now built and tested your PR (in Windows env) and it runs fine without any issues.

**Comment by Didainius** [comment]
Closing as PR https://github.com/vmware/terraform-provider-vcd/pull/628 fixed this.
