### ISSUE TITLE
network_isolated cannot modify static ip pool range

### ISSUE THREAD

**Issue by kokkerhout** [vmware/terraform-provider-vcd#627]
### Terraform Version
Terraform version 0.14.5

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_network_isolated

### Terraform Configuration Files
```hcl
    L2-network = {
      name                 = "L2-network"
      org                  = "myorg"
      vdc_name             = "myvdc"
      description          = "L2-networkk"
      gateway              = "192.168.1.1"
      dns1                 = "192.168.200.50"
      dns2                 = "192.168.200.51"
      dns_suffix           = "example.com"
      shared               = "true"
      static_start_address = "192.168.200.2"
      static_end_address   = "192.168.200.20"
```

### Debug Output
Please provide a link to GitHub [Gist(s)](https://gist.github.com) containing complete debug
output. You can enable debug by using the commands below:
```shell
 Error: error updating isolated network: error updating Org VDC network: [ParseErr]: error parsing error body for non-200 request: XML syntax error on line 6: element <hr> closed by </body> (&{Status:405 Not Allowed StatusCode:405 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Type:[text/html; charset=utf-8] Date:[Fri, 22 Jan 2021 16:01:36 GMT] Feature-Policy:[fullscreen 'self'] Referrer-Policy:[no-referrer-when-downgrade] Server:[nginx] Strict-Transport-Security:[max-age=31536000; includeSubDomains; preload] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] X-Xss-Protection:[1; mode=block]] Body:0xc000694060 ContentLength:-1 TransferEncoding:[chunked] Close:true Uncompressed:false Trailer:map[] Request:0xc000276e00 TLS:0xc0006ca0b0})

```

### Expected Behavior
Able to modify a existing static ip pool range to a different one

### Actual Behavior
Creating a new isolated network with a static ip pool works as expected. But when I want to change this static ip pool range on an existing range is errors out saying it cannot be done.
In the module vcd_network_routed it is possible to do this without any problems

### Steps to Reproduce
1. Modify code to:
      static_start_address = "192.168.160.2"
      static_end_address   = "192.168.160.11"

2. `terraform apply`

**Comment by Didainius** [comment]
Hello @kokkerhout,
Is this NSX-T or NSX-V network?

**Comment by kokkerhout** [comment]
Hi, it's NSX-V and VCD version 10.1.2.16779297

**Comment by Didainius** [comment]
@kokkerhout ,
Are you able to share how your `vcd_network_isolated` network definition looks. I see you have a variable definition which is then references in resource. The reason I am asking is that I have tried below example on 10.1.2 and it work. I suspect there might be specific set of field settings which may/may cause this error to occur and I need to replicate it.


```hcl
resource "vcd_network_isolated" "tf-net" {
  name         = "my-tf-net"
  gateway      = "172.20.0.1"

  shared = true

  static_ip_pool {
    start_address = "172.20.0.100"
    end_address   = "172.20.0.210"
  }
}
```

**Comment by kokkerhout** [comment]
`resource "vcd_network_isolated" "network_isolated" {
  for_each = var.network_isolated

  name                 = each.key
  org                  = each.value.org
  vdc                  = each.value.vdc_name
  description          = each.value.description
  gateway              = each.value.gateway
  dns1                 = each.value.dns1
  dns2                 = each.value.dns2
  dns_suffix           = each.value.dns_suffix
  shared               = each.value.shared

  dynamic "static_ip_pool" {
    for_each = lookup(each.value, "static_start_address", null)[*]
      content {
        start_address  = each.value.static_start_address
        end_address    = each.value.static_end_address
      }
  }
`
Here are my input variables;
`module "network_isolated" {
  source = "../../../modules/network_isolated/"

  network_isolated = {
    L2-net = {
      name                 = "L2-net"
      org                  = "dummy"
      vdc_name             = "vco-dummy"
      description          = "dummy's network"
      gateway              = "192.168.1.250"
      dns1                 = "192.168.1.251"
      dns2                 = "192.168.1.21"
      dns_suffix           = "dummy.example.com"
      shared               = "true"
      static_start_address = "192.168.1.10"
      static_end_address   = "192.168.1.249"
    }
  }
}
`

**Comment by Didainius** [comment]
@kokkerhout , some time has passed and we have introduced `vcd_network_isolated_v2`. Would you be able to try it and see if it actually works.
https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/network_isolated_v2

Feel free to reopen if it still doesn't.
