### ISSUE TITLE
Creating Windows VM with additional disks prevents guest customization from running

### ISSUE THREAD

**Issue by BHoggs** [vmware/terraform-provider-vcd#629]
Hi there,

When configuring a VM with guest customization and also attaching an internal disk at the same time, the VM seems to never run its customization sequence (configuring NIC, init scripts, etc). This appears to happen with *both* internal and independent disks.

Workarounds:
- Removing disk blocks in terraform restored expected behaviour
- Manually forcing re-customization a second time from either terraform or VCD UI causes customization to run successfully

### Terraform Version
Terraform v0.14.4
+ provider registry.terraform.io/vmware/vcd v3.1.0

### VCD Verison
9.7.0.16081827

### Affected Resource(s)
- vcd_vapp_vm
- vcd_vm_internal_disk

### Terraform Configuration Files
```hcl
resource "vcd_vapp" "test" {
    name = "Test"
}

resource "vcd_vapp_org_network" "web" {
    vapp_name        = vcd_vapp.test.name
    org_network_name = "Test Direct Network"
}

resource "vcd_vapp_vm" "web1" {
    vapp_name     = vcd_vapp.test.name
    name          = "TestVM1"
    computer_name = "TestVM1"
    catalog_name  = "SharedCatalogue"
    template_name = "W2k19 Std"

    memory    = 4096
    cpus      = 2
    cpu_cores = 1

    cpu_hot_add_enabled    = true
    memory_hot_add_enabled = true

    network {
        type               = "org"
        name               = vcd_vapp_org_network.web.org_network_name
        ip_allocation_mode = "MANUAL"
        ip                 = "10.0.0.1"
        connected          = true
    }

    customization {
        enabled                    = true
        change_sid                 = true
        allow_local_admin_password = true
        auto_generate_password     = true
    }

    override_template_disk {
        bus_type    = "sas"
        size_in_mb  = (100 * 1024)
        bus_number  = 0
        unit_number = 0
    }
}

resource "vcd_vm_internal_disk" "web1_d" {
    vapp_name        = vcd_vapp.test.name
    vm_name          = vcd_vapp_vm.web1.name
    bus_type         = "paravirtual"
    size_in_mb       = (50 * 1024)
    bus_number       = 1
    unit_number      = 0

    depends_on = [vcd_vapp_vm.web1]
}
```

### Expected Behavior
After a short while, VM should reboot and run guest customization.

### Actual Behavior
VM does not reboot. NIC not configured, left to DHCP setting.

### Steps to Reproduce
1. `terraform apply`
2. Wait several minutes after completion
3. log onto VM to verify if customization has been run (check NIC settings)

**Comment by vbauzysvmware** [comment]
Hi @BHoggs,

I take a look at the latest version of the provider and tried to replicate it. The internal disk doesn't reboot VM unless it's allowed and only for IDE disks.
Also please use 
```
 customization {
    force = true
...
```
This enables that the last reboot of VM resource will be with custimization.

I will close this issue. If we you see if that still ant issue please reopen and provide more information how to reproduce it.
