### ISSUE TITLE
vcd provider plugin crash when planning/reading broken vApps without VMs

### ISSUE THREAD

**Issue by pasikarkkainen** [vmware/terraform-provider-vcd#63]
While testing the current master branch of terraform-provider-vcd I noticed terraform (well, the plugin) will crash with a null pointer dereference when reading/syncing the state if there are vApps with no VMs inside..

"panic: runtime error: invalid memory address or nil pointer dereference"

This kind of case where there are vApps with no VMs inside obviously shouldn't happen, but it's possible someone manually/accidentally removed all the VMs from the Web Interface, but failed/forgot to remove the vApp itself.. which is exactly what happened in my case, when troubleshooting some other issue. So it can happen.

Also obviously terraform-provider-vcd plugin shouldn't crash in this case. The actual bug causing the null pointer dereference is easy to fix, I'll send a PR for govcloudair library.

But I have one question about handling this case properly in the vcd plugin side. Is it OK for the vcd provider plugin to automatically delete the (empty) vApp and rebuild/re-provision it again? Or should we error out and ask the user to fix the environment manually (the whole problem was caused by manually deleting the VMs outside of terraform, to begin with).

Thanks for the comments.

**Comment by Didainius** [comment]
No longer relevant as too much has changed. Should be opened with new details if it still exists.
