### ISSUE TITLE
vApp destroy errors

### ISSUE THREAD

**Issue by kokkerhout** [vmware/terraform-provider-vcd#632]
### Terraform Version
Terraform v0.14.5

### Affected Resource(s)
- vcd_vapp

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vcd = {
      source  = "vmware/vcd"
      version = ">=3.1.0"
    }
  }
  required_version = ">= 0.14.2"
}

resource "vcd_vapp" "vapps" {
  for_each = var.vapps

  name                 = each.key
  org                  = each.value.org
  vdc                  = each.value.vdc_name
  description          = each.value.description

}

```

### Debug Output
https://gist.github.com/kokkerhout/c1987cf94472b913ab59f22a2991b64b

### Expected Behavior
When I remove the code for vApp creation in main.tf 'terraform apply' tells me it will destroy the specific vApp and after typing in 'yes' it should remove the vApp

### Actual Behavior
After removing the code, running terraform apply and answering yes it errors telling me it's not able to remove the vApp

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Make code for creating vApp`
2. `terraform apply`
3. `creation succeeds`
4. `Remove code`
5. `terraform apply`
6. `terraform tells me it will destroy the vApp`
7. `Error`

**Comment by Didainius** [comment]
Hello @kokkerhout ,
I was looking at your issue. Could you give just a little bit more context about how full vApp and VM definitions look like? (do obfuscate names/descriptions if you need to).

The first problem I suspect is that  `vcd_vapp_vm` definitions might need `depends_on = [vcd_vapp.web]` definition. To give background - Terraform automatically sets dependencies  and graph (for create and delete) when `.id` field is used, but might run operations in parallel with `.name` references. That could cause Terraform to remove vApp even before all VMs are removed.

Just like in the other issue #633 I might ask you to include Go SDK for VCD logs by using https://registry.terraform.io/providers/vmware/vcd/latest/docs#logging flag.



Example below:
```hcl
resource "vcd_vapp" "web" {
  name = "web"

  depends_on = [
    # vcd_catalog.myNewCatalog,
    vcd_vapp.web,
  ]
}

resource "vcd_vapp_org_network" "tf-net" {
  vapp_name         = vcd_vapp.web.name
  org_network_name  = vcd_network_isolated.tf-net.name
  
  depends_on = [
    vcd_vapp.web,
  ]
}

resource "vcd_vapp_vm" "web" {
  count = 1

  vapp_name     = vcd_vapp.web.name
  name          = "web1-${count.index}"
  description = "VM-${count.index}"

  catalog_name  = "cat-dainius"
  template_name = "photon-hw11"

  memory        = 2048
  cpus          = 1

  network {
    type               = "org"
    name               = vcd_vapp_org_network.tf-net.org_network_name
    ip_allocation_mode = "POOL"
  }

  depends_on = [vcd_vapp.web]
}
```

**Comment by kokkerhout** [comment]
Well this problem occurs even when there is no vm deployed in the vApp and no networks are attached to it.
It's completly empty.
I will try to add the logging today.

**Comment by Didainius** [comment]
@kokkerhout , I am closing this as it got old and we got to a dead state Feel free to reopen if you have more inputs.
