### ISSUE TITLE
Error: error managing internal disks : [vm creation] disk with bus type paravirtual, bust number 0 and unit number 0 not found

### ISSUE THREAD

**Issue by patsevanton** [vmware/terraform-provider-vcd#637]
Hi! Thanks for terraform-provider-vcd!

### Terraform Version
```
v0.13.5 and v0.14.6
```

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "airflow" {
  count         = var.create_airflow == "true" ? 1 : 0
  vapp_name     = vcd_vapp.airflow.name
  name          = "airflow"
  catalog_name  = "Linux Templates"
  template_name = local.vm_template_name
  memory        = 8192
  cpus          = 4
  cpu_cores     = 2
  storage_profile = var.storage_profile
  network {
    type               = "org"
    name               = vcd_vapp_org_network.dev_vapp_network.org_network_name
    ip                 = cidrhost(local.net, 2)
    ip_allocation_mode = "MANUAL"

  }
  override_template_disk {
    bus_type         = "paravirtual"
    size_in_mb       = "10240"
    bus_number       = 0
    unit_number      = 0
    storage_profile = var.storage_profile
  }
  customization {
    enabled                    = true
    allow_local_admin_password = true
    admin_password             = var.host_pass
    auto_generate_password     = false
    initscript = local.dev_initscript
  }
  depends_on = [vcd_vapp.airflow]
}
```

Get error:
`Error: error managing internal disks : [vm creation] disk with bus type paravirtual, bust number 0 and unit number 0 not found`
change type 
`disk with bus type sas, bust number 0 and unit number 0 not found`
change unit number
`disk with bus type paravirtual, bust number 0 and unit number 1 not found`

If you just create a virtual machine, then tfstate will contain and don`t have error
```
"internal_disk":[
   {
      "bus_number":0,
      "bus_type":"parallel",
      "disk_id":"2000",
      "iops":0,
      "size_in_mb":32768,
      "storage_profile":"Tier B",
      "thin_provisioned":false,
      "unit_number":0
   }
],
```

**Comment by Didainius** [comment]
@patsevanton ,
Just checking - did you try to set `bus_type="parallel"` (together with bus and unit being 0) as the state later shows?

Is your goal to increase boot disk size before first boot? (This is what the setting is meant for).

**Comment by patsevanton** [comment]
With parallel will work.
Question: is Diffirent bus_type for centos and ubuntu ok for  terraform-provider-vcd?
or may be i create bad images?

**Comment by vbauzysvmware** [comment]
This feature allows you to increase the internal disk size existing vApp template, but you have to know the exact type of bus type, number, and unit number. It mean's `override_template_disk` block will match `internal_disk` interface in the vApp template and update it using other properties the user provided in that block.
