### ISSUE TITLE
Creation of VDCgroups

### ISSUE THREAD

**Issue by rvvliet78** [vmware/terraform-provider-vcd#659]
Hi,
Awesome to see NSX-T integration in the terraform provider!

In the documentation I couldn't find how to create a VDC group?
https://docs.vmware.com/en/VMware-Cloud-Director/10.2/VMware-Cloud-Director-Tenant-Portal-Guide/GUID-0F348033-72D9-447B-A1A5-0D8450237009.html

Is this still something that is being worked on, or do I lack search skills?

Thanks,

Rick

**Comment by Didainius** [comment]
Thanks for kind words - we don't yet have VDC group support as we are trying to cover up basic functionality first - NAT, firewall rules, etc...

**Comment by mkriegs** [comment]
Vote for Support this Feature
Its just SG that has 1n SGs as Members (The Scope of the GW is SG)
DFW Rules aren't far from this ;) 
Thanks for the work!

**Comment by mkriegs** [comment]
any Update here ?
best regards

**Comment by Didainius** [comment]
Sorry, but it won't make the 3.4.0 release.

**Comment by rvvliet78** [comment]
That is really unfortunate.
For us this is the main reason why we can't use terraform for deploying new tenants.
Is this feature on a roadmap with a timeline?

**Comment by jeroenvermeulen-01** [comment]
Same here, like to vote for this needed feature, a must have to make the next step.
Is there an indication/timeline for this feature?

**Comment by ZoranvR** [comment]
This would be of great help to our organisation also.

**Comment by kroot-dev** [comment]
This will be a very usefull features to roganisation use vcd and nsx-t like us.
In order to use dynamic security group (another request :) )

**Comment by mkriegs** [comment]
https://github.com/vmware/go-vcloud-director/pull/410
SDK is on the way :)

**Comment by vbauzysvmware** [comment]
Hi @mkriegs 
We are planning to add VDC groups managing support in the next release. Yet the possibility to reference in other resources will take more time. Allowing the use of VDC group instead of VDC may require additional API calls and may not support that automatically.

**Comment by mkriegs** [comment]
Hey @vbauzysvmware 
step by step. most interessting is that the EDGE attached to vdc group can be configured via terraform. this is not possible atm because the gateway additional id for the vdc group. (N-S Rules)
The DF can be done after that for Rules E-W.

**Comment by mkriegs** [comment]
any Update here ?
best regards

**Comment by vbauzysvmware** [comment]
Hi @mkriegs 

Please check the newest released 3.6.0 version of the provider which has major update to support for VDC groups.

If you find anything else missing for VDC group support, please report :) thank you
