### ISSUE TITLE
Can't set poweron to true with vcd_vapp_vm

### ISSUE THREAD

**Issue by nussera** [vmware/terraform-provider-vcd#661]
### Terraform Version
>terraform -v 
Terraform v0.14.7
+ provider registry.terraform.io/vmware/vcd v3.2.0

### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files
```hcl
resource "vcd_vapp_vm" "powerontest" {
  vapp_name     = "vApp_Build"
  name          = "nusseratest"
  computer_name = "nusseratest"
  memory        = 8192
  cpus          = 2
  cpu_cores     = 1

  os_type = "centos7_64Guest"
  hardware_version = "vmx-14"
  catalog_name  = "public-catalog-tsys-j"
  boot_image = "CentOS-7-x86_64-DVD-1602-99.iso"
  power_on = true
```

### Debug Output
https://gist.github.com/nussera/760cd36311290d5e6c76f81c047e1ec3

### Panic Output
None

### Expected Behavior
The vm should be powered on.

### Actual Behavior
An error is reported

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Powering on the machine via GUI works. There are two obvious differences.
1. The browser request doesn't contain any body.
2. The browser request utilized API version 33.0 while the provider uses 32.0

### References
None yet

**Comment by Didainius** [comment]
@nussera ,
Thanks for the issue - just to VCD version - are you on 10.0?

I see a very strange response:
```
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 2919793852439570563<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```


Do you have any WAF or other protection mechanisms in front of VCD?

**Comment by nussera** [comment]
Wow that's a fast response.

Unfortunately I can't tell you much about the VCD. It's outsourced. According to https://docs.vmware.com/de/VMware-Cloud-Director/index.html it should be version 10.0 I guess.

There is most likely a WAF (F5?) in front of the VCD.

I did some debugging myself. If I remove the empty xml from the POST request (via MITM proxy), it looks like it works.

FYI: I have a very similar issue when I try to instantiate a VM based description  https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm#example-usage-vapp-template-with-multi-vms . But this time it fails on the GET https://cloud.t-systems.at/api/query?&type=vm&filter=catalogName==CentOS+vdc04;containerName==template_CentOS7;name==ldcnew7;isVAppTemplate==true;status!=FAILED_CREATION;status!=UNKNOWN;status!=UNRECOGNIZED;status!=UNRESOLVED&links=true;&filterEncoded=true

**Comment by nussera** [comment]
I dump the offending poweron request:
```
POST /api/vApp/vm-a4bed7a3-04c7-407f-a44d-aa97c855246b/power/action/powerOn HTTP/1.1
Host: cloud.t-systems.at
User-Agent: terraform-provider-vcd/v3.2.0 (linux/amd64; isProvider:false)
Content-Length: 39
Accept: application/*+xml;version=32.0
Authorization: bearer *****
X-Vmware-Vcloud-Access-Token: *****
X-Vmware-Vcloud-Token-Type: Bearer
Accept-Encoding: gzip, deflate
Connection: close

<?xml version="1.0" encoding="UTF-8"?>

```
When you remove the xml body, the request is accepted.
Maybe this is an issue with the WAF too, but wouldn't it be nice if there was not pseudo empty body to begin with?

**Comment by Didainius** [comment]
> Maybe this is an issue with the WAF too, but wouldn't it be nice if there was not pseudo empty body to begin with?

Fair point. Would you care to try out a forked build which doesn't send XML headers when body is empty? I can create such fork, but I don't have a place to replicate this issue.

**Comment by nussera** [comment]
I had a look at it and the problem is actually in https://github.com/vmware/go-vcloud-director/blob/master/govcd/api.go#L611
How to proceed from here? Should I keep this issue open and create a new one in the go-vcloud-director project?

**Comment by Didainius** [comment]
@nussera ,
Probably I didn't express myself clearly - I have made such fork (https://github.com/Didainius/terraform-provider-vcd/tree/no-xml-header) which includes a patched go-vcloud-director repo https://github.com/vmware/go-vcloud-director/compare/master...Didainius:no-xml-header

I was just more interested if you could try it out on your end because I have no place to replicate the issue and cannot know if it helps.

Would you be able to build the provider plugin yourself from this branch https://github.com/Didainius/terraform-provider-vcd/tree/no-xml-header

Otherwise I could build it and put into some cloud sharing solution

**Comment by nussera** [comment]
And I already started to learn go... But I see your solution is much more elegant than mine and I can confirm that it works for me.

**Comment by Didainius** [comment]
Ok. So the next plan is - I will look at running all possible test suites on this fork and if this has no negative consequences it should be in next released version.

**Comment by nussera** [comment]
That sounds like a good plan. Thank you very much.

**Comment by Didainius** [comment]
SDK has a fixed and next Terraform provider version will pull it in.
https://github.com/vmware/go-vcloud-director/pull/370
