### ISSUE TITLE
Naming inconsistency between network resources

### ISSUE THREAD

**Issue by 8bitnz** [vmware/terraform-provider-vcd#662]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.14.9
+ provider registry.terraform.io/vmware/vcd v3.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_network
 
### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "vcd_vapp_network" "network" {
  name        = "Network"
  description = "Network"
  vapp_name = "vApp"

  gateway       = "${var.network_host}.254"

  static_ip_pool {
    start_address = "${var.network_host}.100" 
    end_address   = "${var.network_host}.149" 
  }

  dhcp_pool {
    start_address = "${var.network_host}.150" 
    end_address   = "${var.network_host}.199" 
  }
```

### Expected Behavior
Other network resources use dhcp_ip_pool as the IP Pool parameter block. 

dhcp pool block naming should be consistent between resources, suggest renaming dhcp_pool to dhcp_ip_pool to retain consistency between resources.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by Didainius** [comment]
@8bitnz ,
Thanks for spotting this. It is true - we always try to be consistent, but this slipped. We will try to improve on consistency as we go further.
