### ISSUE TITLE
Add possibility to generate UUID for internal/independent disk

### ISSUE THREAD

**Issue by skydion** [vmware/terraform-provider-vcd#665]
Hello,

Implementation of possibility to generate UUID for disks like it's in the vSphere provider.
As vCloud is higher level than vSphere I think it's possible to implement this feature.

Option can have the same name: **enable_disk_uuid**

```
resource "vcd_independent_disk" "system_disk" {
  for_each     = local.system_disks
  name         = "test
  size_in_mb   = each.value.size
  bus_type     = "SCSI"
  bus_sub_type = "VirtualSCSI"

  # new option
  enable_disk_uuid = true
}
```

**Comment by jpbuecken** [comment]
The provider can only implement what you can do via UI (or API). Is it possible to enable it per disk in the UI?

I'm not a developer, but a vmware customer as well, 
but from my own requests I know they like screenshots attached how you do it in UI :-)

Are you refering to the extra config 
disk.EnableUUID = "TRUE"
?
We tried to enable it via self made catalog items but an OVF import in a catalog will remove this configuration item for security reasons. We managed to import a version that had disk.EnableUUID = "TRUE" with VCD admins (import from vsphere), but it will show the vsphere uuid and not a VCD disk id (in vmware integrated openstack, it will show the openstack id as expected).

So if you found another option via VCD, I'm interested.

**Comment by skydion** [comment]
Hello,
I'm new to VCD and Vmware, so maybe this request can't be implement in provider, but we resolve this issue.

In general it looks like, first we should create vsphere template with options disk.enableUUID = "TRUE". Then export as OVF template. In the XML file should be the next code
`<vmw:ExtraConfig vmw:key="disk.enableUUID" vmw:value="true"/>`

In VCD we enabled possibility to send **disk.enableUUID** parameter, this should do vmware administrator form cmd
`/opt/vmware/vcloud-director/bin/cell-management-tool manage-config -n vapp.allowed.extra.config -v disk.enableUUID`
`service vmware-vcd restart`

For VCD user role should be enabled **vApp: Allow Matching Extra Config**
Also we use [article](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/94b8bd8d-74ff-4fe3-b7a4-41ae31516ed7/1b42f3b5-8b31-4279-8b3f-547f6c7c5aa8/doc/GUID-09603BC8-E49F-481A-A619-93208F606C3D.html) and this [article](https://kb.vmware.com/s/article/2148573)

**Comment by Didainius** [comment]
@skydion ,
I am closing this issue as I understand this is configuration option rather than something to do with Terraform resources. Feel free to comment/reopen otherwise
