### ISSUE TITLE
I can't create an Organisation with LDAP enabled and import a user.

### ISSUE THREAD

**Issue by donkerm** [vmware/terraform-provider-vcd#671]
Hi there,

I am searching for an option to create an organisation with LDAP mode: VMware Cloud Director system LDAP service.
Import user from ldap with certain rights. (I normally search on LDAP account name and assign a role)

### Terraform Version
Terraform v0.15.2
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.2.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_org
- vcd_org_user

### Terraform Configuration Files
Main.tf 

```
resource "vcd_org" "org1" {
  name                   = var.vcd_org_name
  full_name            = var.vcd_org_full_name
  description          = var.vcd_org_description
  is_enabled           = "true"
  delete_recursive  = "true"
  delete_force        = "true"

resource "vcd_org_user" "test_user" {
  name                            = "test_user"
  full_name                      = "test user"
  description                   = "Org user test_user"
  role                               = "Org Administratorr"
  enabled                        = true
  take_ownership            = true
  provider_type               = "INTEGRATED"
  stored_vm_quota         = 100
  deployed_vm_quota    = 100
  email_address              = "foo@foo.com"
}
```

###  Output

```
vcd_org.cloudandvirtualisation: Refreshing state... [id=urn:vcloud:org:7ffc8e37-b975-4a8f-bbc5-2c96d5aaadec]
vcd_org_group.cloudandvirtualisation: Creating...
╷
│ Error: unable to find role vAPP User: [ENF] entity not found 

```

### Expected Behavior
The thing I am hoping to achieve is the following:
-	Create an Organisation with enabled LDAP (2nd option VMWare Cloud Director system LDAP service)
-	Import user and assign a role (For example Org Admin or other).

### Actual Behavior
-	Organisation is created without LDAP settings.
-	User can’t be imported/created with rights.

### Steps to Reproduce
Create a simple Organisation and check indentity Providers -> LDAP (this is in the organization).

Manually I can perform this.

Regards,
Mischa

**Comment by Didainius** [comment]
Sorry - we don't have it yet, but as part of issue cleanup I will just close this in favor of #565
