### ISSUE TITLE
vcd_nsxv_ip_set

### ISSUE THREAD

**Issue by username-is-already-taken2** [vmware/terraform-provider-vcd#679]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.20
Provider 2.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
vcd_nsxv_ip_set

Came across this resource whilst reading the vapp_vm docs, I used it and it worked but couldn't find it in the documentation :)

**Comment by Didainius** [comment]
@username-is-already-taken2 ,
Didn't fully understand your query/issue. Is it about missing docs you couldn't find?

They should all be listed in https://registry.terraform.io/providers/vmware/vcd/latest/docs

There is issue with this particular resource `vcd_nsxv_ip_set ` which got named incorrectly - in docs:
`vcd_ipset`. Will have a look at it.
