### ISSUE TITLE
Add more values to attribute reference for vcd_storage_profile data source

### ISSUE THREAD

**Issue by jpbuecken** [vmware/terraform-provider-vcd#692]
According to documentation of provider 3.3 the only attribute reference is the "id"
https://registry.terraform.io/providers/vmware/vcd/latest/docs/data-sources/storage_profile

### Affected Resource(s)
- vcd_storage_profile (data source)

The new version should add Limit and IOPS parameters. In the UI of VCD 10.2.X it looks like this:

![image](https://user-images.githubusercontent.com/38046041/124583615-88943c00-de53-11eb-8b97-a7ae9ef6a493.png)

Not sure if this is possible with 10.1 and lower. Maybe it is possible via API, but UI is limited.

**Comment by vbauzysvmware** [comment]
Solved and change will be released in 3.6.

**Comment by jpbuecken** [comment]
Thanks, I appreciate it!
