### ISSUE TITLE
Using vcd provider to deploy nested ESXi

### ISSUE THREAD

**Issue by coughtrey** [vmware/terraform-provider-vcd#693]
### Issue/Setup:

We trying to automate a nested ESXi 7.0b host into our vCloud 10.2 lab. We are using the ova from virtuallyghetto; the ova is deployed as expected but none of the customization set it used. We are trying to make use of the guest_properties sections as in the below code. I'm wanting to understand if this type of deployment is supported and if so what am I missing in getting this working

### Terraform Version
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.3.0

### Affected Resource(s)
vcd_vapp_vm

###Script
`terraform {
  required_providers {
    vcd = {
      source = "vmware/vcd"
    }
  }
  required_version = ">= 0.13"
}

provider "vcd" {
  user                 = "${var.vcd_username}"
  password             = "${var.vcd_password}"
  org                  = "${var.vcd_org}"
  vdc                  = "${var.vcd_org_vdc}" 
  url                  = "${var.vcd_url}"
  allow_unverified_ssl = "true"
}
resource "vcd_vapp" "Windows_Nested_ESX" {
  name = "Windows_Nested_ESX"
}
resource "vcd_vapp_org_network" "vappOrgNet" {
  org                  = "${var.vcd_org}"
  vdc                  = "${var.vcd_org_vdc}" 
  vapp_name         = vcd_vapp.Windows_Nested_ESX.name
  org_network_name  = "TestLab"
}
resource "vcd_vapp_vm" "Windows_Nested_ESX" {
  vapp_name     = vcd_vapp.Windows_Nested_ESX.name
  name          = "Nested_ESX1"
  computer_name = "NestedESX1"
  catalog_name  = "Sandbox-Catalog"
  template_name = "Nested_ESXi7.0u1_Appliance_Template"
  memory        = 4096
  cpus          = 2
  cpu_cores     = 2

  network {
    type               = "org"
    name               = vcd_vapp_org_network.vappOrgNet.org_network_name
    ip_allocation_mode = "MANUAL"
    ip                 = "172.16.0.55"
    is_primary         = true
  }  
  guest_properties = {
  "guestinfo.hostname"   = "NestedESX1"
  "guestinfo.ipaddress"   = "172.16.0.55" 
  "guestinfo.netmask"   = "255.255.255.0"
  "guestinfo.gateway"   = "172.16.0.1"  
  "guestinfo.dns"   = "8.8.8.8" 
  "guestinfo.password"   = "p@ssw0rd"
  }  
}`

### Expected Behavior
We was hoping that the guest_properties would be used in the deployment

### Actual Behavior
Its all ignore and DCHP from our vApp networkis used. No names or other setting are changed

**Comment by Didainius** [comment]
@coughtrey , could you just give a try to deploy the OVA using UI and see if customization works. That way we could see if this is Terraform problem or the OVA does not accept customization.

Customization is always tricky and very much depends on image.

**Comment by Didainius** [comment]
Closing this for now.
@coughtrey , if you have new details - do ping us. Guest customization is always very tricky because there is no single standard. If you could make it work in UI and share some details, we could dig deeper inside there.
