### ISSUE TITLE
406 Not Acceptable / Invalid API version requested

### ISSUE THREAD

**Issue by jysantos** [vmware/terraform-provider-vcd#725]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.0.8
on linux_amd64

### Affected Resource(s)
Trying to import an existing media item

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vcd = {
      source = "vmware/vcd"
    }
  }
}

provider "vcd" {
  url = "https://XXX.XXX.XXX/api"
  org = "MyOrg"
  vdc = "MyOrg_VDC"
}

resource "vcd_catalog_media" "ootpa-iso" {
  catalog = "MyOrg-ISO"
  name    = "OracleLinux-R8-U4-x86_64-dvd.iso"
}
```

### Debug Output
https://gist.github.com/jysantos/1a415914a13469e17dc51fe6eebb525b

### Panic Output
N/A

### Expected Behavior
existing media item imported

### Actual Behavior
Error: error retrieving Org: MyOrg

### Steps to Reproduce
export VCD_USER=xxxxx
export VCD_PASSWORD=xxxxx
export VCD_IMPORT_SEPARATOR=: 
terraform import vcd_catalog_media.ootpa-iso MyOrg:MyOrg-ISO:OracleLinux-R8-U4-x86_64-dvd.iso

### Important Factoids
We're a tenant in a 3rd party managed VCD environment.  VCD version is 10.2.2.17855680.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
N/A

**Comment by dataclouder** [comment]
Hi,
Thanks for reporting this issue.
In order to reproduce the problem, I need to know which role you are using to perform the operation.
I tried the import with Organization Administrator, and it succeeds

**Comment by dataclouder** [comment]
Update: note that the error "406-not acceptable" is also returned when an invalid username or password is used.
While the errormessage needs to be improved, please validate your credentials to make sure you can access the VCD with them.

**Comment by jysantos** [comment]
I reset the password on my service account and it works fine now.  I agree, the error message is unhelpful in this case.  Thanks for your assistance.
