### ISSUE TITLE
Increasing a hard disk's size is resulting in VM shutdown

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [vmware/terraform-provider-vcd#728]
Hello friends 😃

I am facing an issue when trying to extend the disk size of an existing hard disk. The hard disk has been created using Terraform. When trying to increase the size of the disk via Terraform and deploy the changes, it causes the server to shutdown. However, the disk's size is successfully updated. 

When trying to manually extend a hard disk on the VMWare cloud platform, no reboot is required. So, I thought that it would be the same case when using the Terraform provider. Lastly, I experimented with the `allow_vm_reboot` parameter which did not improve the situation. The `bus_type` of the disk is `paravirtual`. Any feedback would be much appreciated.

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vm_internal_disk

### Terraform Configuration Files

```hcl
resource "vcd_vm_internal_disk" "vm_disk" {
  for_each = var.disks_map

  vapp_name       = each.value.vapp_name
  vm_name         = each.value.vm_name
  bus_number      = each.value.bus_number
  unit_number     = each.value.unit_number
  bus_type        = each.value.bus_type
  size_in_mb      = each.value.size_in_mb
  allow_vm_reboot = true
}
```

### Expected Behavior
Hard disk's size should have increased without causing a VM shutdown.

### Actual Behavior
Hard disk's size was increased but VM was shut down and was not turned on back automatically again.

**Comment by GeorgiosGoniotakis** [comment]
Hello @vbauzysvmware I hope my message finds you well. Is there any update on this please?

**Comment by vbauzysvmware** [comment]
Hi @GeorgiosGoniotakis I will look into this when I finish the current feature I am working on. I hope this happens soon.

**Comment by vbauzysvmware** [comment]
Hi @GeorgiosGoniotakis 

I checked the code and seems to be ok and tried to reproduce the case, but in the examples I used, VM wasn't restarted. 
For e.g. 

```
resource "vcd_vapp_vm" "TestAccVcdVAppVmWithVmSizingVM" {
  vapp_name     = vcd_vapp.TestAccVcdVAppVmWithVmSizing.name
  name          = "TestAccVcdVAppVmWithVmSizingVM"

  computer_name = "TestInternalDiskVmUnique"
  catalog_name  = "cat-vb"
  template_name = "photon-hw11"
  memory        = 1024
  cpus          = 1
  cpu_cores     = 1
}

resource "vcd_vm_internal_disk" "disk1" {
  vapp_name       = vcd_vapp.TestAccVcdVAppVmWithVmSizing.name
  vm_name         = vcd_vapp_vm.TestAccVcdVAppVmWithVmSizingVM.name
  bus_type        = "paravirtual"
  size_in_mb      = "14333"
  bus_number      = "1"
  unit_number     = "0"
  storage_profile = "*"
  allow_vm_reboot = "true"
}
```

could you provide more information? like HCL which makes VM restart, share also what terraform plan shows and logs.

**Comment by GeorgiosGoniotakis** [comment]
Hello @vbauzysvmware After extending the disk size we noticed that the server is shutting down, not rebooting. May I ask which version of the Terraform provider you used to reproduce this please?

**Comment by vbauzysvmware** [comment]
I found one issue and made a change. I hope it was you faced.

**Comment by GeorgiosGoniotakis** [comment]
Hello @vbauzysvmware Happy New Year! Sorry for the late reply. I tested the latest version of the provider last night and I can confirm that this has indeed been fixed. Thank you for having a look into that.

**Comment by vbauzysvmware** [comment]
Great, thank you for testing.
