### ISSUE TITLE
Data source missing for resource type vcd_org_group

### ISSUE THREAD

**Issue by skorhone** [vmware/terraform-provider-vcd#730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Managing access control rules in an environment with existing groups is proving to be quite difficult. Data  source for resource type vcd_org_group doesn't seem to be implemented. Considering that you already have implement resource type, I'd imagine adding data source would be trivial thing to do

│ The provider vmware/vcd does not support data source "vcd_org_group".
│ 
│ Did you intend to use the managed resource type "vcd_org_group"? If so, declare this using a "resource" block instead of a "data" block.

### Terraform Configuration (if it applies)

```hcl
data "vcd_org_group" "group-some_group" {
  name = "some_group"
}
```

**Comment by rvvliet78** [comment]
I think this is related to this issue:
https://github.com/vmware/terraform-provider-vcd/issues/659

**Comment by Didainius** [comment]
> I think this is related to this issue: #659

@rvvliet78 ,
If I see it correctly this is meant for referencing user groups (access) while #659 is meant to handle VDC groups (for cross VDC networking and firewalling).

**Comment by Didainius** [comment]
This was done by @adambarreiro
