### ISSUE TITLE
Error when setup network network configuration for vcd_vapp_vm

### ISSUE THREAD

**Issue by sssipaz** [vmware/terraform-provider-vcd#735]
### Terraform Version
Terraform v1.0.10 on windows_amd64
+ provider registry.terraform.io/hashicorp/vault v2.24.0
+ provider registry.terraform.io/vmware/vcd v3.4.0

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm

### Terraform Configuration Files
```
resource "vcd_test.local" "emptyVM" {
  vapp_name     = vcd_vapp.vmware_tutorial_vapp.name
  name          = "VmWithoutTemplate"
  computer_name = "emptyVM"
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1
  os_type          = "sles10_64Guest"
  hardware_version = "vmx-14"
  
  network {
    type               = "none"
    ip_allocation_mode = "NONE"
    connected          = false
  }
}
```

### Debug Output
2021/11/03 10:27:07 --------------------------------------------------------------------------------
2021/11/03 10:27:07 Request caller: govcd.(*VM).UpdateNetworkConnectionSection-->govcd.(*VM).UpdateNetworkConnectionSection-->govcd.executeRequestWithApiVersion-->govcd.(*Client).executeTaskRequest-->govcd.executeRequestCustomErr-->govcd.executeRequestCustomErr-->govcd.(*Client).newRequest
2021/11/03 10:27:07 PUT https://cdy.test.local/api/vApp/vm-4247e967-cef7-4c0a-adc7-93abd56e0b18/networkConnectionSection/
2021/11/03 10:27:07 --------------------------------------------------------------------------------
2021/11/03 10:27:07 Req header:
2021/11/03 10:27:07 	Accept: [application/*+xml;version=33.0]
2021/11/03 10:27:07 	X-Vmware-Vcloud-Token-Type: [Bearer]
2021/11/03 10:27:07 	Authorization: [********]
2021/11/03 10:27:07 	User-Agent: [terraform-provider-vcd/v3.4.0 (windows/amd64; isProvider:false)]
2021/11/03 10:27:07 	X-Vmware-Vcloud-Access-Token: [********]
2021/11/03 10:27:07 Request data: [629]
<?xml version="1.0" encoding="UTF-8"?>
  <NetworkConnectionSection xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" href="https://cdy.test.local/api/vApp/vm-4247e967-cef7-4c0a-adc7-93abd56e0b18/networkConnectionSection/" type="application/vnd.vmware.vcloud.networkConnectionSection+xml">
      <ovf:Info></ovf:Info>
      <PrimaryNetworkConnectionIndex>0</PrimaryNetworkConnectionIndex>
      <Link href="https://cdy.test.local/api/vApp/vm-4247e967-cef7-4c0a-adc7-93abd56e0b18/networkConnectionSection/" type="application/vnd.vmware.vcloud.networkConnectionSection+json" rel="edit"></Link>
  </NetworkConnectionSection>
2021/11/03 10:27:07 ################################################################################
2021/11/03 10:27:07 Response caller govcd.(*VM).UpdateNetworkConnectionSection-->govcd.(*VM).UpdateNetworkConnectionSection-->govcd.executeRequestWithApiVersion-->govcd.(*Client).executeTaskRequest-->govcd.executeRequestCustomErr-->govcd.checkRespWithErrType-->govcd.ParseErr-->govcd.decodeBody
2021/11/03 10:27:07 Response status 400 Bad Request
2021/11/03 10:27:07 ################################################################################
2021/11/03 10:27:07 Response header:
2021/11/03 10:27:07 	Content-Type: [application/vnd.vmware.vcloud.error+xml;version=33.0]
2021/11/03 10:27:07 	X-Vmware-Vcloud-Request-Execution-Time: [8]
2021/11/03 10:27:07 	Cache-Control: [no-store, must-revalidate]
2021/11/03 10:27:07 	Content-Length: [833]
2021/11/03 10:27:07 	Set-Cookie: [TS0101f65f=0161f31e9dd5aa2f1d1a93b6e331e288cf1e443d9f96af2b14ea710b914a8f6f3bb7801a2f57664a5130937bd18f293c3efc18fcb3; Path=/; Domain=.cdy.test.local]
2021/11/03 10:27:07 	Date: [Wed, 03 Nov 2021 06:27:25 GMT]
2021/11/03 10:27:07 	X-Vmware-Vcloud-Request-Id: [032b8eb7-8f04-450a-beac-2c8db17706a3]
2021/11/03 10:27:07 	X-Vmware-Vcloud-Ceip-Id: [0309bcc6-0c2d-4be1-bd9f-cd7e84f256ba]
2021/11/03 10:27:07 Response text: [833]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Error xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:ns2="http://www.vmware.com/vcloud/v1.5" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:ns9="http://www.vmware.com/vcloud/versions" message="[ 032b8eb7-8f04-450a-beac-2c8db17706a3 ] HTTP 400 Bad Request&#10; - cvc-elt.1.a: Cannot find the declaration of element 'NetworkConnectionSection'." majorErrorCode="400" minorErrorCode="BAD_REQUEST"/>

### Expected Behavior
New vapp VM should be created with network adapter not connected to any network.  At same time with same account I able to create VM on vcloud GUI or powerCLI with any kind of network type.

### Actual Behavior
Error displayed at creation time, VM been created. 

│ Error: unable to setup network configuration for empty VM error updating network connection: API Error: 400: [ 032b8eb7-8f04-450a-beac-2c8db17706a3 ] HTTP 400 Bad Request
│  - cvc-elt.1.a: Cannot find the declaration of element 'NetworkConnectionSection'.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
define vm or vapp_vm with any kind of network adapter and apply

### User Access rights 
Organization Administrator

**Comment by dataclouder** [comment]
Thanks for reporting an issue.

I could not reproduce the behavior using VCD 10.2.

```
resource "vcd_vapp" "newVapp" {
  name = "newVapp"
}

resource "vcd_vapp_vm" "emptyVM" {
  vapp_name        = vcd_vapp.newVapp.name
  name             = "VmWithoutTemplate"
  computer_name    = "emptyVM"
  memory           = 2048
  cpus             = 2
  cpu_cores        = 1
  os_type          = "sles10_64Guest"
  hardware_version = "vmx-14"

  network {
    type               = "none"
    ip_allocation_mode = "NONE"
    connected          = false
  }
}
```
The script above runs correctly.

Which version of VCD are you using?

I noticed that you mention `resource "vcd_test.local"`, instead of `resource "vcd_vapp_vm"`. Is that really the script you are using?

**Comment by sssipaz** [comment]
VCD  - 10.3

Correct config:

resource "vcd_vapp_vm" "emptyVM" {
  vapp_name     = vcd_vapp.vmware_tutorial_vapp.name
  name          = "VmWithoutTemplate"
  computer_name = "emptyVM"
  memory        = 2048
  cpus          = 2
  cpu_cores     = 1
  os_type          = "sles10_64Guest"
  hardware_version = "vmx-14"
  
  network {
    type               = "none"
    ip_allocation_mode = "NONE"
    connected          = false
  }
}

**Comment by dataclouder** [comment]
Tried again with VCD 10.3.0, org admin credentials, and  terraform 1.0.10 on Linux.
Same outcome. The apply works without errors.
Could you provide any other details that help reproduce the case?

**Comment by Didainius** [comment]
@sssipaz ,
I tried your exact example on Mac and Windows 10 - both worked for me.

**Comment by sssipaz** [comment]
That definitely should work, but I could do same task with GUI and PowerCLI and  I'm out of ideas what I do wrong.

**Comment by sssipaz** [comment]
Same when use UpdateNetworkConnectionSection in go-vcloud-director golang library, so I suppose this bug not at terraform provider.
