### ISSUE TITLE
vcd 3.4.0  vcd_vapp_vm Error: error finding catalog name: [ENF] entity not found

### ISSUE THREAD

**Issue by neticenet** [vmware/terraform-provider-vcd#744]
Hello!

After updating the provider to version 3.4.0, I cannot create vcd_vapp_vm. I get:
Error: error finding catalog okd: [ENF] entity not found
Although on version 3.1.0 it works fine.

### Terraform Version
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/vmware/vcd v3.4.0

### Affected Resource(s)
vcd_vapp_vm

### Terraform Configuration Files

resource "vcd_vapp_vm" "vms" {
  name                 = "test-vm"
  catalog_name         = "okd"
  template_name        = "okd-templ"
  memory               = 8192
  cpus                 = 2
  storage_profile      = "SSD"
}

data "vcd_org" "my-org" {
  name   = var.VCD_ORG
}

data "vcd_org_vdc" "my-org-vdc" {
  org     = var.VCD_ORG
  name    = var.VCD_VDC
}

### Panic Output

│ Error: error finding catalog okd: [ENF] entity not found
│ 
│   with vcd_vapp_vm.vms,
│   on main.tf line 58, in resource "vcd_vapp_vm" "vms":
│   58: resource "vcd_vapp_vm" "vms" {
│ 

###  Additional Information
The code runs correctly on version 3.1.0
The code ends with a bug on versions 3.3.1, 3.4.0

### References
- Issue #689

**Comment by Didainius** [comment]
@neticenet ,
We had this bug and fixed in 3.3.1 (at least I hope so). Does 3.2.0 work for you?

Now I need more information on what kind of catalog you have. Is it shared? Any more specific on the catalog and also a log bundle would most probably be required to understand.

**Comment by neticenet** [comment]
@Didainius,
3.2.0 work
3.3.0 not work
3.3.1 not work
3.4.0 not work

My catalog "OKD"  catalog type Shared. 
https://my_cloud/tenant/my_org/libraries/vapp-templates

**Comment by Filsbo** [comment]
catalog_name = **"okd"**

Catalog name is case sensitive.
You need written in capital letters catalog name.

> My catalog "OKD" catalog type Shared. https://my_cloud/tenant/my_org/libraries/vapp-templates

**Comment by neticenet** [comment]
@Filsbo 
The Catalog name in the code is specified in the correct case.

**Comment by Didainius** [comment]
@neticenet,
Could you share logs as described in the Bug Report (https://github.com/vmware/terraform-provider-vcd/issues/new?assignees=&labels=&template=Bug_Report.md)

**Comment by neticenet** [comment]
There is no such possibility.
Top-up checks
terraform version 3.1.0, 3.2.0 value catalog_name, searches in "vApp Templates", and versions 3.3.0 and older in "Catalogs"
"vApp Templates" = https://my_cloud/tenant/my_org/libraries/vapp-templates
"Catalogs" = https://my_cloud/tenant/my_org/libraries/catalogs

**Comment by Didainius** [comment]
The lookup did change in 3.3.0 since it did not work the same way after API bump. What type of image do you use? is it ova?
I need to replicate it somehow - can you give some guide?

**Comment by neticenet** [comment]
@Didainius 
The format is not ova.
Instruction, I just create one virtual server from the previously prepared vApp Templates.
Can you tell us more about changes to search and api changes?

**Comment by vbauzysvmware** [comment]
Hi @neticenet 
Could you share how this vAPP template is stored in VCD? share screenshot with details?

**Comment by Didainius** [comment]
This looks to be stuck. Closing it. @neticenet , can you share additional details if the issue persists with latest provider version.

Thanks
