### ISSUE TITLE
`boot_image` does not seem to be set when using a vcd_vm

### ISSUE THREAD

**Issue by timstoop** [vmware/terraform-provider-vcd#749]
### Terraform Version
```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.4.0
```

### Affected Resource(s)
- vcd_vm

### Terraform Configuration Files

```hcl
resource "vcd_catalog" "MyCatalog" {
  name             = "Install"
  description      = "Installation media"
  delete_recursive = "true"
  delete_force     = "true"
}

resource "vcd_catalog_media" "ipxe-iso" {
  catalog     = vcd_catalog.MyCatalog.name
  name        = "ipxe.iso"
  description = "iPXE boot image"
  media_path  = "media/ipxe.iso"
}

resource "vcd_vm" "test1" {
  name = "test1"
  org  = var.vcd_org
  vdc  = data.vcd_org_vdc.my.name

  computer_name    = "test1"
  memory           = 2048
  cpus             = 1
  cpu_cores        = 1
  power_on         = true
  description      = "Test VM"
  os_type          = "debian10_64Guest"
  hardware_version = "vmx-14"

  # Initial boot media
  catalog_name = vcd_catalog.MyCatalog.name
  boot_image   = vcd_catalog_media.ipxe-iso.name
}
```

### Debug Output
Please let me know if this is necessary, it seems to contain a lot of sensitive info and I rather not put that on the internet without sanitising it some more.

### Expected Behavior
The VM should have started using the image provided, but only once.

### Actual Behavior
The default VMXNET3 PXE boot firmware is started instead.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### User Access rights 
Tenant Role - Organisation Administrator

### Important Factoids
When creating a VM using the same boot image in the Director interface, it works as expected. So I do not think this is a access rights issue. Sadly, there seem no way from the interface to determine the boot image that was originally set, so I cannot check if the VM was created with the correct options.

Happy to provide additional information!

**Comment by timstoop** [comment]
Only checked the issues, but this actually seems related to #714. My provider is providing me with `VMware Cloud Director version: 10.1.2.16779297`. Hope this helps.

**Comment by vivek99singh** [comment]
I am facing the same issue.

**Comment by vbauzysvmware** [comment]
I will check and try to add to the next release if it is issue mentioned #714.

**Comment by dataclouder** [comment]
I have tested #714 and it seems not to have side effects. Will Check more and eventually merge it if nothing else comes up
