### ISSUE TITLE
Add dnsServers to vcd_nsxt_network_dhcp

### ISSUE THREAD

**Issue by forestEagle** [vmware/terraform-provider-vcd#753]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* 

### Description

Hi,
Since the vCloud Director web ui (and API) now supports adding the DNS option to the NSX-T Segment DHCP server, I'd like to see this implemented in the Terraform resource.

Thanks :)

### New or Affected Resource(s)

* vcd_nsxt_network_dhcp

**Comment by nakasix** [comment]
Hello,

Yes this feature would be very useful for me too :)

`vcd_nsxt_network_dhcp => https://{vcd_host}/tenant/{tenant}/domain-networking/org-networks/urn:vcloud:network:{network_id}/ipam/dhcp-nsxt/dhcp-general`

Also, is it possible to provide DNS functionality for the NSX-T gateway itself?

`vcd_nsxt_edgegateway => https://{vcd_host}/provider/cloud/edge-gateways/cloud/urn:vcloud:gateway:{gateway_id}/ip-management/dns`

Regards,

**Comment by mikeletux** [comment]
Hello @forestEagle and @nakasix ,

I've been working on this feature. The PR is already in place. Please check https://github.com/vmware/terraform-provider-vcd/pull/830

This feature will be aimed for next release v3.7.0. Please keep in mind we release once every quarter.
As soon as the PR that implements this feature is merged, I'll proceed to close this issue.

@nakasix Regarding implementing DNS functionality for the NSX-T gateway, please open up another issue as I'd like to keep this one for the original feature.

Thanks!

**Comment by mikeletux** [comment]
Folks, PR merged into main.
This feature will be available in next release v3.7.0. 

I'm closing this issue. 🚀
