### ISSUE TITLE
Edge Gateway routing configuration with vcd provider

### ISSUE THREAD

**Issue by FabienMTP** [vmware/terraform-provider-vcd#755]
Hello,

Is it possible to configure the routing settings (Route Advertisement and BGP) of the Routing part of NSX-T Edge Gateways WebUI with the vcd provider?

![screen01](https://user-images.githubusercontent.com/94961239/144582629-f73d506b-f622-4458-9c04-93e3d915673f.jpg)

I did not find any useful reference in the vcd provider resources documentation.

If not:
-  Do you plan to create the corresponding resources and if yes do you have an approximate date of release?
- I found nsxt resources nsxt_policy_bgp_neighbor to configure this part with nsxt provider but nothing about route advertisement. Do you confirm?
- Do you think that it will be OK to configure nsxt_policy_bgp_neighbor with nsxt resources? Or is it mandatory to configure this part from NSX-T Edge Gateways WebUI (or vcd provider when it will be available) ?

Regards.

**Comment by Didainius** [comment]
Hello @FabienMTP,
> o you plan to create the corresponding resources and if yes do you have an approximate date of release?

Yes we do plan to accommodate BGP and route advertisement. There is no exact date but I would guesstimate for 2022H1.

> I found nsxt resources nsxt_policy_bgp_neighbor to configure this part with nsxt provider but nothing about route advertisement. Do you confirm?

Sorry, but we don't maintain the `nsxt` provider (only `vcd`). You could pose a query in https://github.com/vmware/terraform-provider-nsxt for `nsxt` provider things.

> Do you think that it will be OK to configure nsxt_policy_bgp_neighbor with nsxt resources? Or is it mandatory to configure this part from NSX-T Edge Gateways WebUI (or vcd provider when it will be available) ?

I can't really completelly answer that as we are "consumers" of VCD itself (not developers). If you can make VCD have all the data (shown in UI) - you will be able to `import` reources once we have them. But if VCD UI doesn't show it -  it will not work.

**Comment by FabienMTP** [comment]
Wow. Thanks for the FAST response. Have a nice day.

**Comment by Didainius** [comment]
3.7.0 is released and it support these features.
