### ISSUE TITLE
Allow resource vcd_catalog to be created using suscribe to external catalog functionality

### ISSUE THREAD

**Issue by vbauzys** [vmware/terraform-provider-vcd#776]
When the catalog is published externally and the subscription URL is accessible, then a new catalog can be created using that URL.

![image](https://user-images.githubusercontent.com/41415459/150149326-5b9825cf-3a8e-431a-9cb7-1d912b734e09.png)

**Comment by dataclouder** [comment]
Implemented in PR #916
