### ISSUE TITLE
Allow vcd_catalog resource to share catalog to other users or other Orgs

### ISSUE THREAD

**Issue by vbauzys** [vmware/terraform-provider-vcd#777]
![image](https://user-images.githubusercontent.com/41415459/150151888-f1e4b127-ddc7-4914-a032-9e04ad461d03.png)

**Comment by Didainius** [comment]
We have resource [vcd_catalog_access_control](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/catalog_access_control) for that
