### ISSUE TITLE
NSX-T Dynamic Security Group support

### ISSUE THREAD

**Issue by Didainius** [vmware/terraform-provider-vcd#787]
I am splitting this issue based on comment in https://github.com/vmware/terraform-provider-vcd/issues/459#issuecomment-1035009487

The original issue #459 is to track work for security tags, while this issue will focus on Security Dynamic Groups. We already have [vcd_nsxt_security_group](https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/nsxt_security_group) for **Static Group** management. The resource name is a bit misleading now, but that is how the endpoint was named during development and dynamic security groups were introduced. They use the same API endpoint, but dynamic security groups are a bit more complicated because of their capabilties.

They are found in UI:
![image](https://user-images.githubusercontent.com/15804230/154420146-b172173b-a2af-476d-b541-0ae40ef22557.png)

**Comment by storbel** [comment]
@Didainius actually both exist static and dynamic security Group, i suppose naming the resource as vcd_nsxt_dynamic_security_group is not a bad idea. 
Do you have any clue in what version this resource will be implemented? i believe this is a critical resource for anybody dealing with the 10.3+ version of vCloud.

**Comment by storbel** [comment]
@mikeletux i believe you are also concerned by the comment above, as you are assigned on this enhancement.

**Comment by mikeletux** [comment]
Hello there @storbel 
We are planning to include this resource in the next release. First we had to go ahead with the security tags and now we are able to move with this forward.
Stay tuned for next release!

**Comment by Didainius** [comment]
3.7.0 is released and it contains this feature.
