### ISSUE TITLE
VM from template without OS does not apply CPU and Mem configs in 1.0

### ISSUE THREAD

**Issue by StupidScience** [vmware/terraform-provider-vcd#79]
### Terraform Version
Terraform v0.11.1

### Affected Resource(s)
vcd_vapp_vm

### Terraform Configuration Files
```
provider "vcd" {
  version              = "~> 1.0"
  user                 = "${var.vcd_user}"
  password             = "${var.vcd_pass}"
  org                  = "${var.vcd_org}"
  url                  = "${var.vcd_url}"
  vdc                  = "${var.vcd_vdc}"
  max_retry_timeout    = 6000
  allow_unverified_ssl = true
}

resource "vcd_vapp_vm" "new_vm" {
  vapp_name     = "${var.vm_vapp}"
  name          = "${var.vm_name}"
  catalog_name  = "Blank"
  template_name = "Blank"
  memory        = "${var.vm_mem}"
  cpus          = "${var.vm_cpu}"
  power_on      = "${var.vm_poweron}"
  network_name  = "${var.vm_network}"
  ip            = "${var.vm_ipaddress}"
}
```

### Expected Behavior
VM should be created with specified parameters.

### Actual Behavior
VM created, network configs updated, but CPU and Memory configs don't updating and terraform infinitely (till timeout) notify `Still creating...`
VM at this moment just Powered Off and not in updating state.

### Steps to Reproduce
I try to use template of VM that doesn't have any installed OS then:
1. `terraform apply -var 'vm_poweron=false' -auto-approve`

**Comment by StupidScience** [comment]
With provider version 0.1.1 everything is ok

**Comment by Didainius** [comment]
This one is now way too old and allocations have changed at least a few times.
