### ISSUE TITLE
Add Attribute "Name in vSphere" to vcd_vapp_vm ressource

### ISSUE THREAD

**Issue by bogi0704** [vmware/terraform-provider-vcd#791]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since the VCD Terraform provider still needs some work to implement all NSX-T features, we are looking at ways to circumvent this by using the NSX-T native Terraform provider in tandem. We want to configure everything as code, even if that means we have to use different providers.
More specifically we want to add Tags to VMs in NSX-T Manager by using the following datasources and ressources:

```hcl
data "nsxt_policy_vm" "nsxt_vm1" {
  display_name = vcd_vapp_vm.frontend.name
}

resource "nsxt_policy_vm_tags" "vm1_tags" {
  instance_id = data.nsxt_policy_vm.nsxt_vm1.instance_id

  tag {
    scope = "color"
    tag   = "blue"
  }

  tag {
    scope = "env"
    tag   = "test"
  }
}
```

In order for this to work the vcd_vapp_vm.frontend.name has to be unique. Since we do not want to make arbitrary random strings on VMs a requirement, we would like to use the "Name in vSphere" attribute. That name is already unique accross VCD, NSX-T Manager and vSphere, so I would like to use that instead.

### New or Affected Resource(s)

* vcd_vapp_vm

**Comment by lvirbalas** [comment]
Hello,

> Since the VCD Terraform provider still needs some work to implement all NSX-T features

This is an ongoing priority. Which features are you missing exactly?

CC: @Didainius

**Comment by bogi0704** [comment]
Hi,

thanks for asking :) Most of them are already known in the form of existing issues, but here is a list of things that we need:

1. The edge gateway ressource is currently incompatible with Data Center Groups. I need to be able to create the edge gateway and increase it's scope to the entire Data Center Group. Issue: #763 
2. I currently cannot assign tags to VMs and use those tags in dynamic groups. Issues: #787 and #459
3. There is currently no ressource with which I can configure the distributed firewall settings. Issue: #144 

We would be able to deploy entire VM Stacks with the appropriate firewall and network settings defined as code. This is our goal. That is why we are currently looking to go the nsxt native provider way, as long as the vcd provider needs work on that end.

Since we are a managed service provider the following ressources would also be nice to have:

1. I would like to setup the customer IdP via a tf ressource. Issue: #565
2. I would like to setup the sharing of individual OrgVDCs to specific users via tf. Issue: #785 

Ping me if you need some more information here, glad to help.

**Comment by bogi0704** [comment]
This request is not required anymore, since all of the first 3 points have been adressed natively in VCD with version 3.7 of the terraform provider. Thanks for that!
I will be closing this issue because of that.
