### ISSUE TITLE
ignore_changes does not respect the metadata property for a vcd_vapp_vm

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [vmware/terraform-provider-vcd#792]
Hello everyone 😄 

I hope everyone is in good health.

We are using version `3.5.1` of the provider to provision VM resources on an NSX-T environment. When trying to create a VM for the first time everything works properly. Any further deployments highlight a change in the metadata property of a `vcd_vapp_vm` resource which triggers a refresh of the state. Using the `ignore_changes` property as shown on the code snippet below does not fix the issue. 

Any suggestions would be much appreciated.

### Affected Resource(s)
- vcd_vapp_vm

### Terraform Configuration Files

```hcl
resource "vcd_vapp_vm" "vms" {
  for_each = var.vm_map

  catalog_name                   = each.value.catalog_name
  template_name                  = each.value.template_name
  vapp_name                      = each.value.vapp_name
  power_on                       = each.value.power_on
  name                           = each.value.name
  computer_name                  = each.value.computer_name
  description                    = each.value.description
  cpus                           = each.value.cpus
  cpu_cores                      = each.value.cpu_cores
  cpu_hot_add_enabled            = each.value.cpu_hot_add_enabled
  expose_hardware_virtualization = each.value.expose_hardware_virtualization
  guest_properties               = each.value.guest_properties
  memory                         = each.value.memory
  memory_hot_add_enabled         = each.value.memory_hot_add_enabled
  hardware_version               = each.value.hardware_version

  dynamic "network" {
    for_each = each.value.networks
    content {
      type               = network.value["type"]
      name               = network.value["name"]
      adapter_type       = network.value["adapter_type"]
      is_primary         = network.value["is_primary"]
      ip                 = network.value["ip"]
      ip_allocation_mode = network.value["ip_allocation_mode"]
      connected          = network.value["connected"]
    }
  }

  dynamic "customization" {
    for_each = each.value.customizations
    content {
      enabled    = customization.value["enabled"]
      change_sid = customization.value["change_sid"]
    }
  }

  lifecycle {
    ignore_changes = [metadata]
  }
}
```

### Expected Behavior
Changes in the `metadata` property should be ignored.

### Actual Behavior
Changes in the `metadata` property are triggering a state refresh.

**Comment by bogi0704** [comment]
Hi @GeorgiosGoniotakis,

agree on this, I am noticing the same behavior. Terraform just wants to refresh the state, but this is not something I want or need.
I am also looking at ways to ignore changes to whole groups of metadata entries, like for example "meta.*". I can ignore specific ones, but I was unable to use a wildcard to ignore multiple metadata entries.

**Comment by GeorgiosGoniotakis** [comment]
I discovered that the same issue is happening when using `ignore_changes` with the properties `status` and `status_text` of a `vcd_vapp` resource.

**Comment by Didainius** [comment]
I am closing this issue because Terraform provider developers do not have control over `lifecycle` paramters. These are provided by Hashicorp  Terraform itself and we don't even access these details to handle ignores.
