### ISSUE TITLE
 terraform-provider-vcd_v3.5.1 plugin when creating vcd_nsxt_firewall with terraform

### ISSUE THREAD

**Issue by hungbui78** [vmware/terraform-provider-vcd#808]
Hello,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved
for bug reports and feature requests. For general usage questions, please see:
https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

`Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.5.1`

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_nsxt_firewall

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```
resource "vcd_nsxt_firewall" "testing" {
  org = var.vcd_org # Default for resources
  vdc = var.vcd_vdc # Default for resources

  edge_gateway_id = var.vcd_edgegw_id

  rule {
    action      = "ALLOW"
    name        = "allow-all-IPv4-traffic"
    direction   = "IN"
    ip_protocol = "IPV4"
  }

}
```

### Debug Output
Please provide a link to GitHub [Gist(s)](https://gist.github.com) containing complete debug
output. You can enable debug by using the commands below:
```shell
export TF_LOG_PATH=tf.log            
export TF_LOG=TRACE                  
export GOVCD_LOG_FILE=go-vcloud-director.log
export GOVCD_LOG=true     
```

On Windows the command instead of `export` is `set`.

Replicate the issue after setting the environment variables listed above and it should create two
new files in the working directory: `tf.log` and `go-vcloud-director.log`. The `tf.log` is a general
Terraform debug log (more information about it is in
https://www.terraform.io/docs/internals/debugging.html) while the `go-vcloud-director.log` is a
specific log file for `terraform-provider-vcd` containing debug information about performed API
calls. Please attach both of them to your [Gist](https://gist.github.com).

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
```
vcd_nsxt_firewall.testing: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with vcd_nsxt_firewall.testing,
│   on security.tf line 36, in resource "vcd_nsxt_firewall" "testing":
│   36: resource "vcd_nsxt_firewall" "testing" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vcd_v3.5.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaa1a27]

goroutine 48 [running]:
github.com/vmware/go-vcloud-director/v2/govcd.(*Vdc).GetNsxtEdgeGatewayById(0xc00030afe0, {0xc000876140, 0x37})
        github.com/vmware/go-vcloud-director/v2@v2.14.0/govcd/nsxt_edgegateway.go:39 +0x107
github.com/vmware/terraform-provider-vcd/v3/vcd.(*VCDClient).GetNsxtEdgeGatewayById(0xc00086f740, {0xc0003042a6, 0xc00086f5f0}, {0xc00012a200, 0xc088d623a90b6a70}, {0xc000876140, 0xc0005ecb10})
        github.com/vmware/terraform-provider-vcd/v3/vcd/config.go:490 +0xc6
github.com/vmware/terraform-provider-vcd/v3/vcd.resourceVcdNsxtFirewallCreateUpdate({0xf18398, 0xc000879260}, 0xc00004db00, {0xdbd140, 0xc000544230})
        github.com/vmware/terraform-provider-vcd/v3/vcd/resource_vcd_nsxt_firewall.go:137 +0x1de
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000482ee0, {0xf18328, 0xc00034e400}, 0x2, {0xdbd140, 0xc000544230})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:341 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000482ee0, {0xf18328, 0xc00034e400}, 0xc0004f15f0, 0xc00004d980, {0xdbd140, 0xc000544230})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003009f0, {0xf18328, 0xc00034e400}, 0xc00062aa50)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00004c500, {0xf183d0, 0xc0002e61e0}, 0xc0005500e0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd87b20, 0xc00004c500}, {0xf183d0, 0xc0002e61e0}, 0xc0008780c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fee00, {0xf29f28, 0xc0002b4000}, 0xc000376100, 0xc0004ddce0, 0x14b6660, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0001fee00, {0xf29f28, 0xc0002b4000}, 0xc000376100, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-vcd_v3.5.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
### Expected Behavior
What should have happened?
Expect provider to create a firewall rule

### Actual Behavior
What actually happened?
The plugin crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### User Access rights 
Information about user used. Role and/or more exact rights if it is customized.

### Important Factoids
Is there anything atypical about your accounts that we should know?

### References
No

**Comment by Didainius** [comment]
Hello,
Tiny clarification - is your edge gateway in a VDC Group.

**Comment by hungbui78** [comment]
> 

Hi Didainius.

Yes I think so.  I need to double checked it with our VMware admin.

BR

Hung

**Comment by Didainius** [comment]
I expect so. This provider does not yet support vdc groups. next version 3.6.0 will add at least some support for vdc groups.

**Comment by hungbui78** [comment]
> I expect so. This provider does not yet support vdc groups. next version 3.6.0 will add at least some support for vdc groups.

Aha, ty Didainius. Will next version also add terraform ability to sets distributed firewall? Because I can´t not find any resources for that.

Br

Hung

**Comment by Didainius** [comment]
I very much hope so. In fact I am working on that resource now.
