### ISSUE TITLE
Add OpenID Identity Provider - OIDC

### ISSUE THREAD

**Issue by Nannymeta** [vmware/terraform-provider-vcd#827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Configure OpenID Connect (OIDC) for Identity providers
* Import groups from OpenID Connect (OIDC)

### New or Affected Resource(s)

* vcd_org_group

### References

* Issue #827

**Comment by adambarreiro** [comment]
Hi @Nannymeta,

PR #1263 added the `vcd_org_oidc` resource and data source to the main branch, so it will be part of 3.13.0 release.
In the meantime, you can try this new feature by building the provider manually, checking out the repo and running `make install`.

Documentation: https://github.com/vmware/terraform-provider-vcd/blob/main/website/docs/r/org_oidc.html.markdown

Feel free to provide any feedback.

Thanks!
