### ISSUE TITLE
Creating VM with vcd_vm failed with error 

### ISSUE THREAD

**Issue by hungbui78** [vmware/terraform-provider-vcd#829]
Hi.

We have faced a very strange thing whilst creating av VM using vcd_vm resource. It fails when trying to do customazitions. But when we use vcd_vapp_vm resource it works as expected.

rror: error setting guest customization during creation: error applying guest customization details: task for setting guest customization section failed: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ df1356f8-4e20-43c3-a8e2-4c85153a00b0 ] Unable to perform this action. Contact your cloud administrator.
│ 
│   with vcd_vm.TestVm,
│   on standalone_vm.tf line 1, in resource "vcd_vm" "TestVm":
│    1: resource "vcd_vm" "TestVm" {

Hello,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved
for bug reports and feature requests. For general usage questions, please see:
https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

~/cloudops-aws-examples/cgi-onpreem-cloud-team1$ terraform -v
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.6.0

Your version of Terraform is out of date! The latest version
is 1.1.8. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_vapp_vm
- vcd_network_routed_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
Copy-paste your Terraform configurations here. Please **shrink HCL replicating the bug to minimum** 
without modules. It will help us to respond and replicate the problem quicker. It may also uncover
some HCL error while doing so.

For bigger configs you may use [Gist(s)](https://gist.github.com) or a service like Dropbox and
share a link to the ZIP file.

resource "vcd_vm" "TestVm" {
  name = "TestVm"
  computer_name = "Test-vm"

  catalog_name  = "CGI-Templates"
  template_name = "EC2_Ubuntu1804"
  cpus          = 2
  memory        = 2048

  network {
    name               = "TFPOCTeam1-Dev"
    type               = "org"
    ip_allocation_mode = "POOL"
  }

}
```

### Debug Output
Please provide a link to GitHub [Gist(s)](https://gist.github.com) containing complete debug
output. You can enable debug by using the commands below:
```shell
export TF_LOG_PATH=tf.log            
export TF_LOG=TRACE                  
export GOVCD_LOG_FILE=go-vcloud-director.log
export GOVCD_LOG=true     
```

On Windows the command instead of `export` is `set`.

Replicate the issue after setting the environment variables listed above and it should create two
new files in the working directory: `tf.log` and `go-vcloud-director.log`. The `tf.log` is a general
Terraform debug log (more information about it is in
https://www.terraform.io/docs/internals/debugging.html) while the `go-vcloud-director.log` is a
specific log file for `terraform-provider-vcd` containing debug information about performed API
calls. Please attach both of them to your [Gist](https://gist.github.com).

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
VM creation not failing while doing customazation 

### Actual Behavior
What actually happened?
VM creation is failing while doing customazation 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### User Access rights 
Information about user used. Role and/or more exact rights if it is customized.

### Important Factoids
Is there anything atypical about your accounts that we should know?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Issue #0000
[go-vcloud-director.log](https://github.com/vmware/terraform-provider-vcd/files/8520563/go-vcloud-director.log)
[tf.log](https://github.com/vmware/terraform-provider-vcd/files/8520564/tf.log)

**Comment by Didainius** [comment]
Hello @hungbui78 ,
Could you share a bit more details on the env - I just did create both types of VMs - in vApp and standalone without any issues here (attached my exact snippet)

* Can you try with Org admin role?
* It looks like you were using API Access token, could you try to use username/password?
* Just double checking - is the snippet you pasted is exactly the one that causes error?
* Did this work with previous versions of Terraform Provider for VCD or are you just trying it out using 3.6.0 now?



```hcl
data "vcd_org_vdc" "vdc1" {
  org  = "datacloud"
  name = "nsxt-vdc-datacloud"
}

data "vcd_nsxt_edgegateway" "t1" {
  org      = "datacloud"
  owner_id = data.vcd_org_vdc.vdc1.id
  name     = "nsxt-gw-datacloud"
}

resource "vcd_network_routed_v2" "nsxt-backed" {
  org  = "datacloud"
  name = "routed-one"

  edge_gateway_id = data.vcd_nsxt_edgegateway.t1.id

  gateway       = "1.1.1.1"
  prefix_length = 24

  static_ip_pool {
    start_address = "1.1.1.10"
    end_address   = "1.1.1.20"
  }

  static_ip_pool {
    start_address = "1.1.1.100"
    end_address   = "1.1.1.103"
  }
}

resource "vcd_vm" "TestVm" {
  vdc           = "nsxt-vdc-datacloud"
  name          = "TestVm"
  computer_name = "Test-vm"

  catalog_name  = "cat-datacloud"
  template_name = "photon-hw11"
  cpus          = 2
  memory        = 2048

  network {
    name               = vcd_network_routed_v2.nsxt-backed.name
    type               = "org"
    ip_allocation_mode = "POOL"
  }
}

resource "vcd_vapp" "vapp" {
  vdc  = "nsxt-vdc-datacloud"
  name = "vapp-one"
}

resource "vcd_vapp_org_network" "vappOrgNet" {
  vdc = "nsxt-vdc-datacloud"

  vapp_name = vcd_vapp.vapp.name

  # Comment below line to create an isolated vApp network
  org_network_name = vcd_network_routed_v2.nsxt-backed.name
}

resource "vcd_vapp_vm" "inVApp" {
  vdc           = "nsxt-vdc-datacloud"
  name          = "TestVm"
  vapp_name     = vcd_vapp.vapp.name
  computer_name = "Test-vm"

  catalog_name  = "nsxt-cat"
  template_name = "photon3"
  cpus          = 2
  memory        = 2048

  network {
    name               = vcd_vapp_org_network.vappOrgNet.org_network_name
    type               = "org"
    ip_allocation_mode = "POOL"
  }
}
```

**Comment by hungbui78** [comment]
Hi Didainius.

Ty for your reply. Down are the answers to your questions.

> * Can you try with Org admin role?
 -- We are using the tenant admin to do terraform. The user should have same permission as Org admin
> * It looks like you were using API Access token, could you try to use username/password?*
-- Tried  just few mins ago with user and password but gets same error
> * Just double checking - is the snippet you pasted is exactly the one that causes error?
-- Yes. Here is the snipped again with a freash apply 
```
╷
│ Error: error setting guest customization during creation: error applying guest customization details: task for setting guest customization section failed: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ a01f0565-d9fc-41df-951a-917a28d14248 ] Unable to perform this action. Contact your cloud administrator.
│ 
│   with vcd_vm.TestVm,
│   on standalone_vm.tf line 1, in resource "vcd_vm" "TestVm":
│    1: resource "vcd_vm" "TestVm" {
│ 
```
 
> * Did this work with previous versions of Terraform Provider for VCD or are you just trying it out using 3.6.0 now?
 -- No, same error on provider version 3.5.1
 
 
 I also added fresh logs when using password and username instead of token
 Br

Hung 

[tf.log](https://github.com/vmware/terraform-provider-vcd/files/8528297/tf.log)
[go-vcloud-director.log](https://github.com/vmware/terraform-provider-vcd/files/8528298/go-vcloud-director.log)

**Comment by Didainius** [comment]
This is very confusing as I don't see what is explicitly wrong there. More thoughts for now:
* Do you have any other VCD environment to rule out that this particular environment has some problems?
* Can you see the failing task in VCD? Maybe it has more details than  `500`. `500` is usually not a good error on VCD side as it is more or less unhanded.

One more thought - try adding this snippet to VM to explicitly disable customization:
```
  customization {
    enabled = false
  }
```

**Comment by hungbui78** [comment]
> This is very confusing as I don't see what is explicitly wrong there. More thoughts for now:
> 
> * Do you have any other VCD environment to rule out that this particular environment has some problems?
   -- I tried it against another tenant with same error
> * Can you see the failing task in VCD? Maybe it has more details than  `500`. `500` is usually not a good error on VCD side as it is more or less unhanded.
  -- I can only see this in VCD.
  ```
Operation:
Updated Virtual Machine TestVm(d868e1a5-999e-4041-8e5e-07d2179e7656)
Job ID:
dcb38453-8137-4264-8464-228114a67f56
Object:
TestVm
Type:
vm
Status:
Failed
Organization:
TFPOCTeam2
Initiator:
k_hubu
Start Time:
04/21/2022, 01:26:53 PM
Completion Time:
04/21/2022, 01:26:54 PM
Service Namespace:
com.vmware.vcloud
Details:
[ 168ab5ac-c0c9-4251-9e52-227864621889 ] Unable to perform this action. Contact your cloud administrator.
 ``` 
> 
> One more thought - try adding this snippet to VM to explicitly disable customization:
> 
> ```
>   customization {
>     enabled = false
>   }
> ```

--- Added the `enabled = false for the customiziton block` but still same error

**Comment by vbauzysvmware** [comment]
Hi @hungbui78 

Could you check VCD logs. As `Unable to perform this action. Contact your cloud administrator.` usually mean VCD internal issues.

**Comment by vbauzysvmware** [comment]
Hi,

Is it possible to ask your ENV administrator to check the logs of VCD? as we can't reproduce the issue is not possible for us to identify the possible culprit.

**Comment by hungbui78** [comment]
> Hi,
> 
> Is it possible to ask your ENV administrator to check the logs of VCD? as we can't reproduce the issue is not possible for us to identify the possible culprit.

HI.

Yes, I reached out to ENV admin yesterday regarding the logs. Waiting for answer from them.

BR

Hung

**Comment by hungbui78** [comment]
Ty all for the help and advices.

We have now found the error and it was in the configuration of the VCD tentant. The missing configuration has now been applied and is now working to create VM with vcd_vm resource.

BR

Hung

**Comment by vbauzysvmware** [comment]
Hi @hungbui78 

Glad to hear and thank you for letting us know.
