### ISSUE TITLE
Feature Request: Administrative operations shoud also be possible

### ISSUE THREAD

**Issue by vMarkusK** [vmware/terraform-provider-vcd#83]
Hi there,

at the moment the Plugin v1 only supports operations as a Tenant. From a Service Provider perspective is would be an awsome enhancement if also administrative operations are possible.

Examples:
- Create new Org
- Create OrgVDC
- Create Edge Gateway
- Manage Storage Policys
- Manage Roles and Permissions

**Comment by Didainius** [comment]
Closing this as it is really old and quite a few operations are there for providers (althout not all)
