### ISSUE TITLE
Malformed http GET request for catalogs

### ISSUE THREAD

**Issue by nussera** [vmware/terraform-provider-vcd#831]
Hello,

This only happens when applying a new vApp. Existing vApps are not effected.
During the initial modificiation check, a request in the form of
`GET /api/query?&filter=orgName==tma;name==CentOS vdc04&type=catalog&filterEncoded=true`
is sent. This is invalid as the blank between "CentOS" and "vdc04" is not URL encoded. 
The correct request would be
`GET /api/query?&filter=orgName==tma;name==CentOS%20vdc04&type=catalog&filterEncoded=true` with the blank being URL encoded as '%20'

### Terraform Version
Terraform v1.1.9 on linux_amd64

```
Initializing provider plugins...
- Finding vmware/vcd versions matching ">= 3.5.0"...
- Using previously-installed vmware/vcd v3.6.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- datasource vcd_catalog

### Terraform Configuration Files

```hcl
data "vcd_catalog" "centos_cataloge" {
  org  = var.org_name
  name = "CentOS vdc04"
}
```

### Debug Output
IMHO there isn't much useful debug output. The error speaks for itself.
```
Applying modifications
╷
│ Error: unable to retrieve catalog record - error decoding query results: XML syntax error on line 1: element <br> closed by </body>
│ 
│   with module.datasources.data.vcd_catalog.centos_cataloge,
│   on ../../modules/datasources/main.tf line 10, in data "vcd_catalog" "centos_cataloge":
│   10: data "vcd_catalog" "centos_cataloge" {
│ 
╵
ERRO[0005] 1 error occurred:
        * exit status 1
```

### Panic Output
None

### Expected Behavior
`terraform apply` works.

### Actual Behavior
The request `GET /api/query?&filter=orgName==tma;name==CentOS vdc04&type=catalog&filterEncoded=true` gets rejected.

### Steps to Reproduce
1. Define a new vApp and let it use a data source with a blank ' ' in its name.
2. `terraform apply`

### User Access rights 
N/A

### Important Factoids
N/A

### References
N/A

**Comment by vbauzysvmware** [comment]
Fix will be released in 3.7.0 version.
