### ISSUE TITLE
Error: Invalid API version for external_network_V2 data source

### ISSUE THREAD

**Issue by Zypheros** [vmware/terraform-provider-vcd#832]
### Terraform Version
```
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.6.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- datasource vcd_external_network_v2

### Terraform Configuration Files

```hcl
data "vcd_external_network_v2" "t0" {
  name = "<Name of a tier0 gateway>"
}
```

### Debug Output

There isn't much useful information in the debug output, the error message speaks for itself.
```
PS > terraform plan
╷
│ Error: could not find external network V2 by name 'REDACTED': could not find external network by name: error getting all pages for endpoint https://REDACTED/cloudapi/1.0.0/externalNetworks/: error in HTTP GET request: NOT_ACCEPTABLE - The request has invalid accept header: Invalid API version requested. Supported API versions are: [37.0.0-alpha, 36.2, 36.1, 36.0, 35.2, 35.0, 34.0, 33.0 [D], 32.0 [D], 31.0 [D]] ([D] indicates deprecated versions)
│
│   with data.vcd_external_network_v2.t0,
│   on main.tf line 1, in data "vcd_external_network_v2" "t0":
│    1: data "vcd_external_network_v2" "t0" {
```

### Expected Behavior
The data source should have returned the specified gateway.

### Actual Behavior
The request gets rejected by the api.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### User Access rights 
N/A

### Important Factoids
I did some testing with python directly towards the API and found out that the api only accepts the `application/json` header:
 `"Accept": "application/json;version=36.2"`
Maybe it can help.

### References
N/A

**Comment by vbauzysvmware** [comment]
Hi @Zypheros 

which VCD version did you use to get this error?

**Comment by Zypheros** [comment]
Hi, our VCD version is: 10.3.2.19173133

**Comment by Zypheros** [comment]
Hi. It turns out I have been trying to use the data source mentioned on a nsx-t tier 0 gateway so it makes sense this does not work. Sorry for wasting your time.

-Endre
