### ISSUE TITLE
Error: Invalid API version requested for vcd_nsxt_manager data source

### ISSUE THREAD

**Issue by Zypheros** [vmware/terraform-provider-vcd#836]
### Terraform Version
```
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.6.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- data vcd_nsxt_manager 

### Terraform Configuration Files

```hcl
data "vcd_nsxt_manager" "main" {
  name = "my-nsxt-manager"
}

data "vcd_nsxt_tier0_router" "router" {
  name            = "my-tier0-gateway"
  nsxt_manager_id = data.vcd_nsxt_manager.main.id
}
```

### Debug Output

tf log: https://gist.github.com/Zypheros/934d6edd3f47dd966ce5312d04d578e8
go log: https://gist.github.com/Zypheros/777278521e21c7ee221d2ab12a3cd5f6

### Panic Output
N/A

### Expected Behavior
The data source should have returned the nsx-t manager

### Actual Behavior
Terraform returned an error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform plan

### User Access rights 
N/A

### Important Factoids
Did some testing with python and it seems the `application/json` does not work for this API request:
```py
def getBearerToken():
    # Get bearer token
    auth2 = requests.post(
        "https://cloud-director/oauth/provider/token?grant_type=refresh_token&refresh_token=<TOKEN>",
        verify=False,
    )
    access_token = "Bearer " + auth2.json()["access_token"]
    sc_headers = {
        "Authorization": f"{access_token}",
        "Accept": "application/json;version=36.3",
    }
    return sc_headers

def getNSXmanager():
    vcd_response = requests.get("https://cloud-director/api/query?&type=nsxTManager&filterEncoded=true&filter=name==my-nsxt-manager", verify=False, headers=getBearerToken())
    print(json.dumps(vcd_response.text, indent=4, sort_keys=True))


getNSXmanager()
```

vcd_response:
```
{  "minorErrorCode" : "NOT_ACCEPTABLE",  "message" : "The request accept header is invalid.",  "stackTrace" : "javax.ws.rs.ClientErrorException: HTTP 406 Not Acceptable
```

This header is also present in the go logs on line 101 -> 103:

```log
2022/04/26 10:56:18 Req header:
2022/04/26 10:56:18 	Content-Type: [application/json]
2022/04/26 10:56:18 	User-Agent: [terraform-provider-vcd/v3.6.0 (windows/amd64; isProvider:true)]
```

When using this header the python script works and returns the nsx-t manager:
```py
    sc_headers = {
        "Authorization": f"{access_token}",
        "Accept": "application/*+xml;version=36.3",
    }
    return sc_headers
```

### References
N/A

**Comment by Didainius** [comment]
Can you share some details what kind of environment is it? Is it self-hosted VCD or is it a CDS instance? As I see it looks to be 10.3.3?
We are not sending `Accept` header at all in our requests and it has not caused any errors on our test environments. This surprises me a bit you see such error. Do you see it only for this resource?

**Comment by Zypheros** [comment]
Hi. Yes, this is a self hosted VCD appliance based, on version 10.3.3. 
I have not seen this error on any other resources no, but I can do some testing and see if it shows.

**Comment by Zypheros** [comment]
I removed the accept header from the python script and got this error message:
```log
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:ns9="http://www.vmware.com/vcloud/versions" message="The request has invalid accept header: Invalid API version requested. Supported API versions are: [37.0.0-alpha, 36.3, 36.2, 36.1, 36.0, 35.2, 35.0, 34.0, 33.0 [D], 32.0 [D], 31.0 [D]] ([D] indicates deprecated versions)" majorErrorCode="406" minorErrorCode="NOT_ACCEPTABLE"/>

```

**Comment by Zypheros** [comment]
Update: 
I tried the vcd_nsxt_tier0_router data source and got the same error
```
│ Error: could not find NSX-T Tier-0 router by name 'tier0' in NSX-T manager urn:vcloud:nsxtmanager:ID: could not find NSX-T Tier-0 router with name 'tier0' for NSX-T manager with id 'urn:vcloud:nsxtmanager:ID': error getting all pages for endpoint https://cloud-director/cloudapi/1.0.0/nsxTResources/importableTier0Routers: error in HTTP GET request: NOT_ACCEPTABLE - The request has invalid accept header: Invalid API version requested. Supported API versions are: [37.0.0-alpha, 36.3, 36.2, 36.1, 36.0, 35.2, 35.0, 34.0, 33.0 [D], 32.0 [D], 31.0 [D]] ([D] indicates deprecated versions)
```
I copied the get request from the go logs to the python script and it worked there, but now only with 
`"Accept": "application/json` header.

**Comment by Zypheros** [comment]
I'm sorry for wasting your time (again). Had a typo in the password for the sysadmin account, this is not my day.

-Endre
