### ISSUE TITLE
vcd_role and vcd_org_user not working when using api token as authentication method

### ISSUE THREAD

**Issue by hungbui78** [vmware/terraform-provider-vcd#839]
Hi.

I have a problem with vcd_role and vcd_org_user resources, when I using api token as authentication method then the following resources gives error. If I changed the authentication to user and password instead it works.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.6.0
```

Your version of Terraform is out of date! The latest version
is 1.1.9. You can update by downloading from https://www.terraform.io/downloads.html
### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_role 
- vcd_org_user

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
Copy-paste your Terraform configurations here. Please **shrink HCL replicating the bug to minimum** 
without modules. It will help us to respond and replicate the problem quicker. It may also uncover
some HCL error while doing so.

For bigger configs you may use [Gist(s)](https://gist.github.com) or a service like Dropbox and
share a link to the ZIP file.


resource "vcd_role" "CloudOps-test-role" {
org         = var.vcd_org
name        = "CloudOps-test-role-admin"
description = "Testing creation of roles from terraform"
       rights = [
    	   
                  ]
 }

resource "vcd_org_user" "cloudops-testare" {
org         = var.vcd_org

name        = "cloudops-testare"
description = "Test to create new user with terraform"
role        = "CloudOps-test-role-admin"
password    = "change-me"
 }
```

### Debug Output
Please provide a link to GitHub [Gist(s)](https://gist.github.com) containing complete debug
output. You can enable debug by using the commands below:
```shell
export TF_LOG_PATH=tf.log            
export TF_LOG=TRACE                  
export GOVCD_LOG_FILE=go-vcloud-director.log
export GOVCD_LOG=true     
```

On Windows the command instead of `export` is `set`.

Replicate the issue after setting the environment variables listed above and it should create two
new files in the working directory: `tf.log` and `go-vcloud-director.log`. The `tf.log` is a general
Terraform debug log (more information about it is in
https://www.terraform.io/docs/internals/debugging.html) while the `go-vcloud-director.log` is a
specific log file for `terraform-provider-vcd` containing debug information about performed API
calls. Please attach both of them to your [Gist](https://gist.github.com).

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
It should create user and role

### Actual Behavior
Gets error

```
vcd_role.CloudOps-test-role: Creating...
╷
│ Error: [role create] error creating role CloudOps-test-role-admin: error creating role: error in HTTP POST request: ACCESS_TO_RESOURCE_IS_FORBIDDEN - [ 76ce6576-d46d-4320-a5f4-7eb530dfc839 ] This operation is denied.
│ 
│   with vcd_role.CloudOps-test-role,
│   on role_and_permissions.tf line 13, in resource "vcd_role" "CloudOps-test-role":
│   13: resource "vcd_role" "CloudOps-test-role" {
│ 
╵
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### User Access rights 
Tenant admin rights and error only when using api token.

### Important Factoids
Is there anything atypical about your accounts that we should know?

No

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Issue #0000
[go-vcloud-director.log](https://github.com/vmware/terraform-provider-vcd/files/8589347/go-vcloud-director.log)
[tf.log](https://github.com/vmware/terraform-provider-vcd/files/8589348/tf.log)

**Comment by vbauzysvmware** [comment]
Hi @hungbui78 
As documentation states:

![image](https://user-images.githubusercontent.com/41415459/165912344-4715a63b-c526-4c97-9e7f-2bb5365cf2fd.png)

I think it's logical that you don't work with users right when you use api token as you can make very strange things :)
