### ISSUE TITLE
Attach a routed network with vApp to SSH into the VMs

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [vmware/terraform-provider-vcd#847]
This ticket is not a bug report but is intended to clarify confusion regarding the vCloud Director infrastructure that I'm trying to build. 

### Terraform Configuration Files

```hcl
# Existing edge gateway in VDC
data "vcd_edgegateway" "edge_gateway" {
  name = var.vcd_edge_gateway_name
  org  = var.vcd_org_name
  vdc  = var.vcd_vdc_name
}

# Routed network that will be connected to the edge gateway
resource "vcd_network_routed_v2" "network" {
  name        = "cluster-network"
  org         = var.vcd_org_name

  edge_gateway_id = data.vcd_edgegateway.edge_gateway.id

  interface_type = distributed

  gateway       = 192.168.100.1
  prefix_length = 24

  static_ip_pool {
    start_address = 192.168.100.2
    end_address   = 192.168.100.254
  }
}

# Dedicated vApp for cluster resources; vms, disks, network.
resource "vcd_vapp" "cluster" {
  name        = cluster
  org         = var.vcd_org_name
  vdc         = var.vcd_vdc_name

  depends_on = [vcd_network_routed_v2.network]
}

# Connect the dedicated routed network to vApp
resource "vcd_vapp_org_network" "network" {
  vapp_name        = cluster
  org_network_name = vcd_network_routed_v2.network.name

  # It's a pre-requisite for configuring Firewall and NAT rules per vApp
  is_fenced = true

  depends_on = [vcd_vapp.cluster, vcd_network_routed_v2.network]
}

resource "vcd_vapp_firewall_rules" "vapp-fw" {
  org = var.vcd_org_name
  vdc = var.vcd_vdc_name

  vapp_id        = vcd_vapp.cluster.id
  network_id     = vcd_vapp_org_network.network.id
  default_action = "drop"

  rule {
    name             = "allow-ssh"
    policy           = "allow"
    protocol         = "tcp"
    destination_port = "22"
    destination_ip   = "any"
    source_port      = "any"
    source_ip        = "0.0.0.0/0"
  }
}

resource "vcd_vapp_vm" "control_plane" {
  count         = 2
  vapp_name     = cluster
  name          = "cluster-${count.index + 1}"
  computer_name = "cluster-${count.index + 1}"

  guest_properties = {
    "hostname" = "root"
    "password" = "password"
  }

  catalog_name  = var.catalog_name
  template_name = var.template_name

  memory                 = 2048
  cpus                   = 2
  cpu_cores              = 1

  network {
    type               = "org"
    name               = vcd_vapp_org_network.network.org_network_name
    ip_allocation_mode = "POOL"
    is_primary         = true
  }

  depends_on = [vcd_vapp_org_network.network]
}
```

### Expected Behavior
What should have happened?

An isolated `vApp` is created with VMs that can interact with each other, SSH is possible, and external services that are outside of the VDC are accessible. Currently, this only gets assigned a private IP address and thus is not accessible over the internet which is my first concern. Do i need DNAT and SNAT rules in this case? 

Also, I'd preferably like maximum isolation for my VMs so maybe I can resort to a bastion host for external access as well. 

### Additional Details

Currently, since I'm new to vCloud director the networking part is not coherent. If there are resources over the internet that you think can help, do share. 

End goal is to install a Kubernetes cluster in this VCD setup.

@Didainius based on our conversation over email this is the ticket that I have opened. Let's move the conversation here and I'll ask questions along the way, as per your suggestion.

P.S. Since I couldn't find enough documentation regarding my scenario, which seems pretty common, maybe this is something I can eventually contribute towards in the `examples` section.

**Comment by lvirbalas** [comment]
> End goal is to install a Kubernetes cluster in this VCD setup.

K8s-only or CSE?

**Comment by ahmedwaleedmalik** [comment]
Only K8s, not with the CSE.

**Comment by ahmedwaleedmalik** [comment]
Another detail would be that I'd prefer for NAT, SNAT, and firewall settings to be configured per vApp instead of the gateway, is that even possible? The reason is that I'd like the ability to replicate the same set-up to create multiple isolated clusters. Would `vcd_vapp_firewall_rules` and `vcd_vapp_nat_rules` be sufficient for that? I think it isn't enough and I'll still need **vcd_nsxv_firewall_rule, vcd_nsxv_dnat, and vcd_nsxv_snat** is that true?

**Comment by Didainius** [comment]
Hello @ahmedwaleedmalik,
This team works more on Terraform provider VCD support rather than digs very deep at architecture level of VCD app deployment. If you're not sure what exactly you're trying to build - it might help to poke in the UI and/or also check [official docs of VCD](https://docs.vmware.com/en/VMware-Cloud-Director/index.html) as this team doesn't consist of  real solution integration experts of VCD. This Terraform provider here just helps to achieve your desired state using code.

That being said - there is no single way to deal with networks and it depends on your access level and wishes:
* If you're using routed network for your VMs, then you should use Edge Gateway DNAT/SNAT to do port forwarding to your VM for SSH or other traffic as only edge gateway has external IP. Routed network is attached to edge gateway so DNAT/SNAT + Firewall rules help to forward traffic to your desired VM.
* You could use `direct` network and attach it to VMs directly. This would directly assign external IP to each of your VMs. If you want traffic isolation then - you could have a few NICs. One - for networks interconnecting VMs at vApp level , the other external traffic access.

**Comment by ahmedwaleedmalik** [comment]
> This team works more on Terraform provider VCD support rather than digs very deep at architecture level of VCD app deployment.

@Didainius thank you, that is understandable. I'm going through the documentation alongside as well.

It's just that the network topology that I want to garner is a bit unclear. That's probably on me since I'm probably not an expert in that domain.

**Comment by ahmedwaleedmalik** [comment]
> If you're using routed network for your VMs, then you should use Edge Gateway DNAT/SNAT to do port forwarding to your VM for SSH or other traffic as only edge gateway has external IP. Routed network is attached to edge gateway so DNAT/SNAT + Firewall rules help to forward traffic to your desired VM. Option 2 in my current setup is not possible.

This is exactly what I was trying to and did implement. Although I still am unable to SSH into my VM, from my local machine. Although the DNAT and SNAT rules are configured.

Do you have any idea what I'm doing wrong here?

```hcl
resource "vcd_nsxv_firewall_rule" "rule_ssh" {
  edge_gateway = data.vcd_edgegateway.edge_gateway.name
  name         = "ssh"
  action = "accept"

  source {
    ip_addresses = ["any"]
  }

  destination {
    ip_addresses = [data.vcd_edgegateway.edge_gateway.default_external_network_ip]
  }

  service {
    protocol = "tcp"
    port     = 22
  }
}

resource "vcd_nsxv_dnat" "rule_internet_ssh" {
  edge_gateway = data.vcd_edgegateway.edge_gateway.name
  network_type = "ext"
  network_name = local.external_network

  original_address = data.vcd_edgegateway.edge_gateway.default_external_network_ip
  original_port    = 22

  translated_address = vcd_vapp_vm.control_plane[0].network[0].ip
  translated_port    = 22
  protocol           = "tcp"
}
```
