### ISSUE TITLE
Allow to create VM without template

### ISSUE THREAD

**Issue by xcompass** [vmware/terraform-provider-vcd#85]
### Terraform Version
Terraform v0.11.3
+ provider.vcd v1.0.0

### Affected Resource(s)
- vcd_vapp_vm

vCloud allows to create VM without using a template. The VM can be booted from iPXE. When using CoreOS matchbox to bootstrap from network, there is no need to use a template. Currently the `template` is a required field. I would like to see the support for creating a blank VM without a template

**Comment by jameswmcnab** [comment]
I would also like to see this and surprised it wasn't possible.

vCloud Director allows you to create a 'new' VM from a bootable ISO as well as from a template.

**Comment by vbauzysvmware** [comment]
Yes, at moment doesn't seem possible. We adding this to our backlog.

**Comment by lvirbalas** [comment]
@jameswmcnab curious which company are you from? As Vaidotas mentioned, this is an important request and we're adding it to backlog. Please consider joining our #vcd-terraform-dev Slack channel through https://code.vmware.com/ to discuss any details.

**Comment by jameswmcnab** [comment]
@lvirbalas I work for a small company you wouldn't have heard of, but we are currently evaluating a vCloud Director solution and as part of that the Terraform integration.

**Comment by elandmancrs** [comment]
Glad to hear this is going into backlog!
Also I'd like to see the ability to create a vApp from a catalogue item that has more than one VM in it.
Reason ask is that we building a predetermined vApp(3 VM's) via build, then capturing it as a catalogue item for users to deploy out.

New issue/request?

**Comment by Didainius** [comment]
> New issue/request?

Would be nice if you could put that in. This will help planning.

Thanks

**Comment by elandmancrs** [comment]
> > New issue/request?
> 
> Would be nice if you could put that in. This will help planning.
> 
> Thanks

done. 
https://github.com/terraform-providers/terraform-provider-vcd/issues/305

**Comment by elandmancrs** [comment]
ping

**Comment by lvirbalas** [comment]
@elandmancrs We're planning to tackle this soon. Would you be open to testing the early build when it's ready?

**Comment by elandmancrs** [comment]
Yes please. The point I'm at in my project, I'm primed for it. Cheers

**Comment by dwtaylornz** [comment]
also looking for this functionality - yes please!

**Comment by vbauzysvmware** [comment]
Hi everyone,
We have PR for this https://github.com/terraform-providers/terraform-provider-vcd/pull/484
Would be helpful for testing it :)

**Comment by Didainius** [comment]
We have this functionality for long time now
