### ISSUE TITLE
Terrafom operation fail if VM /  vApp with VMs containing vcd_internal_disk is deleted from outside TF

### ISSUE THREAD

**Issue by qsc-danielfeiler** [vmware/terraform-provider-vcd#855]
Hello,

Current version of Terraform vcd provider (v3.6.0) does not seem to work in the scenario if some of the vCD resources (vApps or VMs with configured internal Disks) are deleted from vCD manually / outside of terraform. vcd provider just gives a generic error and does not work. To work around the issue in the case of vApp deletion it is necessary to delete vcd_vapp_network  and vcd_vm_internal_disk ressources from the terraform state file.
In the case of VM or internal disk deletion  it is necessary to delete the vcd_vm_internal_disk ressources from the terraform state file.

### Terraform Version
terraform v1.19
terraform vcd provider v3.6.0

### Affected Resource(s)
vcd_vapp_network.vapp-net
vcd_vm_internal_disk

### Expected Behavior
Terraform vcd provider should show an error with the actual missing resource name/ID mentioned.
Terraform vcd provider should re-provision the missing resources.

### Actual Behavior
If the whole vApp is deleted from outside terraform the terraform vcd provider gives following  error message:
```
│ Error: error finding Vapp: [ENF] entity not found
│
│   with vcd_vapp_network.vapp-net,
│   on main.tf line 53, in resource "vcd_vapp_network" "vapp-net":
│   53: resource "vcd_vapp_network" "vapp-net" {
```
After removing the network from the from the terraform state file the following error message apears 
```
Error: [getVm] failed to get vApp: [ENF] entity not found
│
│   with vcd_vm_internal_disk.REPROVM01-Disk01,
│   on main.tf line 89, in resource "vcd_vm_internal_disk" "REPROVM01-Disk01":
│   89: resource "vcd_vm_internal_disk" "REPROVM01-Disk01" {
```
After deleting the internal disk from terraform state, the plan and apply operation succeded.

If only the internal disk is deleted from the VM the following error apears during a terraform plan

```
Error: cannot get internal disk - VM doesn't have internal disks
│
│   with vcd_vm_internal_disk.REPROVM01-Disk01,
│   on main.tf line 89, in resource "vcd_vm_internal_disk" "REPROVM01-Disk01":
│   89: resource "vcd_vm_internal_disk" "REPROVM01-Disk01" {
│
```
after removing the internal disk from terraform state, terraform will re-apply the internal disk correctly.

If the whole VM is deleted the following error is displayed:

```
 Error: [getVm] failed to get VM: [ENF] entity not found
│
│   with vcd_vm_internal_disk.REPROVM01-Disk01,
│   on main.tf line 89, in resource "vcd_vm_internal_disk" "REPROVM01-Disk01":
│   89: resource "vcd_vm_internal_disk" "REPROVM01-Disk01" {
│
```
after removing the internal disk from terraform state, terraform will re-apply the VM and the internal disk correctly.

 terraform "plan", "apply" or "destroy" actions don't work in this scenario.

###Steps to Reproduce

terraform apply and get some vapps/VMs with internal disks provisioned to vCD.
Delete one of the vApps manually from vCD UI, or by using for example vcd-cli.
Run terraform plan, terraform apply or terraform destroy again and it'll fail with the described errors

1. 
- terraform apply and get some vapps/VMs with internal disks provisioned to vCD.
- Delete one of the vApps manually from vCD UI, or by using for example vcd-cli.
- Run terraform plan, terraform apply or terraform destroy again and it'll fail with the described errors
2.
- terraform apply and get some vapps/VMs with internal disks provisioned to vCD.
- Delete one of the internal disks from a VM manually from vCD UI, or by using for example vcd-cli.
- Run terraform plan, terraform apply or terraform destroy again and it'll fail with the described errors
3.
- terraform apply and get some vapps/VMs with internal disks provisioned to vCD.
- Delete one of the in VMs manually from vCD UI, or by using for example vcd-cli.
- Run terraform plan, terraform apply or terraform destroy again and it'll fail with the described errors

Important Factoids
Currently running vCD 10.3.0
A terraform config file is attached to this post. I have used this config to reproduce the described behavior

[main.tf.txt](https://github.com/vmware/terraform-provider-vcd/files/8715512/main.tf.txt)

**Comment by Didainius** [comment]
Hello @qsc-danielfeiler ,
Thanks for reporting the issue - we're aware of it and while not everything is yet fixed, but we have already patched a few resources and hope to gradually fix it everywhere.

**Comment by lvirbalas** [comment]
Referencing:
#611
#783 
#451
