### ISSUE TITLE
Downsizing a vcd_vm_internal_disk is causing an in-place update instead of a replacement

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [vmware/terraform-provider-vcd#857]
Hello there 😄 

When trying to downsize an already existing `vcd_vm_internal_disk` resource, the provider is suggesting an in-place update. As you already know downsizing an existing disk is not possible. When applying the suggested Terraform plan, the API is return an HTTP 400 code which causes the provider to show an error and exit. It would be better if the provider knew about these intricacies and proposed a replacement of the resource. In this way, unnecessarily blocking the entire pipeline will be prevented.

### Terraform Version
Terraform v1.1.6

### Terraform Provider Version
v3.5.1

### Affected Resource(s)
- vcd_vm_internal_disk

### Terraform Configuration Files

```hcl
resource "vcd_vm_internal_disk" "disk1" {
  vapp_name   = "my-vapp"
  vm_name      = "my-vm1"
  bus_type       = "sas"
  size_in_mb    = "13333"
  bus_number = 0
  unit_number = 1
}
```

### Panic Output
```text
Error: error updating VM disks: API Error: 400: [ XXXXXX-XXXXXX-XXXXXXX ] Virtual machine disk sizes may only be increased, not decreased.
```

### Expected Behavior
A replacement of the resource should be proposed.

### Actual Behavior
An in-place update was proposed instead.

**Comment by vbauzysvmware** [comment]
Hi @GeorgiosGoniotakis 

Terraform SDK doesn't allow such conditional checks in reading mode to impact the planning phase on value or value differences. And any other workaround means silently deleting and creating the disk which is not acceptable due sensitivity of data(disk resource).
Though, you may `taint` the resource before running a plan or `apply`.
