### ISSUE TITLE
Storage policy/profile - default disk IOps value not honored

### ISSUE THREAD

**Issue by OnnO14** [vmware/terraform-provider-vcd#859]
**Starting point:**
VCD 10.3.3.1
TF 3.6

**VCD storage policies are configured as follows:**
- IOPS limiting enabled
- Impact placement enabled
- Maximum disk IOPS 5000
- Default disk IOPS 3000

**Issue**:
In case you have enabled the IOPS limit, that can be set on a storage policy/profile, you will run into an issue when using terraform to deploy a disk resource. Not specifying the iops argument results in the following error:

_Error: error updating VM disks: error updating VM disks: API Error: 400: [ ----------- ] Requested disk iops 0 for virtual machine "test2" exceeds maximum allowed iops 5,000._

**Desired solution:**
By default when creating a disk based on a profile, that has IOps limit enforced, it should honor the default IOps as provided by the storage policy/profile. Specifying the iops argument should only be needed to deviate from the default value with a limit to the value as defined as Maximum disk IOPS.

**Comment by vbauzysvmware** [comment]
The change will be released with the provider 3.7.0 version.
