### ISSUE TITLE
resource "vcd_nsxt_app_port_profile"  is forgetting the state

### ISSUE THREAD

**Issue by hungbui78** [vmware/terraform-provider-vcd#860]
Hello,

I have an strange issue with resource "vcd_nsxt_app_port_profile". When I create a port profile with the resource it works fine but if I working on the code and apply new changes to my infra then sometimes it says the error belows even thu I haven´t done any changes in my code to the resource "vcd_nsxt_app_port_profile"  after it has been created.

It seems like it try to recreate the port profile again. Then I need to delete the port profile manually in the webconsole to be able to run my code again. It seems like the state of the resource has automatically disappears in the state file.

```

│ Error: error creating NSX-T Application Port Profile 'CloudOps test port profile2': error creating NSX-T Application Port Profile: error in HTTP POST request: BAD_REQUEST - [ 0ab1d021-0350-46b9-89da-525896bca405 ] Application Port Profile CloudOps test port profile2 already exists in Organization 974fb748-67d3-4dd7-8f50-ce2de4bd7161.
│ 
│   with vcd_nsxt_app_port_profile.custom-ports-profile,
│   on distributed_fw.tf line 76, in resource "vcd_nsxt_app_port_profile" "custom-ports-profile":
│   76: resource "vcd_nsxt_app_port_profile" "custom-ports-profile" {
│ 
``` 

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.6.0

### Affected Resource(s)
Please list the resources as a list, for example:
-  vcd_nsxt_app_port_profile

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
Copy-paste your Terraform configurations here. Please **shrink HCL replicating the bug to minimum** 
without modules. It will help us to respond and replicate the problem quicker. It may also uncover
some HCL error while doing so.

resource "vcd_nsxt_app_port_profile" "custom-ports-profile" {
  
  org = var.vcd_org
  context_id  = data.vcd_org_vdc.existing.id
  name        = "CloudOps test port profile2"
  description = "Application port profile for custom application"

  scope = "TENANT"

  app_port {
    protocol = "ICMPv4"
  }

  app_port {
    protocol = "TCP"
    port     = ["22", "443","80"]
  }

}

For bigger configs you may use [Gist(s)](https://gist.github.com) or a service like Dropbox and
share a link to the ZIP file.
```

### Debug Output
Please provide a link to GitHub [Gist(s)](https://gist.github.com) containing complete debug
output. You can enable debug by using the commands below:
```shell
export TF_LOG_PATH=tf.log            
export TF_LOG=TRACE                  
export GOVCD_LOG_FILE=go-vcloud-director.log
export GOVCD_LOG=true     
```

On Windows the command instead of `export` is `set`.

Replicate the issue after setting the environment variables listed above and it should create two
new files in the working directory: `tf.log` and `go-vcloud-director.log`. The `tf.log` is a general
Terraform debug log (more information about it is in
https://www.terraform.io/docs/internals/debugging.html) while the `go-vcloud-director.log` is a
specific log file for `terraform-provider-vcd` containing debug information about performed API
calls. Please attach both of them to your [Gist](https://gist.github.com).

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

That the port profile not try to recreating it when it has not been deleted

### Actual Behavior
What actually happened?

From time to time the port profile try to recreate it when running terraform apply even thu the port profile has not been changed or deleted.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### User Access rights 
Information about user used. Role and/or more exact rights if it is customized.

Tenant admin right

### Important Factoids
Is there anything atypical about your accounts that we should know?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- Issue #0000
[tf.log](https://github.com/vmware/terraform-provider-vcd/files/8812087/tf.log)
[go-vcloud-director.log](https://github.com/vmware/terraform-provider-vcd/files/8812088/go-vcloud-director.log)

**Comment by Didainius** [comment]
Hello,
I am 99% sure the issue is as detailed here https://github.com/vmware/terraform-provider-vcd/issues/802

Could you double-check that - unfortunately we're not able to fix it as this is not a provider bug, but VCD itself.

**Comment by hungbui78** [comment]
> 

Ty Didainius.

Yes it is the same issue we have :( . Now I know it is a VCD bug, hope it will get fixed in the futre releases of VCD. 

BR

Hung

**Comment by hungbui78** [comment]
But don´t close the caset yet because I want to verify if the resource getting deleted automatically from the state file? I know that i couldn´t fin the resource int the state file when I got that error.

Today I has recreate the prot profile and see it in the state and wait till tomorrow to see the state file again and see if the resource is still there.

hungbui@SELI142646:$ terraform state list |grep vcd_nsxt_app_port;date
vcd_nsxt_app_port_profile.custom-ports-profile
Wed Jun  1 12:25:35 CEST 2022

**Comment by Didainius** [comment]
Hello,
I looked at the code and it should get deleted.
The reason is:
when doing `plan`/`refresh`/`apply` Terraform will "read" your existing resource. Now if the resource with given ID does not exist - it will wipe it from statefile (`d.SetId("")`) so that a new one can be created.

This is correct behavior for Terraform which aids to restore given objects when they are deleted outside of Terraform (UI, CLI, etc). However it doesn't play well with this VCD bug. I am aware this bug is reported to VCD team and they are going to fix it, but don't know anything about timelines.



"read" function for app port profile
```go
func resourceVcdNsxtAppPortProfileRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	vcdClient := meta.(*VCDClient)

	org, err := vcdClient.GetOrgFromResource(d)
	if err != nil {
		return diag.Errorf(errorRetrievingOrg, err)
	}

	appPortProfile, err := org.GetNsxtAppPortProfileById(d.Id())
	if err != nil {
		if govcd.ContainsNotFound(err) {
			d.SetId("")
			return nil
		}
		return diag.Errorf("error getting NSX-T Application Port Profile with ID '%s': %s", d.Id(), err)
	}

	err = setNsxtAppPortProfileData(d, appPortProfile.NsxtAppPortProfile)
	if err != nil {
		return diag.Errorf("error reading NSX-T Application Port Profile: %s", err)
	}

	return nil
}
```
