### ISSUE TITLE
vcd_nsxt_network_imported  should support Distributed virtual port group backed networks

### ISSUE THREAD

**Issue by pauljemmett** [vmware/terraform-provider-vcd#865]
Hello,

### Terraform Version
Terraform v1.2.2
on windows_amd64
+ provider registry.terraform.io/vmware/vcd v3.6.0

### Affected Resource(s)
vcd_nsxt_network_imported

### Terraform Configuration Files
Can't add these currently

### Debug Output
Can't add these currently

### Panic Output
Can't add these currently

### Expected Behavior
When I import a vcd_nsxt_network_imported from a vdc the resource is found and imported so assume I'm using the correct call.
Although, this was an imported "dvswitch from vCenter" and not an NSX-T logical switch, so is a standard port group.

### Actual Behavior
On import of the already created resource into terraform the tfstate has "nsxt_logical_switch_name": null
If I run the script with this value I get:

│ Error: Missing required argument
│
│   with module.name.vcd_nsxt_network_imported.vcd_nsxt_network_imported,
│   on modules\vcd_nsxt_network_imported\main.tf line 27, in resource "vcd_nsxt_network_imported" "vcd_nsxt_network_imported":
│   27:   nsxt_logical_switch_name = null
│
│ The argument "nsxt_logical_switch_name" is required, but no definition was found.

If I change the name it wants to recreate the resource which isn't an option

**Comment by Didainius** [comment]
When `vcd_nsxt_network_imported` was introduced, it could only be backed by NSX-T Logical Switch. Now it can also be backed by Distributed virtual portgroup. VCD provider should catch up with this functionality.
