### ISSUE TITLE
Documentation is "broken"

### ISSUE THREAD

**Issue by echo-devnull** [vmware/terraform-provider-vcd#872]
On the page:  https://registry.terraform.io/providers/vmware/vcd/latest/docs/resources/vapp_vm
Starting from: "Example Usage (using advanced compute settings)"

The documentation is broken / syntax is off.

**Comment by vbauzysvmware** [comment]
Hi, @echo-devnull  Thank you for the report. 
This already has been fixed and reporting issue also exists https://github.com/vmware/terraform-provider-vcd/issues/840.
Closing as duplication.
