### ISSUE TITLE
Add Edge Cluster configuration for VDC Organization

### ISSUE THREAD

**Issue by Nannymeta** [vmware/terraform-provider-vcd#873]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- Configure Edge Cluster for VDC Organization as below 

![image](https://user-images.githubusercontent.com/103997330/175073845-f2bfcc07-3bf8-4d78-9edb-2a9b27d62a61.png)

### New or Affected Resource(s)

- vcd_org_vdc

### References

* Issue #0000

**Comment by mkriegs** [comment]
Hey, any Update here ?

**Comment by Didainius** [comment]
> Hey, any Update here ?

This is in `main` code now and 3.8.0 will have this functionality
