### ISSUE TITLE
vcd_network_routed_v2 error if network already exists

### ISSUE THREAD

**Issue by MarRio81** [vmware/terraform-provider-vcd#900]
Hello,

### Terraform Version
terraform -v
Terraform v1.2.6

### Affected Resource(s)
- vcd_network_routed_v2

### Terraform Configuration Files

<script src="https://gist.github.com/MarRio81/286ba76eadc85b6acf68bec0899405d2.js"></script>

### Debug Output

<script src="https://gist.github.com/MarRio81/bf250eda3fd0c9c4ced200bc4f1ef78d.js"></script>

### Expected Behavior
Should not fail if the resource is already existent and created by terraform in an previous run

### Actual Behavior
Exiting with:
Error: [routed network create v2] error creating Routed network: error creating Org VDC network: error in HTTP POST request: BAD_REQUEST - [ 51f3a6fb-8205-4fa9-b47a-ee0e0b106cf7 ] An organization VDC network with the same name (template_test_network) exists in the organization VDC.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply` again

### User Access rights 
Organization Administrator

**Comment by Didainius** [comment]
Hey. that is interesting - did you get a crash during object creation? Is the statefile in place and not manually modified after creation?

**Comment by MarRio81** [comment]
Nothing of that.
The first run creates the network as expected, on the second run it explains that the Network already exists.

**Comment by Didainius** [comment]
Do you mean you just do `terraform apply` in the same directory with an existing statefile?
Can you just check the statefile after you create the network (the first time)? Does the entry for this network exist?

**Comment by MarRio81** [comment]
You are right it was a corrupted statefile.
