### ISSUE TITLE
vcd_catalog_item - unable to upload ova image to catalog

### ISSUE THREAD

**Issue by DmitryevichD** [vmware/terraform-provider-vcd#933]
Hello,
I get an error when try to upload OVA image to catalog.
I've manually downloaded the OVA image from server using UI and am trying to upload this image to catalog using vcd provider.
 In 20 sec. I catch the message:
```
Error: error uploading media: &errors.errorString{s:"file upload failed. Err: 403 Internal Server Error"}
```

### Terraform Version
Terraform v1.3.4
on linux_amd64
\+ provider registry.terraform.io/vmware/vcd v3.7.0

### Affected Resource(s)
- vcd_catalog_item

#### script
```
resource "vcd_catalog_item" "upload-catalog-item-used-tf" {
  catalog = "test-empty-catalog"

  name                 = "new-template"
  description          = "Copy of exist template that used in VM"
  ova_path             = "debian-base-10.8_original.ova"
  upload_piece_size    = 10
  show_upload_progress = true
}

provider "vcd" {
  org  = "myOrg"
  vdc = "myVDC"
  url  = "myUrl"
  allow_unverified_ssl = "true"
}

terraform {
  required_providers {
    vcd = {
      source = "vmware/vcd"
    }
  }
}

```
#### Console output
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vcd_catalog_item.upload-catalog-item-used-tf will be created
  + resource "vcd_catalog_item" "upload-catalog-item-used-tf" {
      + catalog              = "test-empty-catalog"
      + created              = (known after apply)
      + description          = "Copy of exist template that used in VM"
      + id                   = (known after apply)
      + name                 = "new-template"
      + ova_path             = "debian-base-10.8_original.ova"
      + show_upload_progress = true
      + upload_piece_size    = 10
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vcd_catalog_item.upload-catalog-item-used-tf: Creating...
vcd_catalog_item.upload-catalog-item-used-tf: Still creating... [10s elapsed]
vcd_catalog_item.upload-catalog-item-used-tf: Still creating... [21s elapsed]
vcd_catalog_item.upload-catalog-item-used-tf: Still creating... [31s elapsed]
╷
│ Error: error uploading media: &errors.errorString{s:"file upload failed. Err: 403 Internal Server Error"}
│ 
│   with vcd_catalog_item.upload-catalog-item-used-tf,
│   on install-ova.tf line 1, in resource "vcd_catalog_item" "upload-catalog-item-used-tf":
│    1: resource "vcd_catalog_item" "upload-catalog-item-used-tf" {
│ 
```

On UI can find a task details:
![Selection_047](https://user-images.githubusercontent.com/20191905/202545666-4a7e4ec4-f7f8-4cad-bddc-fb67d8605c45.png)

**Comment by dataclouder** [comment]
Hi
Thanks for submitting this issue.
I see some conflicting facts in your report:
* The task you are reporting says it was canceled by a user. This doesn't seem to be the reason for the failed upload.
* The error message mentions an internal server error, which is usually associated with 500+ error code, but uses code 403, which signifies access to resource is forbidden.

Could you repeat the operation with the logs enabled and then submit the part of the log that contains the request and the error? Use a Github gist if you can't isolate the needed part. 
To enable the logs, add `logging = true` to the provider's block.

**Comment by dataclouder** [comment]
So, the task was canceled after failure, by the same process that tried to upload. So, at least this one is accounted for. The catalog item resource tried to upload, the process failed, and it canceled the task. Although the task in the log is not the same as the one shown in your screen shot. That is also plausible, because this operation can use several tasks.

What is not clear is the kind of response you are receiving (text/html instead of XML) and the mixed error message (403 = unauthorized, and "internal server error" = something is not working as expected).

I still don't have enough data to understand the problem. Could you post the requests and responses occurring in the two minutes  before the one you have already provided?

Also, which version of VCD are you using?
And, is the VCD using a load-balancer for access? (This is a bit tricky if you only have tenant credentials, but if you can find out, this would give us a hint)

**Comment by DmitryevichD** [comment]
At this [gist](https://gist.github.com/DmitryevichD/73c5733f432a4591641e04289b23f1df) you can find all request and response that sent to vcd. I've deleted all headers and body because they may consist sensitive date. I hope this info will help you find issue

**Comment by Didainius** [comment]
@DmitryevichD ,
Thanks for all the logs. We have looked at it and it is quite clear you have some sort of WAF or other security device in the path to VCD.

What happens is it intercepts the PUT request for image upload

```
2022/11/18 13:39:28 PUT https://cloud-canada.continent8.com/transfer/45535893-c757-462b-84ff-6e0991cf6ab5/vm-79739fcd-793f-43b0-969b-7cd3e08cecd3-disk-0.vmdk
2022/11/18 13:39:28 --------------------------------------------------------------------------------
2022/11/18 13:39:28 Req header:
2022/11/18 13:39:28 	....
2022/11/18 13:39:31 Request data: [10485760]
version=1
CID=ad83e0b1 
parentCID=ffffffff 
createType="streamOptimized" 

# Extent description
RDONLY 20971520 SPARSE "generated-stream.vmdk"

# The Disk Data Base 
#DDB

ddb.adapterType = "buslogic"
ddb.deletable = "true"
ddb.geometry.biosCylinders = "1024"
ddb.geometry.biosHeads = "255"
ddb.geometry.biosSectors = "63"
ddb.geometry.cylinders = "16383"
ddb.geometry.heads = "16"
ddb.geometry.sectors = "63"
ddb.longContentID = "7ab396cae811a4f9744540ddeff54beb"
ddb.virtualHWVersion = "14"
```


And in the end it is not VCD that returns HTTP 403, but your security device, which sends back an HTML page, which looks like this when rendered:
![image](https://user-images.githubusercontent.com/15804230/202783488-a11b02fc-dc1a-4fa5-a260-54c718a656f0.png)

To move forwards we'd have to understand what exactly does your security device does not like in that request. Depending on this it might be a few actions:
* (For us) add some missing detail to payload (maybe a missing header, or something else)
  * Can you successfully upload your image using VCD UI? 
* (For your security team) add this endpoint to allowlist so that requests do not get blocked

**Comment by DmitryevichD** [comment]
> Can you successfully upload your image using VCD UI?
Yep, when I manually upload an image everything is fine

Thanks. I will try to allow this point in WAF and repeat my attempt.

**Comment by Didainius** [comment]
@DmitryevichD ,
Just want to check if you were able to identify a solution. Also curious if you know what exactly does your WAF not like in the request coming from terraform provider?

**Comment by DmitryevichD** [comment]
I tried to find  some restriction rules in the WAF but I found nothing. 
Perhaps interesting point is that when I launch TF from VM that located in vCloude I catched the same status 403.
To solve this issue we had to change current flow and now we don't try to upload template to catalog.

Below I've pinned the headers of requests. First section contains logs that I've got from the terraform (403). Second I've cut from my browser (200)

<details>
<summary>Headers</summary>

```
2022/11/18 13:39:28 PUT https://cloud-canada.continent8.com/transfer/*****-c757-****/vm-****-793f-****-disk-0.vmdk
2022/11/18 13:39:28 --------------------------------------------------------------------------------
2022/11/18 13:39:28 Req header:
2022/11/18 13:39:28     Authorization: [********]
2022/11/18 13:39:28     User-Agent: [terraform-provider-vcd/v3.7.0 (linux/amd64; isProvider:false)]
2022/11/18 13:39:28     X-Vmware-Vcloud-Access-Token: [********]
2022/11/18 13:39:28     Accept: [application/*+xml;version=35.0]
2022/11/18 13:39:28     X-Vmware-Vcloud-Token-Type: [Bearer]
2022/11/18 13:39:31 Request data: [10485760]
```

```
PUT https://cloud-canada.continent8.com/transfer/****-94e7-****/vm-**39fcd-****-disk-0.vmdk
Accept: application/*+xml;version=37.0
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Bearer []
Connection: keep-alive
Content-Length: 52428800
Content-Range: bytes 0 - 52428800 / 1753695232
Content-Type: application/*+xml;charset=utf-8
Cookie: cookiesession1=678A3E28B480D2224102698AD6CA4314; vcloud_jwt=*****; vcloud_session_id=****7532f2b4e***; vcd=srv-4jPYbfZmHt***
Host: cloud-canada.continent8.com
Origin: https://cloud-canada.continent8.com
Referer: https://cloud-canada.continent8.com/tenant/*****/libraries/catalogs/****-b3ec-4509-****/catalog-vapp-templates
sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
X-Requested-With: XMLHttpRequest
X-VMWARE-VCLOUD-AUTH-CONTEXT: ****
X-VMWARE-VCLOUD-TENANT-CONTEXT: 4cc8f3e7-2776-****
```

</details

**Comment by Didainius** [comment]
Ok, so that means your vendor is having some WAF in front of VCD. Would still be interesting to find out the reason they block these requests, but I am not sure if you can ask them

**Comment by DmitryevichD** [comment]
@Didainius You are right
Providers WAF blocks this requests. 
I wrote email to the support and they confirmed this. 
Provider will add our URL to white list and after that all should be ok.

Thanks for your help. The issure is closed.
