### ISSUE TITLE
CSE 4 Support

### ISSUE THREAD

**Issue by returntrip** [vmware/terraform-provider-vcd#947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When are you planning to support CSE 4?

**Comment by adambarreiro** [comment]
Hi @returntrip, thanks for your interest in CSE :)
I'll come back as soon as possible with an answer.

**Comment by adambarreiro** [comment]
Hi @returntrip, with the release of v3.9.0, we added a new guide to install and configure CSE v4.0 in VCD.
We will work now in adding some examples for clusters creation.
I hope it helps!
