### ISSUE TITLE
wrong vcd_org_vdc_access_control group_id

### ISSUE THREAD

**Issue by bogi0704** [vmware/terraform-provider-vcd#950]
After re-applying a `vcd_org_vdc_access_control` configuration, the resource is always updated in-place. This happens because the group_id is applied using the group urn e.g. `"urn:vcloud:group:6811eef7-533e-4561-a663-9f84cd0d313a"`, whereas the read only gets the ID `"6811eef7-533e-4561-a663-9f84cd0d313a"`.

### Terraform Version
Terraform v1.3.6

### Affected Resource(s)
- vcd_org_vdc_access_control

### Terraform Configuration Files

```hcl
resource "vcd_org_group" "main" {
  org           = var.org_name
  provider_type = "SAML"
  name          = vcd_org_vdc.main.name
  role          = "Defer to Identity Provider"
}

resource "vcd_org_vdc_access_control" "main" {
  org                  = var.org_name
  vdc                  = vcd_org_vdc.main.name
  shared_with_everyone = false

  shared_with {
    group_id     = vcd_org_group.main.id
    access_level = "ReadOnly"
  }
}
```

### Expected Behavior
No Update should take place

### Actual Behavior
The `vcd_org_vdc_access_control` will be updated in-place with the same group id.

```shell
  ~ resource "vcd_org_vdc_access_control" "main" {
        id                   = "urn:vcloud:vdc:f4f9c6a9-db42-46cb-a55d-45ba970ec6a3"
        # (3 unchanged attributes hidden)

      - shared_with {
          - access_level = "ReadOnly" -> null
          - group_id     = "6811eef7-533e-4561-a663-9f84cd0d313a" -> null
          - subject_name = "testvdc" -> null
        }
      + shared_with {
          + access_level = "ReadOnly"
          + group_id     = "urn:vcloud:group:6811eef7-533e-4561-a663-9f84cd0d313a"
          + subject_name = (known after apply)
        }
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform plan`

**Comment by Didainius** [comment]
@bogi0704 , v3.8.2 is now released with this fix.
