### ISSUE TITLE
 Add DNS field for external networks backed by NSX-t Segment

### ISSUE THREAD

**Issue by marwanhammad** [vmware/terraform-provider-vcd#964]
n external networks backed by nsx-t vlan segment , we don't have an option to add DNS servers unlike vlan backed by vds one.
as a result guest customization set no DNS servers in the OS level

We have confirm it's a UI miss, as it is available in the openAPI  https:///cloudapi/1.0.0/externalnetworks/<urn: id>
however applying the terraform script again remove this setting back to null.

so would u please update vcd_external_network_v2 to accept DNS setting for NSX-t as it's access for NSX-v version

![image](https://user-images.githubusercontent.com/65039966/208431757-895db903-7c97-4a58-860e-2d675872320e.png)

**Comment by Didainius** [comment]
@marwanhammad ,
Thanks for the issue. I am looking at it. I also wanted to check with you - does `dnsSuffix` work for you? Can you set it via API?
