### ISSUE TITLE
Cannot subscribe to a vSphere content library

### ISSUE THREAD

**Issue by Zypheros** [vmware/terraform-provider-vcd#967]
Hello,

### Terraform Version

Terraform v1.3.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/vsphere v2.2.0
+ provider registry.terraform.io/vmware/vcd v3.8.1

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_subscribed_catalog

### Terraform Configuration Files

```hcl
data "vsphere_datacenter" "datacenter_a" {
  name = "vsphere datacenter"
}

data "vsphere_datastore" "publisher_datastore" {
  name          = "vsphere datastore"
  datacenter_id = data.vsphere_datacenter.datacenter_a.id
}

resource "vsphere_content_library" "publisher_content_library" {
  name            = "terraformTest"
  description     = "testing new functionallity"
  storage_backing = [data.vsphere_datastore.publisher_datastore.id]
  
  publication {
    authentication_method = "NONE"
    published = "true"
  }
}

resource "vcd_subscribed_catalog" "subscriber" {
  org = "CustomerX"
  name             = "terraform_catalog"

  delete_force     = "true"
  delete_recursive = "true"

  subscription_url      = vsphere_content_library.publisher_content_library.publication[0].publish_url
  make_local_copy       = true
  subscription_password = ""
}
```

### Expected Behavior
Terraform should have created a subscribed catalog with the `subscription_url` parameter set to the publish url of the content library.

### Actual Behavior
I got an error message:

```log
Error: error creating catalog terraform_catalog from subscription: subscription URL 'https:vcenter-fqdn:443/cls/vcsp/lib/17o55s4565-aso3-4sd76o-a5a63s5-2gh846sd/lib.json' should end with a '/'
```
Just a note, this works fine if set the url manually in the vcd user interface.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### User Access rights 
System Administrator

**Comment by Zypheros** [comment]
Ah, then it makes sense with the error message. Thanks for the reply :)
Great work with the provider btw!

**Comment by dataclouder** [comment]
Hi @Zypheros 
I am apply a fix for this issue in PR #972 
Would you be able to build a provider out of [this branch](https://github.com/dataclouder/go-vcloud-director/tree/fix-catalog-access) and try if your problem is resolved? I have added a test for the case you present here, but your input would be appreciated.

**Comment by Zypheros** [comment]
Of course, I will test the build now.

**Comment by Zypheros** [comment]
Hi again @dataclouder.
I didn't realize that the testing the build would require me to use go, and because I haven't used go at all, progress with testing the new build is slow.

**Comment by dataclouder** [comment]
Hi @Zypheros.
You don't need to "use Go", but just to have it installed in your system, and run `make install` in the top directory of the repository. That command will install the provider in your local host, and the next time you run `terraform init`, it will pick up the provider that you have just built

**Comment by dataclouder** [comment]
Implemented and merged to main branch
