### ISSUE TITLE
vcd_vdc_group - changing starting_vdc_id after VDC Group is created

### ISSUE THREAD

**Issue by rvvliet78** [vmware/terraform-provider-vcd#968]
Hi All,

I'm having an issue with the starting_vdc_id of the vcd_vdc_group resource and the removal of a vdc.

When we create an environment for a customer with for example a Prod and Acc vdc, we can add them to the vdcgroup.
It makes sense to use the prod as the primary as it's not likely that a customer want's their prod vdc removed.
But never say never, so we have to assume that this could happen.

So when we want to remove the VDC which is the starting_vdc_id the whole vdcgroup, including the distrubuted firewall will be removed.
This is pretty nasty.

Am I missing something or is it not possible to remove/replace the "starting_vdc_id" without re-creating the entire vdcgroup?

**Comment by Didainius** [comment]
Hello @rvvliet78,
Terraform schema has some limitations which doesn't allow making it very convenient, but there is a way around it.

The `starting_vdc_id` is **only** used when creating VDC Group (if you look up the UI, it also prompts for "Starting VDC", when creating).

You could go around it this way


Step 1 - your initial VDC Group creation script:

```hcl
resource "vcd_vdc_group" "test1" {
  org                   = "cloud"
  name                  = "TestAccVcdVdcGroupResource"
  starting_vdc_id       = vcd_org_vdc.newVdc.0.id
  participating_vdc_ids = vcd_org_vdc.newVdc.*.id
  
  dfw_enabled           = "false"
  default_policy_status = false
}
```

Then, if you are removing that `starting_vdc_id` `vcd_org_vdc.newVdc.0.id` for the next iteration you could leverage Terraform's built-in [`lifecycle`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle) parameter and switch the `starting_vdc_id` to some other `vdc_id` in your group:
```hcl
resource "vcd_vdc_group" "test1" {
  org                   = "cloud"
  name                  = "TestAccVcdVdcGroupResource"
  starting_vdc_id       = vcd_org_vdc.newVdc.1.id # <---- changed to other VDC
  participating_vdc_ids = vcd_org_vdc.newVdc.*.id
  
  dfw_enabled           = "false"
  default_policy_status = false

  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      starting_vdc_id,
    ]
  }
}
```

**Comment by rvvliet78** [comment]
Thanks Didanius,
That is one very nice workaround, works like a charm.

**Comment by Didainius** [comment]
@rvvliet78 ,
I am closing this one now as there is no very convenient solution due to Terraform schema limitations.
