### ISSUE TITLE
Improve data source vcd_catalog_vapp_template for working with deleted templates

### ISSUE THREAD

**Issue by NilsBusche** [vmware/terraform-provider-vcd#971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is the data source `vcd_catalog_vapp_template` which allows for querying a given catalog for a matching vApp template. If there is no matching template, the data source throws an error.

In our infrastructure we regularly update our vApp templates to newest OS versions etc. Therefore we have a timestamp in the vApp template names, so we can create new templates and after testing we can update our Terraform configuration to use these new templates. After some time we delete old templates, so they cannot be used anymore.

This now leads into following problem: Assume we built a VM using `vcd_vapp_vm` resource some time ago using the data source `vcd_catalog_vapp_template` for getting the template ID. Now we delete this template as there is a newer one and the old one is not necessary anymore. This would cause all VMs using the old template name in their configuration to end up in errors as the data source cannot find those old template anymore.

To prevent this situation I would suggest to implement a second data source, called `vcd_catalog_vapp_templates`, to allow querying for multiple templates matching the given name (maybe with possibility for sorting by date etc.) and returning an empty list if there was no matching template but without throwing an error. This idea basically is the same as the AWS provider does it with `aws_ami_id` and `aws_ami_ids`. This would allow us to deal with this by adding some conditional in the `vapp_vm` resource.
Another idea would be to add an attribute like `no_fail` or something in the current `vcd_catalog_vapp_template` data source to have the opportunity to decide if the data source should fail or not when there is no matching template.

### New or Affected Resource(s)

* `vcd_catalog_vapp_template`
* Suggestion for new resource: `vcd_catalog_vapp_templates`

#### Current configuration
```hcl
data "vcd_catalog" "catalog" {
  org  = "ORG0001"
  name = "catalog-abc"
}

data "vcd_catalog_vapp_template" "vapp_template" {
  org        = "ORG0001"
  catalog_id = data.vcd_catalog.catalog.id
  name       = "template-123"
}

output "template_id" {
  value = data.vcd_catalog_vapp_template.vapp_template.id
}
```
#### Possible improvement (idea 1)
```hcl
data "vcd_catalog" "catalog" {
  org  = "ORG0001"
  name = "catalog-abc"
}

data "vcd_catalog_vapp_templates" "vapp_templates" {
  org        = "ORG0001"
  catalog_id = data.vcd_catalog.catalog.id
  name       = "template-123"
}

output "template_id" {
  value = length(data.vcd_catalog_vapp_template.vapp_templates) == 0 ? "not found" : data.vcd_catalog_vapp_template.vapp_templates[0].id
}
```
#### Possible improvement (idea 2)
```hcl
data "vcd_catalog" "catalog" {
  org  = "ORG0001"
  name = "catalog-abc"
}

data "vcd_catalog_vapp_template" "vapp_template" {
  org        = "ORG0001"
  catalog_id = data.vcd_catalog.catalog.id
  name       = "template-123"
  no_fail = true
}

output "template_id" {
  value = data.vcd_catalog_vapp_template.vapp_template.id == null ? "not found" : data.vcd_catalog_vapp_template.vapp_template.id
}
```

**Comment by dataclouder** [comment]
Hi,
Thanks for submitting this request.
I wonder whether you could use the properties `number_of_vapp_templates` and `vapp_template_list` in combination with the [Terraform `contains` function](https://developer.hashicorp.com/terraform/language/functions/contains) to achieve what you need.

**Comment by dataclouder** [comment]
I have a question of my own. Suppose we have the capability of not failing the data source: the VM will still need a vApp template ID to complete its reading, and if the new ID doesn't match, Terraform will trigger a rebuild. How would you handle it?

**Comment by NilsBusche** [comment]
Hi @dataclouder,

thanks for your suggestion regarding `vapp_template_list`. Using this and the `contains` function works for us.

Regarding your second question: We already had set `ignore_changes` for the catalog/template attributes in `vcd_vapp_vm` resource. Using the suggested functionality this now allows us to assign a "dummy" string (`WARNING:ImageNotFound`), if the template does not exist anmyore. This leads into a more or less good error message if the template does not exist at initial VM creation, but definitely the cause for the error is understandable for our admins. And after that, during lifetime of the VM, it does not matter if the template gets removed as the attribute is ignored then.

This is our config now basically:
```hcl
variable "template_name" {
  default = "template-123"
}

data "vcd_catalog" "catalog" {
  org  = "ORG0001"
  name = "catalog-abc"
}

data "vcd_catalog_vapp_template" "vapp_template" {
  count = contains(data.vcd_catalog.catalog.vapp_template_list, var.template_name) ? 1 : 0

  org        = "ORG0001"
  catalog_id = data.vcd_catalog.catalog.id
  name       = var.template_name
}

[...]

resource "vcd_vapp_vm" "vm" {
  lifecycle {
    ignore_changes = [
      vapp_template_id,
    ]
  }

  vapp_template_id = length(data.vcd_catalog_vapp_template.vapp_template) > 0 ? data.vcd_catalog_vapp_template.vapp_template[0].id : "WARNING:ImageNotFound"
  
  [...]
  
}
´´´

**Comment by NilsBusche** [comment]
Yes, the issue is resolved for me. Thanks!
