### ISSUE TITLE
Add support for Kubernetes Container Clusters plug-in resources

### ISSUE THREAD

**Issue by janaurka** [vmware/terraform-provider-vcd#979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

VCD can CRUD Kubernetes / Tanzu Kubernetes Grid Clusters, through the `Kubernetes Container Clusters plug-in` (maybe it’s also called `Container Service Extension plug-in for VMware Cloud Director.`, I’m not 100% sure tbh). Currently there are no resources regarding this plug-in. It would be great to have the possibility to work with Kubernetes/TKG clusters using this `vcd` terraform provider.

Plugin/Extension documentation: https://docs.vmware.com/en/VMware-Cloud-Director/10.2/VMware-Cloud-Director-Tenant-Portal-Guide/GUID-8C05E8F0-2F08-44C9-A016-D383205039E1.html

**Comment by Didainius** [comment]
Hello @janaurka ,
Are you looking for this? https://registry.terraform.io/providers/vmware/vcd/latest/docs/guides/container_service_extension_3_1_x

**Comment by janaurka** [comment]
Hey @Didainius . Hmm honestly I am not sure. I do have a VCD with the Container Service Extension installed and I would like to leverage this to build me a K8s cluster.

When I understand your code correctly, then this is purely installing the Extensions, allowing users to then create K8s clusters in the WebUI?

cheers

**Comment by adambarreiro** [comment]
Hi @janaurka, yes, right now the guide and resources only support installing the extensions (and for CSE 3.1.x). The Kubernetes clusters are then created manually in web UI.

We have also this query to add support for CSE 4.0, are you using this version already? #947
What resources would fit your needs, an hypothetical `vcd_k8s_cluster` or you have more?

**Comment by janaurka** [comment]
Hi @adambarreirom, yeah something like `vcd_k8s_cluster` (which looks kind lika https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster or https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) would be amazing. 

> We have also this query to add support for CSE 4.0, are you using this version already?

Honestly, I don’t know, since I have only VCD non-admin access so far and was asked to test the K8s feature. And since I mostly work with EKS/AKS/etc where there is proper TF support, I wanted to explore this option with VCD/CSE as well.

**Comment by adambarreiro** [comment]
Thanks @janaurka, we are working on adding support for Kubernetes clusters, I will update this issue once we get more info about it.

**Comment by adambarreiro** [comment]
Hi @janaurka, with the release of the v3.10.0 of the provider we have created a new guide to create Kubernetes clusters using CSE v4.0:
https://registry.terraform.io/providers/vmware/vcd/latest/docs/guides/container_service_extension_4_0_cluster_management
