### ISSUE TITLE
default_compute_policy_id is not optional when placement policies are set

### ISSUE THREAD

**Issue by bogi0704** [vmware/terraform-provider-vcd#997]
### Terraform Version
```
Terraform v1.3.8
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.8.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_org_vdc

### Terraform Configuration Files

```hcl
resource "vcd_org_vdc" "geo" {
  name        = "VDC"
  description = "Test"
  org         = vcd_org.main.name

  allocation_model  = "AllocationVApp"
  network_pool_name = "nPool"
  provider_vdc_name = "GEO"

  compute_capacity {
    cpu {
      allocated = 0
      limit     = 0
    }

    memory {
      allocated = 0
      limit     = 0
    }
  }

  storage_profile {
    name    = "Intermediate-Mirrored"
    limit   = 0
    default = true
  }

  network_quota     = 20
  vm_quota          = 0
  memory_guaranteed = 0
  cpu_guaranteed    = 0
  cpu_speed         = 2000
  nic_quota         = 0

  enabled                  = true
  enable_thin_provisioning = true
  enable_fast_provisioning = false
  enable_vm_discovery      = true
  delete_force             = true
  delete_recursive         = true
  vm_placement_policy_ids  = [data.vcd_vm_placement_policy.site1.id, data.vcd_vm_placement_policy.site2.id]
}

## Placement Policies
data "vcd_provider_vdc" "geo_pvdc" {
  name = "GEO"
}

data "vcd_vm_placement_policy" "site1" {
  name            = "site1"
  provider_vdc_id = data.vcd_provider_vdc.geo_pvdc.id
}

data "vcd_vm_placement_policy" "site2" {
  name            = "site2"
  provider_vdc_id = data.vcd_provider_vdc.geo_pvdc.id
}
```

### Expected Behavior
The VDC should have been created with the two placement_policies set, but without explicitly setting a default.

### Actual Behavior
The VDC could not be created, because the `default_compute_policy_id` is not set. This works in the UI.
╷
│ Error: error assigning VM Compute Policies to VDC: `default_compute_policy_id`  is not present in any of `[vm_sizing_policy_ids vm_placement_policy_ids]`
│ 
│   with vcd_org_vdc.geo,
│   on 020_vdc.tf line 1, in resource "vcd_org_vdc" "geo":
│    1: resource "vcd_org_vdc" "geo" {
│ 
╵

### Steps to Reproduce
1. `terraform apply`

### User Access rights 
System Administrator

### Important Factoids
VCD Version 10.4.1.20912624

**Comment by adezxc** [comment]
Hello @bogi0704, thanks for creating this issue.

This is the intended behavior, because a VDC is created with a default sizing policy which can't be removed if it's the only one, so if we would like to add sizing policies without choosing a default one amongst them, it would require tinkering on the provider's side to have a consistent plan including the auto-generated sizing policy. 

Is there maybe a specific use case why you would need this functionality?

**Comment by bogi0704** [comment]
Hi @adezxc,

but this issue occurs when setting the `vm_placement_policy_ids`, not the `vm_sizing_policy_ids`. Looking at the docs it does say that this is expected behaviour:

```
[vm_placement_policy_ids] - (Optional, v3.8+, VCD 10.2+) Set of IDs of VM Placement policies that are assigned to this VDC. This field requires `default_compute_policy_id` to be configured together.
```

What is weird to me that setting a default is not required when you do all this via the UI.

Anyways, I have worked around this issue by creating another Placement Policy which we are using as the default. So this is not really an issue for me anymore, rather an inconsistency in behaviour compared to the UI.

**Comment by adezxc** [comment]
Sorry, maybe my response wasn't clear, but in VDC, both VM Placement policies and sizing policies are tied together as compute policies, and when creating a new VDC, the pre-created sizing policy is assigned as the default, like in the screenshot: 
![image](https://user-images.githubusercontent.com/16798732/234056263-3f1ccffd-99b4-4950-9679-c73446d7ee3e.png)

Basically, if we don't request a default placement policy ID, on the next plan it would return that something has changed, as a default one has been set, but by VCD itself, not Terraform.

**Comment by bogi0704** [comment]
Ok, that makes sense.
