### ISSUE TITLE
Destruction of VDCs does not work when they are part of a VDC group

### ISSUE THREAD

**Issue by bogi0704** [vmware/terraform-provider-vcd#998]
Removing a VDC from a configuration does not work. The user is forced to remove the VDC from the VDC group manually before continuing to remove it.

### Terraform Version
Terraform v1.3.8
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.8.2

### Affected Resource(s)
Please list the resources as a list, for example:
- vcd_org_vdc
- vcd_vdc_group

### Terraform Configuration Files

```hcl
resource "vcd_vdc_group" "main" {
  org                   = "VDC"
  name                  = "vdc-group"
  description           = "Test"
  starting_vdc_id       = vcd_org_vdc.geo.id
  participating_vdc_ids = [vcd_org_vdc.geo.id, vcd_org_vdc.geo2.id]
  dfw_enabled           = true
  default_policy_status = true
}

resource "vcd_org_vdc" "geo" {
  name        = "VDC"
  description = "Test"
  org         = vcd_org.main.name

  allocation_model  = "AllocationVApp"
  network_pool_name = "nPool"
  provider_vdc_name = "GEO"

  compute_capacity {
    cpu {
      allocated = 0
      limit     = 0
    }

    memory {
      allocated = 0
      limit     = 0
    }
  }

  storage_profile {
    name    = "Intermediate-Mirrored"
    limit   = 0
    default = true
  }

  network_quota     = 20
  vm_quota          = 0
  memory_guaranteed = 0
  cpu_guaranteed    = 0
  cpu_speed         = 2000
  nic_quota         = 0

  enabled                  = true
  enable_thin_provisioning = true
  enable_fast_provisioning = false
  enable_vm_discovery      = true
  delete_force             = true
  delete_recursive         = true
}

resource "vcd_org_vdc" "geo2" {
  name        = "VDC2"
  description = "Test"
  org         = vcd_org.main.name

  allocation_model  = "AllocationVApp"
  network_pool_name = "nPool"
  provider_vdc_name = "GEO"

  compute_capacity {
    cpu {
      allocated = 0
      limit     = 0
    }

    memory {
      allocated = 0
      limit     = 0
    }
  }

  storage_profile {
    name    = "Intermediate-Mirrored"
    limit   = 0
    default = true
  }

  network_quota     = 20
  vm_quota          = 0
  memory_guaranteed = 0
  cpu_guaranteed    = 0
  cpu_speed         = 2000
  nic_quota         = 0

  enabled                  = true
  enable_thin_provisioning = true
  enable_fast_provisioning = false
  enable_vm_discovery      = true
  delete_force             = true
  delete_recursive         = true
}

```

### Debug Output
https://gist.github.com/bogi0704/c644f86509502b677691be058f96b8f2

### Expected Behavior
The VDC should have been deleted

### Actual Behavior
```shell
Plan: 0 to add, 1 to change, 1 to destroy.
vcd_org_vdc.geo2: Destroying... [id=urn:vcloud:vdc:fdf1a0fc-4bc3-4836-b788-a735eca17aa1]
╷
│ Error: error removing VDC VDC2, err: error deleting vdc: API Error: 409: [ 5c93a337-e3bf-42aa-b062-ddacad1966ba ] VDC2 is participating in VDC Groups [vdc-group]. Remove the VDC from the VDC Group(s) and try again.
│ 
│ 
╵
```

### Steps to Reproduce
1. `terraform apply` - create the VDCs and groups
2. remove the VDC from configuration and the array in the `vcd_vdc_group` resource
3. `terraform apply`

A `terraform destroy` actually works, because it first removes the group and the VDCs afterwards.

### User Access rights 
System Administrator

### Important Factoids
VCD Version 10.4.1.20912624

**Comment by Didainius** [comment]
Hello @bogi0704,
I will have to check it, but I am afraid there is not much we can do if Terraform performs actions on dependencies that way. The provider plugin has no control over the order that Terraform modifies resources.

**Comment by carmine73** [comment]
I'm start working with `vcd_vdc_group` and I've realized it's a pain destroying resources underneath.
any chance to add `delete_force` to vdc group resource?

**Comment by Didainius** [comment]
https://github.com/vmware/terraform-provider-vcd/issues/1009#issuecomment-1651028870
