### ISSUE TITLE
vcd_vapp_org_network does not work properly with IPv6 networks in NSX-T

### ISSUE THREAD

**Issue by NilsBusche** [vmware/terraform-provider-vcd#999]
### Terraform Version
```
Terraform v1.3.8
on linux_amd64
+ provider registry.terraform.io/vmware/vcd v3.8.2
```

### Affected Resource(s)
- vcd_vapp_org_network

### Terraform Configuration Files

```hcl
resource "vcd_vapp" "vapp" {
  name = "test-vapp"
}

resource "vcd_vapp_org_network" "network1" {
  vapp_name        = vcd_vapp.vapp.name
  org_network_name = "network-IPv6"
}

resource "vcd_vapp_org_network" "network2" {
  depends_on = [vcd_vapp_org_network.network1]

  vapp_name        = vcd_vapp.vapp.name
  org_network_name = "network-IPv4"
}
```

### Expected Behavior
- The vapp should be created
- The IPv6 network should be attached
- The IPv4 network should be attached

### Actual Behavior
- The vapp gets created
- The IPv6 network gets attached
- The attachment of the IPv4 network fails:
```
│ Error: error creating vApp org network. &errors.errorString{s:"operation error: task did not complete successfully:  [500:INTERNAL_SERVER_ERROR] - [ c532b75e-6483-448c-b0c0-d1e260f90d3e ] class java.lang.NullPointerException - task error: [500 - INTERNAL_SERVER_ERROR] [ c532b75e-6483-448c-b0c0-d1e260f90d3e ] class java.lang.NullPointerException"}
│
│   with vcd_vapp_org_network.network2,
│   on main.tf line 20, in resource "vcd_vapp_org_network" "network2":
│   20: resource "vcd_vapp_org_network" "network2" {
```

### Steps to Reproduce
1. `terraform apply`

### User Access rights 
A provider user was used

### Important Factoids
- The `depends_on` is only used to make the order clear and reproducible. If you switch attachment order of the networks (so at first the IPv4 and then the IPv6 network) everything works as expected
- The issue only occurs in NSX-T environments
- We already opened a VMware support case and the cause for this problem could be identified: For working with IPv6 networks it is required to send the `SubnetPrefixLength` attribute within the updated content of the `NetworkConfigurationSection`. The Terraform provider currently does not send this attribute, so this causes the null pointer exception. In a future release of vCloud director there will be an error instead of the exception but the attribute will be still required. So this should be fixed in the provider.

### References
- VMware support case SR 23395539201

**Comment by adezxc** [comment]
Hello @NilsBusche,
You are correct, right now the `vcd_vapp_network` resource doesn't handle subnet prefix length and I am currently working on introducing it.

**Comment by NilsBusche** [comment]
Hi @adezxc 

I can confirm it is working for us now.

Thanks!
